const source = {
  repo: 'https://github.com/kyoo-147/Autopilot_and_FSD',
  readme: 'https://github.com/kyoo-147/Autopilot_and_FSD/blob/main/README.md',
  openpilot: 'https://comma.ai/openpilot',
  comma: 'https://comma.ai/',
  intuition: 'https://appliedintuition.com/',
  roboracer: 'https://roboracer.ai/'
};

const visualMedia = {
  '/': { src: '/products/media/autopilot/model.jpeg', alt: 'Project scale-model autonomous vehicle on its documented test surface', caption: 'PROJECT SOURCE / SCALE-MODEL VEHICLE / CAPABILITY NOT INFERRED FROM IMAGE' },
  '/vehicle/': { src: '/products/media/autopilot/track.jpeg', alt: 'Scale-model vehicle on a BFMC-style test track', caption: 'PROJECT SOURCE / TEST-TRACK CONTEXT / CURRENT OPERATION UNVERIFIED' },
  '/hardware/': { src: '/products/media/autopilot/hardware-connection.jpg', alt: 'Project hardware connection diagram', caption: 'PROJECT SOURCE / HARDWARE CONNECTION REFERENCE' },
  '/localization/': { src: '/products/media/autopilot/map.jpeg', alt: 'Local map representation documented by the project', caption: 'PROJECT SOURCE / LOCAL MAP REFERENCE / ACCURACY NOT CLAIMED' },
  '/software/': { src: '/products/media/autopilot/work.jpeg', alt: 'Project workbench with scale-model vehicle', caption: 'PROJECT SOURCE / BUILD RECORD / RUNTIME NOT INFERRED' }
};

const page = (path, title, description, headline, lede, kind, visualTitle, sections, cta = { title: 'Read the source trail', body: 'Start with the public references. No deployment, benchmark, or commercial availability is implied.', label: 'Open repository', href: source.repo }) => ({
  path, title, description, headline, lede,
  visual: { kind, title: visualTitle, caption: 'Editorial system view; source material and simulation are labeled, not presented as physical proof.', ...visualMedia[path] },
  sections, cta
});
const section = (kind, title, body, points = [], status, cta) => ({ kind, title, body, points, ...(status ? { status } : {}), ...(cta ? { cta } : {}) });

const pages = [
  page('/', 'Autopilot — autonomous-driving research', 'An open research reference for autonomous scale-model vehicles and the systems around them.', 'Build the loop. Label the evidence.', 'Autopilot follows sensor input through perception, localisation, planning, and control. It is a research platform, not a production-road autonomy claim.', 'vehicle', 'A small vehicle / a complete loop', [section('orientation', 'Research, not a promise', 'The project repository describes a BFMC-oriented scale-model vehicle, ROS nodes, learned models, and embedded hardware. Reproduction and current runtime behaviour remain to be checked.', ['Open-source reference', 'Physical evidence is separately labeled', 'No pricing or deployment offer'], 'SOURCE-BACKED / REPRODUCTION UNVERIFIED')]),
  page('/platform/', 'Platform', 'The Autopilot platform maps the autonomous-driving loop as inspectable research surfaces.', 'One loop, many boundaries.', 'Treat each handoff as a place to inspect assumptions, inputs, outputs, and evidence.', 'diagram', 'Sensor → model → planner → actuator', [section('architecture', 'Trace the handoffs', 'A platform view connects the repository’s documented sensors, ROS interfaces, perception models, localisation, and controllers without claiming they are a tested integrated release.', ['Inputs stay named', 'Outputs stay inspectable', 'Unknown runtime status stays visible']), section('boundary', 'Scope the claim', 'The reference concerns a scale-model test-track context. It does not establish general-road capability, safety certification, or commercial availability.', [], 'CONTEXT-LIMITED'), section('reading-order', 'Read it as a loop', 'Start with the physical vehicle, then inspect perception, localisation, planning, and control. Simulation and evidence are separate chapters so a diagram cannot be mistaken for a run.', ['Vehicle context', 'Signal transformations', 'Actuation boundary'], 'RECOMMENDED READING')]),
  page('/vehicle/', 'Vehicle', 'Vehicle context for the scale-model autonomy reference.', 'The vehicle is the experiment.', 'Read the physical platform as a research boundary: chassis, sensors, compute, and actuation are part of the result.', 'vehicle', 'Scale-model vehicle / source image', [section('hardware', 'A concrete test object', 'Project-owned source material depicts the scale-model vehicle and build context. The page does not assert that the pictured setup is currently operational.', ['Scale-model platform', 'Camera and inertial sensing named in README', 'Reproduction requires your own setup'], 'IMAGE SOURCE / PROJECT REFERENCE'), section('inspection', 'Inspect before interpreting', 'A vehicle image establishes context, not capability. A responsible reconstruction records the assembled parts, wiring, software revision, track conditions, and operator boundary before discussing behaviour.', ['Chassis and sensor placement', 'Compute and controller wiring', 'Track and supervision conditions'], 'REPRODUCTION CHECKLIST')]),
  page('/perception/', 'Perception', 'Perception references for camera-based autonomous-driving experiments.', 'Turn pixels into bounded signals.', 'The README names lane, traffic-sign, traffic-light, and pedestrian classification references. Their quality and current execution are not independently verified here.', 'perception', 'Frame / detections / lane signal', [section('models', 'Name the outputs', 'Perception is useful when its outputs can be inspected before they influence planning or control.', ['Lane error signal', 'Traffic-sign classification', 'Traffic-light classification', 'Pedestrian classification'], 'DOCUMENTED IN SOURCE / RUNTIME NOT CALLED'), section('limits', 'Do not overread a model', 'A model reference is not a benchmark, safety case, or claim of reliable detection in varied conditions.', [], 'NO BENCHMARK CLAIM')]),
  page('/localization/', 'Localization', 'Localization references for the Autopilot research loop.', 'Know where the map ends.', 'The project describes GPS localisation, a local map, and inertial orientation as parts of its track context.', 'map', 'Local map / coordinate frame', [section('inputs', 'Position is contextual', 'GPS, map representation, and inertial orientation are source-described ingredients. Accuracy, drift, and current fusion behaviour remain unknown.', ['GPS localisation', 'Local track map', 'BNO055 orientation reference'], 'SOURCE-BACKED / PERFORMANCE UNKNOWN')]),
  page('/planning/', 'Planning', 'Planning surfaces for a bounded autonomous-driving research loop.', 'Choose a path you can explain.', 'Planning sits between interpreted track context and the controller. This site describes the boundary, not an asserted production planner.', 'trajectory', 'Reference path / reachable route', [section('route', 'Make intent visible', 'A trajectory view should show what the system intends before actuation. The repository is the authority for implementation details.', ['Track-aware route representation', 'Planner output before control', 'Failure cases require explicit testing'], 'DESIGN SURFACE')]),
  page('/control/', 'Control', 'Control references named by the Autopilot project.', 'Convert intent into motion.', 'The README names Pure Pursuit and PID control references, with serial commands reaching embedded control hardware.', 'telemetry', 'Error → steering → motor command', [section('controllers', 'Classical control, inspectably', 'The documented control vocabulary is a useful starting point for examining steering, speed, and motor interfaces.', ['Pure Pursuit reference', 'PID reference', 'Serial command interface'], 'DOCUMENTED REFERENCE / NOT A PERFORMANCE CLAIM'), section('safety', 'Keep actuation bounded', 'A control diagram is not evidence that a vehicle is safe to operate. Physical testing needs an owned test protocol and capable supervision.', [], 'PHYSICAL VALIDATION REQUIRED')]),
  page('/simulation/', 'Simulation', 'Simulation and source material are separated from physical vehicle evidence.', 'Test the idea before the track.', 'Simulation can make assumptions cheap to inspect. It cannot be presented as a physical run or real-world benchmark.', 'simulation', 'Virtual track / synthetic telemetry', [section('separation', 'Synthetic is synthetic', 'Charts, trajectories, and overlays on this page are diagrams of an evaluation method, not results from a real episode.', ['Simulation setup must be identified', 'Synthetic traces are not physical proof', 'No result values are claimed'], 'SIMULATION / NOT PHYSICAL EVIDENCE'), section('protocol', 'Name the handoff', 'A useful simulation record captures the map, sensor model, controller configuration, scenario, seed, and failure outcome. Without that receipt, a smooth line is only an illustration.', ['Scenario and map revision', 'Inputs and assumptions', 'Outcome and failure log'], 'PROTOCOL BEFORE METRIC')]),
  page('/hardware/', 'Hardware', 'Hardware references for the scale-model autonomous-driving platform.', 'Sensors make the loop tangible.', 'The source README names Raspberry Pi and Arduino/Nucleo hardware alongside camera, IMU, sonar, and GPS references.', 'hardware', 'Wiring / compute / sensor edges', [section('stack', 'A documented hardware vocabulary', 'Hardware names here follow the public repository description; exact bill of materials, current availability, and assembled state are not asserted.', ['Raspberry Pi reference', 'Arduino/Nucleo reference', 'Camera, IMU, ultrasonic, GPS'], 'SOURCE-BACKED / CURRENT STATE UNKNOWN')]),
  page('/software/', 'Software', 'Software surfaces for the Autopilot research reference.', 'Make the graph readable.', 'ROS nodes, ONNX model references, and serial interfaces form the documented software boundary.', 'software', 'ROS graph / model edge / serial edge', [section('stack', 'Inspect the interfaces', 'The repository is the source for package versions, node names, and execution instructions. This page intentionally avoids inventing a release matrix.', ['ROS Noetic reference', 'ONNX inference reference', 'Embedded serial interface'], 'NOT EXECUTED BY THIS SITE')]),
  page('/research/', 'Research', 'Research framing and source boundaries for Autopilot.', 'Questions before conclusions.', 'Use the platform to ask what changed, what was measured, and what remains unknown.', 'notebook', 'Question / setup / observation', [section('method', 'A reproducible posture', 'A useful study records setup, source revision, sensor inputs, intervention, and limitations before interpreting a trace.', ['State the source revision', 'Separate observation from inference', 'Preserve failed runs and unknowns'], 'RESEARCH METHOD'), section('evidence', 'A result needs a receipt', 'For autonomy, evidence should identify whether a view is source material, simulation, supervised physical testing, or public-road operation. This project page only claims the first two categories.', ['Source image or repository fact', 'Simulation trace', 'Physical episode only with capture'], 'EVIDENCE TAXONOMY')]),
  page('/benchmarks/', 'Benchmarks', 'Benchmark policy for the Autopilot research platform.', 'No numbers without receipts.', 'This page contains no performance values. A benchmark belongs only with a defined protocol, captured run, and reproducible source context.', 'chart', 'Protocol / run / receipt', [section('policy', 'Evidence before leaderboard', 'The repository and reference sites do not by themselves establish a benchmark for this product page.', ['Define the track and conditions', 'Record the exact software and hardware', 'Publish raw evidence with the metric'], 'NO BENCHMARK CLAIM'), section('status', 'Current status', 'No benchmark run is claimed or reported here.', [], 'NOT CALLED')]),
  page('/docs/', 'Documentation', 'Documentation index for the Autopilot source trail.', 'Read the system at the source.', 'Use the repository README and linked upstream documentation for implementation instructions and evolving details.', 'document', 'README / notes / revision', [section('start', 'Start with the README', 'The public project README is the canonical starting point for the project-specific description.', ['Repository README', 'ROS Noetic documentation', 'Upstream references remain distinct'], 'SOURCE INDEX')]),
  page('/github/', 'GitHub', 'Public source repository for Autopilot and FSD.', 'The code is the trail.', 'Open the public repository to inspect implementation, history, issues, and the project’s own documentation.', 'code', 'Repository / source / history', [section('source', 'Project repository', 'This product page links to the public source repository and does not reproduce its code or assets.', ['kyoo-147/Autopilot_and_FSD', 'README is source-backed context', 'Inspect license and attribution at source'], 'PUBLIC REFERENCE')]),
  page('/releases/', 'Releases', 'Release status for the Autopilot research reference.', 'A source snapshot is not a release promise.', 'No Navin product release, package, support window, or availability is announced here.', 'archive', 'Revision / note / status', [section('status', 'Current status', 'The page points to the public repository rather than inventing a Navin release schedule.', ['No commercial release claimed', 'No support commitment claimed', 'Check repository history for updates'], 'NOT ANNOUNCED')]),
  page('/about/', 'About Autopilot', 'About the Autopilot autonomous-driving research platform.', 'A field notebook for autonomy.', 'Autopilot presents an independent research reference around a small vehicle and its complete sensing-to-control loop.', 'notebook', 'Field notes / bounded claims', [section('posture', 'What this is', 'A concise, source-backed map of a public project and the questions needed to reproduce it.', ['Research reference', 'Source material is attributed', 'Human review remains necessary'], 'RESEARCH REFERENCE')]),
  page('/access/', 'Access', 'Access information for the Autopilot research reference.', 'Bring your own test boundary.', 'There is no commercial pricing or hosted deployment offer on this page. Access the public source and provide your own equipment and supervision for any reproduction.', 'gate', 'Source access / physical gate', [section('availability', 'No product offer', 'Autopilot is presented as an open research reference. Hardware, track access, and physical validation are not supplied or promised.', ['Public source link', 'No price listed', 'No availability claimed'], 'OPEN SOURCE REFERENCE / REPRODUCTION UNVERIFIED')]),
  page('/privacy/', 'Privacy', 'Privacy notice for the Autopilot product page.', 'Keep the trail minimal.', 'This static product page does not request vehicle telemetry, sensor recordings, or account data. External links follow their own policies.', 'document', 'Page / link / boundary', [section('scope', 'What this page does', 'The page links to external sources and makes no claim to collect or process autonomous-driving data.', ['No telemetry collection claimed', 'External sites have separate policies', 'Review the site-wide privacy notice'], 'SITE NOTICE')]),
  page('/terms/', 'Terms', 'Terms context for the Autopilot product page.', 'Reference material, not operating advice.', 'Autopilot pages describe research context and do not authorize unsafe operation, deployment, or reliance on unverified claims.', 'document', 'Reference / responsibility / limits', [section('scope', 'Use responsibly', 'Any physical reproduction requires appropriate supervision, local compliance, and a controlled test environment.', ['No safety certification', 'No deployment authorization', 'Verify source and conditions'], 'LIMITED RESEARCH REFERENCE')]),
  page('/404.html', 'Page not found', 'The requested Autopilot page could not be found.', 'The route is off the map.', 'Return to the platform overview or inspect the public source trail.', 'map', 'Unknown coordinate / return path', [section('recovery', 'Find the route', 'Use the navigation to return to a documented surface.', ['Platform overview', 'Public repository', 'Source-backed documentation'], 'NOT FOUND')], { title: 'Return to platform', body: 'Continue from the documented system overview.', label: 'Open platform', href: '/platform/' })
];

const autopilot = {
  slug: 'autopilot', name: 'Autopilot', eyebrow: 'AUTONOMOUS SCALE-MODEL VEHICLES', status: 'OPEN RESEARCH REFERENCE', catalogStatus: 'product',
  thesis: 'A ROS and deep-learning stack for autonomous scale-model vehicles, documented as a test-track chronicle rather than a production promise.',
  intro: 'Autopilot follows the vehicle from sensor input to control output: camera, IMU, sonar, and localisation feed a ROS-based loop, while learned perception and classical control share the work.',
  proofNote: 'The public project README describes a BFMC-oriented scale-model vehicle, Raspberry Pi and Arduino/Nucleo hardware, ROS nodes, ONNX models, and an official-style test track. Reproduction hardware, model quality, and current runtime behaviour remain to be independently checked.',
  sections: [{ id: 'field-notes', kicker: '01 / FIELD NOTES', title: 'A small vehicle, a complete loop.', body: 'The reference is grounded in a physical scale-model platform. Its chronicle moves from camera frames and inertial orientation through ROS topics toward steering, speed, and motor interfaces.', points: ['Camera image input', 'BNO055 IMU orientation', 'Ultrasonic echo distance', 'GPS localisation'] }, { id: 'control-room', kicker: '02 / CONTROL ROOM', title: 'Perception meets the track.', body: 'The documented loop names lane keeping, traffic-sign, traffic-light, and pedestrian classifiers alongside Pure Pursuit and PID control. These are implementation references, not a claim of general-road autonomy.', points: ['ONNX inference at the vehicle edge', 'Lane error signals for the driving loop', 'Pure Pursuit and PID control references', 'Serial commands to an embedded controller'] }, { id: 'track-chronicle', kicker: '03 / TEST-TRACK CHRONICLE', title: 'Read the map, then read the limits.', body: 'The README records testing against the BFMC track layout with lane markings, traffic signs, and a local GPS map. The next useful chapter is open reproduction: inspect the code, rebuild the setup, and report what survives contact with the track.', points: ['BFMC 2024–2025 context', 'Local GPS map and track representation', 'Open-source academic reference', 'Physical validation still requires a capable setup'] }],
  capabilities: ['ROS sensor graph', 'Deep-learning perception', 'Camera and IMU fusion', 'Lane-keeping control', 'Embedded actuation'],
  evidence: [{ label: 'Source repository', value: 'Public README and source tree', state: 'VERIFIED' }, { label: 'Research posture', value: 'Academic / open reference', state: 'VERIFIED' }, { label: 'Physical reproduction', value: 'Hardware and track access required', state: 'UNVERIFIED' }, { label: 'Current runtime', value: 'Not executed in this product page', state: 'NOT_CALLED' }],
  media: [{ src: '/products/media/autopilot/model.jpeg', alt: 'Scale-model autonomous vehicle used by the project', caption: 'PROJECT SOURCE / SCALE-MODEL VEHICLE' }, { src: '/products/media/autopilot/track.jpeg', alt: 'BFMC-style test track documented by the project', caption: 'PROJECT SOURCE / TEST TRACK' }, { src: '/products/media/autopilot/hardware-connection.jpg', alt: 'Documented vehicle hardware connection diagram', caption: 'PROJECT SOURCE / HARDWARE CONNECTION' }, { src: '/products/media/autopilot/map.jpeg', alt: 'Local map representation documented by the project', caption: 'PROJECT SOURCE / LOCAL MAP' }, { src: '/products/media/autopilot/work.jpeg', alt: 'Project workbench and scale-model vehicle', caption: 'PROJECT SOURCE / BUILD RECORD' }],
  availability: { label: 'AVAILABILITY', title: 'Open the research trail.', body: 'There is no pricing or deployment offer here. Start with the public reference, then bring your own vehicle, sensors, and test-track protocol.', cta: 'Read the open research' },
  sourceLinks: [{ label: 'Autopilot & FSD README', url: source.readme }, { label: 'comma.ai / openpilot', url: source.openpilot }, { label: 'Applied Intuition', url: source.intuition }, { label: 'RoboRacer AI', url: source.roboracer }, { label: 'ROS Noetic documentation', url: 'https://wiki.ros.org/noetic' }, { label: 'Bosch Future Mobility Challenge', url: 'https://www.bosch.com/stories/bosch-future-mobility-challenge/' }],
  site: { primaryCta: { label: 'Open the repository', href: source.repo }, navigation: [{ label: 'Platform', children: [{ label: 'Overview', href: '/platform/' }, { label: 'Vehicle', href: '/vehicle/' }, { label: 'Perception', href: '/perception/' }, { label: 'Localisation', href: '/localization/' }, { label: 'Planning', href: '/planning/' }, { label: 'Control', href: '/control/' }] }, { label: 'Lab', children: [{ label: 'Hardware', href: '/hardware/' }, { label: 'Software', href: '/software/' }, { label: 'Simulation', href: '/simulation/' }] }, { label: 'Evidence', children: [{ label: 'Research', href: '/research/' }, { label: 'Benchmarks', href: '/benchmarks/' }, { label: 'Releases', href: '/releases/' }] }, { label: 'Docs', href: '/docs/' }, { label: 'GitHub', href: '/github/' }], footerGroups: [{ title: 'System', links: [{ label: 'Platform', href: '/platform/' }, { label: 'Vehicle', href: '/vehicle/' }, { label: 'Perception', href: '/perception/' }, { label: 'Localisation', href: '/localization/' }, { label: 'Planning', href: '/planning/' }, { label: 'Control', href: '/control/' }] }, { title: 'Lab', links: [{ label: 'Hardware', href: '/hardware/' }, { label: 'Software', href: '/software/' }, { label: 'Simulation', href: '/simulation/' }] }, { title: 'Evidence', links: [{ label: 'Benchmarks', href: '/benchmarks/' }, { label: 'Research', href: '/research/' }, { label: 'Releases', href: '/releases/' }] }, { title: 'Legal', links: [{ label: 'Privacy', href: '/privacy/' }, { label: 'Terms', href: '/terms/' }] }], pages }
};

export default autopilot;
