const visualTitles = { "document-canvas": "Page canvas / source retained", "workflow": "State rail / accountable handoff", "bounding-boxes": "Candidate fields / page regions", "validation": "Rule ledger / exception states", "discrepancy": "Two records / one open mismatch", "review-queue": "Review queue / decision required", "integration": "Approved record / export boundary", "enterprise": "Operating context / control questions", "contact": "Intake note / useful context", "security": "Boundary register / unknowns visible", "docs": "Concept index / route map", "status": "Availability register / no price", "legal": "Notice scope / canonical policy" };
const routePurposes = { "/document-processing/": "Keep the original page beside each processing state.", "/extraction/": "Treat every candidate field as a proposition tied to a region.", "/validation/": "Separate schema checks from judgment and downstream handoff.", "/reconciliation/": "Make disagreements legible before anyone resolves them.", "/review/": "Give a person the context needed to approve, correct, or return work.", "/integrations/": "Export only records whose review state is explicit.", "/use-cases/": "Choose a workflow by the decision the document must support.", "/use-cases/invoices/": "Keep amount, supplier, and source region in one review path.", "/use-cases/purchase-orders/": "Compare commitments without detaching them from the page.", "/pricing/": "State availability without inventing a commercial plan." };
const pageSpecs = [
  ["/", "Document intelligence for accountable work", "A review workstation for turning difficult documents into evidence-linked records.", "See the page. Defend the record.", "Dossier keeps source pages, extracted fields, confidence, and reviewer decisions in one inspectable path.", "document-canvas", ["Illustrative page view", "Evidence-linked fields", "Human review boundary"], "A document is more than its output", "Extraction is proposed structure, not a final truth. The planned workstation keeps the original page close to every decision."],
  ["/product/", "The Dossier workstation", "A concept-stage product direction for document processing with a visible chain of evidence.", "A desk for the uncertain middle.", "Dossier is designed around the point where machine output needs context, validation, and a person who can approve it.", "workflow", ["Ingest", "Extract", "Validate", "Review", "Handoff"], "One surface, several accountable steps", "The interface is intended to make state changes legible rather than burying them behind a chat transcript."],
  ["/document-processing/", "Document processing", "Prepare pages for inspection without losing their source context.", "Start with the page in view.", "Document processing is the planned foundation for pages, batches, and structured observations.", "document-canvas", ["Page and batch context", "Layout-aware preparation", "Source retained"], "Processing should leave a trail", "Each later field should be able to point back to the page region and processing state that produced it."],
  ["/extraction/", "Extraction", "Turn page regions into candidate fields, tables, and line items.", "Propose structure. Keep the evidence.", "Dossier treats extracted values as reviewable proposals with confidence and provenance attached.", "bounding-boxes", ["Fields", "Tables", "Line items"], "A value without context is incomplete", "The planned extraction view pairs a candidate value with its source region, status, and the next action it needs."],
  ["/validation/", "Validation", "Check extracted records against schemas, rules, and source evidence.", "Make uncertainty a visible state.", "Validation is a separate step so malformed or unsupported values do not silently become downstream facts.", "validation", ["Schema checks", "Rule outcomes", "Retry or escalate"], "A failed check is useful information", "Dossier is designed to distinguish a clean pass, a recoverable retry, and a question for a human reviewer."],
  ["/reconciliation/", "Reconciliation", "Compare related documents and surface discrepancies for resolution.", "Put the mismatch on the table.", "Planned reconciliation views help teams compare records such as invoices and purchase orders without hiding the disagreement.", "discrepancy", ["Side-by-side evidence", "Discrepancy states", "Resolution notes"], "Agreement is an outcome, not an assumption", "A discrepancy remains open until a rule or a person provides a defensible resolution."],
  ["/review/", "Human review", "Give reviewers the context and controls to approve, correct, or return a proposed record.", "Review is part of the system.", "The planned review queue makes confidence, evidence, and decision status visible before any handoff.", "review-queue", ["Approve", "Correct", "Return for retry"], "The reviewer has the final say", "Dossier does not present illustrative confidence or status as production performance. They are interface states for an accountable workflow."],
  ["/workflows/", "Workflows", "Shape repeatable document paths around explicit states and ownership.", "From intake to approved handoff.", "Build a workflow that names what happens next, who can decide, and what evidence travels with the record.", "workflow", ["State transitions", "Human gates", "Export boundary"], "A workflow is a contract", "The intended model keeps each transition inspectable so teams can adapt the process without losing responsibility."],
  ["/integrations/", "Integrations", "Connect approved records to the systems that receive them.", "Export what the desk can defend.", "Integration work is planned around explicit contracts, not inferred fields or unreviewed automation.", "integration", ["Structured output", "Webhook-ready boundary", "Contract-first mapping"], "Downstream systems need a clear promise", "The destination should know which fields were approved, which remain unresolved, and where their evidence lives."],
  ["/use-cases/", "Use cases", "Explore document workflows by the decisions they need to support.", "Different documents. Same discipline.", "Dossier is intended for teams that need to inspect, reconcile, and approve operational documents.", "workflow", ["Invoices", "Purchase orders", "Custom document sets"], "Start from the decision", "The right workflow depends on the document, the rule, and the person accountable for the outcome."],
  ["/use-cases/invoices/", "Invoice review", "A source-linked path for extracting and reviewing invoice fields.", "Keep every amount near its source.", "The planned invoice flow separates extraction from validation and leaves exceptions visible for review.", "bounding-boxes", ["Supplier and dates", "Totals and line items", "Exception queue"], "Illustrative invoice workspace", "This page describes interface intent only; it does not claim accuracy, processing volume, or customer results."],
  ["/use-cases/purchase-orders/", "Purchase-order review", "Compare purchase-order structure with the evidence on the page.", "Make commitments inspectable.", "A purchase-order workflow can preserve line-item context while preparing a record for downstream reconciliation.", "reconciliation", ["Order identifiers", "Line-item context", "Approval status"], "A record with its original page", "The useful unit is not a detached field. It is a field, its evidence, and the decision that accepted it."],
  ["/security/", "Security and boundaries", "A transparent starting point for discussing document handling and control surfaces.", "Trust starts with clear limits.", "Dossier is a concept-stage direction. Deployment, retention, access controls, and security attestations are not represented as shipped capabilities here.", "security", ["Explicit evidence states", "Human approval boundary", "No certification claim"], "What is known, and what is not", "Security posture must be documented against a real deployment. This page intentionally avoids unsupported compliance or availability claims."],
  ["/developers/", "Developers", "Design integration boundaries around explicit, reviewable records.", "Build on a visible contract.", "Developer-facing surfaces are intended to expose schemas, evidence references, and unresolved states clearly.", "integration", ["Schema-shaped records", "Evidence references", "Failure states"], "An API should not erase the review trail", "The planned developer experience makes it possible to handle approved, rejected, and incomplete records deliberately."],
  ["/docs/", "Documentation", "A concise map of the planned Dossier concepts and vocabulary.", "Understand the states before the tools.", "Documentation will describe the processing, extraction, validation, reconciliation, and review boundaries without overstating maturity.", "docs", ["Concepts", "Workflow states", "Integration notes"], "Documentation follows the evidence", "As the product develops, examples should remain clearly marked as illustrative or live."],
  ["/pricing/", "Pricing", "A transparent placeholder for a product that has not published commercial terms.", "No price has been published.", "Dossier is not presented as a generally available service, so no price, plan, quota, or billing commitment is claimed.", "status", ["Commercial terms: unpublished", "Availability: concept stage", "Contact for context"], "Ask; do not assume", "Any future pricing page should be sourced from an approved commercial decision rather than a placeholder number."],
  ["/enterprise/", "Enterprise", "Discuss governance and workflow requirements without promising unsupported readiness.", "Start with the operating reality.", "Enterprise conversations should begin with documents, decisions, ownership, and deployment constraints—not a fictional customer list.", "enterprise", ["Workflow discovery", "Governance questions", "Deployment scope"], "A conversation, not a claim", "Dossier has no published enterprise customer, SLA, procurement, or certification claim on this site."],
  ["/contact/", "Contact Dossier", "Share the documents, decisions, and constraints that matter to your workflow.", "Tell us what needs defending.", "Contact is the appropriate next step for early-access interest, workflow context, or questions about the concept.", "contact", ["Workflow context", "Document types", "Review requirements"], "A useful first conversation", "No outcome, response time, or availability is promised by this contact path."],
  ["/privacy/", "Privacy", "How this concept-stage page treats information and makes no hidden data promises.", "Privacy requires a real policy.", "This product page is a concept description. It does not claim a production data-processing arrangement or substitute for a reviewed privacy notice.", "legal", ["No fabricated retention terms", "No fabricated subprocessors", "Policy review required"], "Read the actual notice", "Use the site's canonical privacy policy for current site practices; product-specific processing terms require separate documentation."],
  ["/terms/", "Terms", "The canonical terms boundary for this product page.", "Terms should match the service.", "Dossier is described as a concept-stage direction, not a completed service contract or warranty of capability.", "legal", ["No service promise", "No performance warranty", "Scope remains explicit"], "Do not infer a contract from a concept", "Any future offering should publish reviewed terms that match the actual product and deployment."],
  ["/404.html", "Page not found", "The requested Dossier page could not be found.", "This page is not in the dossier.", "Return to the product desk or choose a documented workflow.", "status", ["Check the URL", "Return to Dossier"], "A quiet dead end", "Only documented routes are part of this concept-stage map."]
];

const routeSections = {
  "/document-processing/": { kind: "intake", title: "Preserve the intake state.", body: "A page can be rotated, split, incomplete, or difficult to read. Those conditions belong to the record before extraction begins.", points: ["Batch identity", "Page order", "Processing state"], status: "SOURCE RETAINED" },
  "/extraction/": { kind: "candidates", title: "Every field remains a candidate.", body: "A proposed value should carry its region, type, confidence state, and an explicit route to correction or review.", points: ["Region anchor", "Field type", "Correction path"], status: "PROPOSAL / NOT FACT" },
  "/validation/": { kind: "exceptions", title: "Exceptions deserve a queue.", body: "Rules can identify malformed values, but they cannot silently decide whether an unusual document is correct. Escalation keeps that distinction visible.", points: ["Rule failure", "Evidence check", "Human escalation"], status: "FAIL CLOSED" },
  "/reconciliation/": { kind: "resolution", title: "Resolve with a reason.", body: "When records disagree, the resolution should preserve both source values, the rule or person that decided, and the remaining uncertainty.", points: ["Source A", "Source B", "Resolution note"], status: "OPEN UNTIL EXPLAINED" },
  "/review/": { kind: "decision", title: "A decision needs context.", body: "Approval is meaningful only when the reviewer can inspect the page, proposed values, checks, exceptions, and downstream consequence together.", points: ["Inspect", "Correct", "Approve or return"], status: "HUMAN DECISION" },
  "/workflows/": { kind: "ownership", title: "Name the owner at each state.", body: "A workflow is safer when every transition has an accountable role, a condition, and a durable record of what happened.", points: ["Owner", "Condition", "Receipt"], status: "OWNERSHIP REQUIRED" },
  "/integrations/": { kind: "export", title: "Export only an understood record.", body: "An integration boundary should carry schema version, review state, unresolved fields, and evidence references instead of flattening uncertainty.", points: ["Schema version", "Review state", "Evidence reference"], status: "CONTRACT / NOT LIVE" },
  "/use-cases/": { kind: "decision-map", title: "The document serves a decision.", body: "Different teams need different evidence: payment, commitment, exception handling, or an audit trail. Start with that decision rather than a generic extraction promise.", points: ["Decision", "Required evidence", "Accountable reviewer"], status: "WORKFLOW DIRECTION" },
  "/use-cases/invoices/": { kind: "invoice-check", title: "Totals need their line-item trail.", body: "Invoice review keeps supplier identity, dates, taxes, totals, and line items close to the page region that supports each proposition.", points: ["Supplier", "Totals", "Line-item evidence"], status: "ILLUSTRATIVE PATH" },
  "/use-cases/purchase-orders/": { kind: "commitment-check", title: "Commitments need comparison context.", body: "Purchase-order review preserves identifiers, requested quantities, prices, and approval history before a comparison is treated as resolved.", points: ["Order identity", "Quantity and price", "Approval history"], status: "ILLUSTRATIVE PATH" },
  "/developers/": { kind: "schema", title: "Schemas should carry their provenance.", body: "A future integration can be useful without hiding incomplete records: consumers need version, evidence pointers, state, and failure semantics.", points: ["Versioned schema", "Evidence pointer", "Failure semantics"], status: "API DIRECTION / NOT PUBLISHED" },
  "/security/": { kind: "control", title: "Controls depend on deployment reality.", body: "Access, retention, deletion, isolation, and audit controls must be documented against a real system. This page names questions rather than claiming answers.", points: ["Access boundary", "Retention decision", "Audit evidence"], status: "CONTROL QUESTIONS" },
  "/pricing/": { kind: "access", title: "Availability is not implied.", body: "There is no published plan, quota, price, trial, or service commitment. A contact route records interest only.", points: ["No plan", "No price", "No service promise"], status: "NOT ANNOUNCED" },
  "/enterprise/": { kind: "discovery", title: "Start with operating constraints.", body: "An enterprise conversation would need to establish document types, ownership, deployment boundary, review policy, and procurement requirements before any capability discussion.", points: ["Document scope", "Governance", "Deployment questions"], status: "DISCOVERY ONLY" },
  "/contact/": { kind: "intake-note", title: "A useful note has a boundary.", body: "Describe the document workflow and the decision it supports, but do not send sensitive documents or personal information through an unapproved channel.", points: ["Workflow", "Decision", "Safe context"], status: "NON-BINDING" },
  "/privacy/": { kind: "policy", title: "Policy follows the actual system.", body: "Product-specific collection, retention, subprocessors, and deletion terms are not published because no released Dossier service is represented here.", points: ["Collection", "Retention", "Deletion"], status: "POLICY PENDING" },
  "/terms/": { kind: "scope", title: "Terms follow an actual offering.", body: "A concept page does not grant access, warranty, support, or commercial rights. Any future service needs reviewed terms matched to its real scope.", points: ["Access", "Responsibility", "Scope"], status: "NO CONTRACT" },
  "/": { kind: "orientation", title: "Keep source, proposal, and decision together.", body: "The desk is useful only when a reviewer can move from original page to proposed structure to approved handoff without losing context.", points: ["Original page", "Proposed record", "Human decision"], status: "DESIGN DIRECTION" },
  "/product/": { kind: "orientation", title: "The desk is a chain, not a widget.", body: "Processing, extraction, validation, reconciliation, and review are separate instruments in one accountable workstation.", points: ["Page context", "State changes", "Handoff"], status: "CONCEPT MAP" },
  "/docs/": { kind: "documentation", title: "Document states before API syntax.", body: "Future docs should explain source identity, candidate values, validation outcomes, review decisions, and integration boundaries with examples marked honestly.", points: ["Vocabulary", "State model", "Evidence rules"], status: "DOCS / NOT PUBLISHED" },
  "/404.html": { kind: "unknown", title: "Unknown route, no assumption.", body: "A missing path is not evidence of an available feature or processing endpoint. Return to the documented desk.", points: ["Check URL", "Return to desk"], status: "ROUTE UNKNOWN" },
};

const pages = pageSpecs.map(([path, title, description, headline, lede, kind, items, sectionTitle, body]) => ({
  path, title, description, eyebrow: "DOSSIER / DOCUMENT INTELLIGENCE", headline, lede,
  visual: { kind, title: visualTitles[kind] || "Illustrative interface state", items, caption: "Illustrative only — not a live processing result." },
  sections: [{ kind, title: sectionTitle, body, points: items, status: "CONCEPT / SOURCE-BOUND" }, { kind: "evidence", title: routePurposes[path] || `What this ${path === "/" ? "desk" : "route"} is for`, body: `${body} The page stays deliberately separate from a live processing result: this is a product direction and interface contract, not a performance claim.`, points: ["Source context stays adjacent", "Uncertainty remains addressable", "A reviewer can stop the handoff"] }, routeSections[path]],
  cta: { title: "Continue with context", body: "Bring the workflow and its evidence requirements into the next conversation.", label: "Contact Dossier", href: "/contact/" }
}));

const dossier = {
  slug: "dossier", name: "Dossier", eyebrow: "Agentic Document Intelligence", status: "Early-access interest", catalogStatus: "product",
  thesis: "A local-first document desk for turning difficult pages into reviewable, approved, integration-ready structured data.",
  intro: "Dossier is a concept-stage direction for document work where extraction is only the beginning. Each proposed record stays connected to the page, the decision, and the person who approved it.",
  proofNote: "Concept stage: the workflow and capability areas are planned, not a claim of shipped OCR accuracy, automation coverage, or production readiness.",
  sections: [{ id: "desk", kicker: "01 / Forensic document desk", title: "Read the page before it becomes a row.", body: "A document is treated as an inspectable artefact. The planned desk keeps page context visible while an agent proposes observations, fields, and questions for human review.", points: ["Page-aware inspection", "Evidence attached to proposals", "Human approval before handoff"] }],
  capabilities: ["OCR", "Handwriting", "Layout and tables", "Forms and extraction", "QA and evidence"],
  evidence: [{ label: "Product posture", value: "Local-first concept", state: "PLANNED" }, { label: "Review boundary", value: "Human approval required", state: "INTENT" }, { label: "Output posture", value: "Integration-ready structure", state: "TARGET" }, { label: "Current access", value: "Early-access interest", state: "OPEN" }],
  availability: { label: "Availability", title: "A desk being drawn in public.", body: "Dossier is not presented as a launched product. Share an early-access signal to help shape the review workflow and the documents it should respect.", cta: "Register interest" },
  sourceLinks: [{ label: "W3C Web Annotation Data Model", url: "https://www.w3.org/TR/annotation-model/" }, { label: "JSON Schema specification", url: "https://json-schema.org/specification" }, { label: "NIST AI Risk Management Framework", url: "https://www.nist.gov/itl/ai-risk-management-framework" }],
  site: {
    primaryCta: { label: "Contact Dossier", href: "/contact/" },
    navigation: [{ label: "The desk", href: "/product/" }, { label: "Processing", children: [{ label: "Document processing", href: "/document-processing/" }, { label: "Extraction", href: "/extraction/" }, { label: "Validation", href: "/validation/" }] }, { label: "Review", children: [{ label: "Reconciliation", href: "/reconciliation/" }, { label: "Human review", href: "/review/" }, { label: "Workflows", href: "/workflows/" }] }, { label: "Build", children: [{ label: "Integrations", href: "/integrations/" }, { label: "Developers", href: "/developers/" }, { label: "Docs", href: "/docs/" }] }, { label: "Contact", href: "/contact/" }],
    footerGroups: [{ title: "The desk", links: [{ label: "Document processing", href: "/document-processing/" }, { label: "Extraction", href: "/extraction/" }, { label: "Human review", href: "/review/" }] }, { title: "Decisions", links: [{ label: "Reconciliation", href: "/reconciliation/" }, { label: "Use cases", href: "/use-cases/" }, { label: "Workflows", href: "/workflows/" }] }, { title: "Build", links: [{ label: "Integrations", href: "/integrations/" }, { label: "Developers", href: "/developers/" }, { label: "Docs", href: "/docs/" }] }, { title: "Boundaries", links: [{ label: "Security", href: "/security/" }, { label: "Availability", href: "/pricing/" }, { label: "Contact", href: "/contact/" }] }],
    pages
  }
};

export default dossier;
