const sources = {
  arkit: 'https://developer.apple.com/documentation/arkit/scene_understanding',
  nist: 'https://www.nist.gov/itl/iad/mig/voice-biometric-evaluations',
  sqlite: 'https://www.sqlite.org/docs.html',
  microduck: 'https://pollen-robotics.com/microduck',
  moflin: 'https://www.casio.com/us/moflin/',
  limx: 'https://limxdynamics.com/en',
  figure: 'https://www.figure.ai/figure',
  menlo: 'https://menlo.ai/'
};

const section = (kind, title, body, points, status = 'CONCEPT STAGE') => ({ kind, title, body, points, status });
const page = (path, title, description, eyebrow, headline, lede, visual, sections, cta) => ({ path, title, description, eyebrow, headline, lede, visual, sections, ...(cta ? { cta } : {}) });
const contact = { title: 'Keep the notebook open', body: 'Follow future field notes as the direction becomes more concrete.', label: 'Follow field notes', href: '/availability/' };

const lajvard = {
  slug: 'lajvard', name: 'Lajvard', eyebrow: 'WARM COMPANION FIELD NOTES / BLUEPRINT 01', status: 'CONCEPT STAGE · UPDATES, NOT PREORDER', catalogStatus: 'research',
  thesis: 'A compact robot companion imagined for the small rituals of a room: noticing where it is, remembering what matters, and answering with warmth without pretending to be human.',
  intro: 'Lajvard is a product direction, not a shipping promise. This notebook describes questions around a portable robot with spatial awareness, a private journal, and a gentle social presence.',
  proofNote: 'The capabilities below are intentions and design hypotheses. No Lajvard hardware, firmware, availability, performance, or offline/online behavior is being claimed.',
  sections: [
    { id: 'room-notes', kicker: '01 / ROOM NOTES', title: 'A map that stays close to the moment', body: 'The imagined robot would build a modest spatial memory of its surroundings, then use that context to make movement and conversation feel less random.', points: ['LiDAR mapping is an intended sensing direction, not a demonstrated feature.', 'Spatial memory should be inspectable, editable, and easy to clear.'] },
    { id: 'private-thread', kicker: '02 / PRIVATE THREAD', title: 'A journal, not a hidden dossier', body: 'Lajvard explores a local-first journal of moments an owner chooses to keep. Voice recognition and an offline-online split remain consent and failure-mode questions.', points: ['Journal entries should carry provenance and deletion controls.', 'Network access should be visible rather than assumed.'] },
    { id: 'portable-character', kicker: '03 / PORTABLE CHARACTER', title: 'Personality with an honest boundary', body: 'The character is meant to be warm and compact without making emotional guarantees. Physical form, power, and updates remain open questions.', points: ['Personality is a creative direction, not evidence of sentience.', 'Concepts, prototypes, and demonstrations must stay separately labelled.'] }
  ],
  capabilities: ['Compact humanoid form direction', 'Spatial memory direction', 'Owner-controlled journal direction', 'Local-first interaction direction', 'Visible uncertainty and consent'],
  evidence: [
    { label: 'Hardware', value: 'Not built or demonstrated', state: 'CONCEPT' },
    { label: 'Firmware', value: 'Architecture under exploration', state: 'UNVERIFIED' },
    { label: 'Privacy', value: 'Consent and deletion are requirements', state: 'INTENDED' },
    { label: 'Availability', value: 'No release or preorder', state: 'UPDATES ONLY' }
  ],
  availability: { label: 'FIELD NOTEBOOK', title: 'Follow the questions, not a checkout button.', body: 'There is no preorder, delivery date, or availability claim attached to this page.', cta: 'Read future updates' },
  sourceLinks: [
    { label: 'Apple ARKit scene understanding', url: sources.arkit }, { label: 'NIST voice biometric evaluations', url: sources.nist }, { label: 'SQLite documentation', url: sources.sqlite },
    { label: 'Pollen Robotics MicroDuck', url: sources.microduck }, { label: 'Casio Moflin', url: sources.moflin }, { label: 'LimX Dynamics', url: sources.limx },
    { label: 'Figure', url: sources.figure }, { label: 'Menlo AI', url: sources.menlo }
  ],
  site: {
    primaryCta: { label: 'Follow the field notes', href: '/availability/' },
    navigation: [
      { label: 'Life with Lajvard', href: '/life-with-lajvard/' },
      { label: 'The robot', href: '/robot/', children: [{ label: 'Movement', href: '/movement/' }, { label: 'Spatial memory', href: '/spatial-memory/' }, { label: 'Hardware', href: '/hardware/' }] },
      { label: 'Intelligence', href: '/intelligence/' }, { label: 'Research', href: '/research/' }, { label: 'Access', href: '/availability/' }
    ],
    footerGroups: [
      { title: 'Explore', links: [{ label: 'Gallery', href: '/gallery/' }, { label: 'Specs', href: '/specs/' }, { label: 'Developer', href: '/developer/' }] },
      { title: 'Read', links: [{ label: 'Research', href: '/research/' }, { label: 'Support', href: '/support/' }, { label: 'About', href: '/about/' }] },
      { title: 'Legal', links: [{ label: 'Privacy', href: '/privacy/' }, { label: 'Terms', href: '/terms/' }, { label: 'Contact', href: '/contact/' }] }
    ],
    pages: [
      page('/', 'Lajvard — a daily robot companion', 'A concept-stage field notebook for a warm, compact robot companion.', 'FIELD NOTE 01 / A DAY IN THE ROOM', 'Life with a little presence.', 'Lajvard begins with the room: a quiet hello, a small ritual, a companion that knows the limits of what it knows. This is a concept, not a shipping announcement.', { kind: 'daybook', title: 'A daybook, not a dashboard', items: ['morning', 'notice', 'remember', 'rest'], caption: 'Original concept storyboard — not a product demo.' }, [section('promise', 'Start with the morning, not the feature list.', 'A companion earns trust through small, legible moments: a greeting you can dismiss, a memory you can edit, and a pause you understand.', ['Ordinary rituals before spectacle', 'Visible boundaries around memory and listening', 'No claim of sentience or emotional understanding']), section('evidence', 'What is real today?', 'Lajvard has no demonstrated hardware or released software. These pages are a transparent design and research direction.', ['Concept only', 'No price or availability announced', 'References are context, not Lajvard proof'], 'UNVERIFIED')], contact),
      page('/robot/', 'The robot', 'The proposed form, behavior, and boundaries of Lajvard.', 'THE ROBOT / FORM STUDY', 'A small body for a real room.', 'The form is intentionally open: compact, approachable, and capable of being present without taking over the room.', { kind: 'silhouette', title: 'Form study 01', items: ['proportion', 'posture', 'pause'], caption: 'Original concept study — no production design claim.' }, [section('form', 'Character before specification.', 'Lajvard explores a humanoid silhouette because face, posture, and gesture can make a machine legible. That is a design hypothesis, not a capability claim.', ['Compact humanoid direction', 'Warm character, not childish branding', 'Physical dimensions and materials are not final']), section('boundary', 'A body is a set of compromises.', 'The body must eventually account for power, repair, sound, safe movement, and ownership. No component choice has been announced.', ['No prototype shown', 'No certification claimed', 'No physical specification published'], 'UNKNOWN')]),
      page('/movement/', 'Movement', 'Movement research for a small companion robot.', 'THE ROBOT / MOVEMENT NOTES', 'Movement should earn its place.', 'A robot in a home needs safe pauses, clear intent, and an honest answer when the route is unknown.', { kind: 'motion-line', title: 'Pause is a behavior', items: ['approach', 'pause', 'ask'], caption: 'Storyboard, not a movement test.' }, [section('research', 'A question, not a benchmark.', 'Public robotics work demonstrates many approaches to mobility, but none of it is evidence that Lajvard moves. We are studying how movement can feel calm and predictable.', ['Navigation is not demonstrated', 'No speed, range, or autonomy claim', 'Pause and ask when uncertain'], 'NOT DEMONSTRATED'), section('safety', 'The quiet behavior matters most.', 'Any future movement system needs an explicit stop state and a way for a person to understand what the robot intends to do.', ['Stop must be visible', 'Uncertainty must interrupt action', 'Physical behavior requires physical evidence'], 'RESEARCH QUESTION')]),
      page('/spatial-memory/', 'Spatial memory', 'How Lajvard might remember a room with consent.', 'THE ROBOT / ROOM MEMORY', 'Remember less. Remember clearly.', 'Spatial memory should be a readable relationship with a place, not an invisible dossier.', { kind: 'map', title: 'Room memory study', items: ['seen', 'placed', 'forgotten'], caption: 'Inspired by public scene-understanding documentation; not a Lajvard feature.' }, [section('privacy', 'A map with an eraser.', 'Scene understanding is an established research area; Lajvard has no mapping implementation. Any future map would need inspection, correction, expiry, and deletion.', ['Show what was remembered', 'Let the owner correct it', 'Clear it without a support ticket'], 'INTENDED'), section('provenance', 'Memory needs a source and an expiry.', 'A remembered object should explain when and how it entered the journal, and when it will be forgotten. This is a design requirement, not a storage claim.', ['Provenance before convenience', 'Owner-controlled retention', 'No hidden household profile'], 'DESIGN REQUIREMENT')]),
      page('/hardware/', 'Hardware', 'The open hardware questions behind Lajvard.', 'THE ROBOT / HARDWARE NOTEBOOK', 'A body is a set of compromises.', 'Sensors, compute, power, sound, repair, and materials all shape how a companion belongs in a room.', { kind: 'parts', title: 'Open hardware notebook', items: ['sensing', 'compute', 'power', 'shell'], caption: 'Question map — no specification sheet.' }, [section('inventory', 'No specification sheet yet.', 'We are not publishing invented dimensions, battery life, sensors, materials, or certifications. The hardware program is not announced.', ['No prototype shown', 'No certification claimed', 'Repair and ownership remain open questions'], 'UNKNOWN'), section('tradeoffs', 'A future body must be accountable.', 'Hardware choices should be explained through serviceability, privacy, and safe failure—not only appearance.', ['Power is a constraint', 'Sensors require consent', 'Repair is part of ownership'], 'RESEARCH QUESTION')]),
      page('/software/', 'Software', 'A proposed software surface for Lajvard.', 'INTELLIGENCE / SOFTWARE STATES', 'Software should explain itself.', 'The software direction favors visible state: listening, thinking, remembering, offline, unavailable, and waiting for permission.', { kind: 'status', title: 'Listening / local / waiting', items: ['LISTENING', 'LOCAL', 'WAITING'], caption: 'Concept state vocabulary — no released software.' }, [section('system', 'State before spectacle.', 'A future companion needs understandable controls for journals, network access, updates, and recovery. No Lajvard software is currently released.', ['Clear listening indicator', 'Export and delete journal data', 'Fail closed when identity is uncertain'], 'UNBUILT'), section('recovery', 'The safest answer can be no.', 'When identity, network, or perception is uncertain, the software should stop and explain the boundary rather than improvise confidence.', ['Offline is explicit', 'Permission is revocable', 'Recovery is observable'], 'DESIGN REQUIREMENT')]),
      page('/intelligence/', 'Intelligence', 'A truthful outline of proposed intelligence boundaries.', 'INTELLIGENCE / BOUNDARIES', 'Helpful does not mean all-knowing.', 'Lajvard may combine perception, memory, and language someday. The system must show uncertainty instead of performing confidence.', { kind: 'layers', title: 'Perception / memory / response', items: ['observe', 'retain with consent', 'respond'], caption: 'Architecture hypothesis — not an implemented system.' }, [section('architecture', 'Three modest layers.', 'We are exploring a perception layer, a local journal, and an interaction layer. Their interfaces and models remain research questions.', ['Perception can be wrong', 'Memory is owner-controlled', 'Responses are not evidence of understanding'], 'RESEARCH DIRECTION'), section('character', 'Warmth without a claim of feeling.', 'A consistent voice can make an interface legible; it cannot establish sentience, emotion, or a human relationship.', ['Personality is authored behavior', 'No sentience claim', 'Uncertainty stays visible'], 'BOUNDARY')]),
      page('/developer/', 'Developer', 'A possible developer surface, without a fabricated SDK.', 'DEVELOPER / FUTURE SURFACE', 'Nothing to install yet.', 'There is no Lajvard SDK, API, package, or developer preview to download. This page records the boundary clearly.', { kind: 'terminal', title: 'Developer access', items: ['permissions', 'journal', 'events'], caption: 'No commands or credentials are being offered.' }, [section('boundary', 'Future interfaces should be narrow.', 'If a developer surface exists, it should document permissions, data ownership, versioning, and failure states before convenience APIs.', ['No SDK announced', 'No API key or sandbox available', 'Contact us with focused research questions'], 'NOT AVAILABLE'), section('contract', 'An interface should expose the stop state.', 'A future integration must distinguish observed, proposed, approved, and unavailable states instead of flattening them into a response.', ['Permission contract', 'Versioned events', 'Explicit failure states'], 'DESIGN DIRECTION')]),
      page('/research/', 'Research', 'Public references and open questions guiding Lajvard research.', 'RESEARCH / READING SHELF', 'Borrow methods, not certainty.', 'Lajvard is informed by public documentation and products; those references are context, not proof of Lajvard capability.', { kind: 'references', title: 'Methods under review', items: ['map', 'voice', 'store', 'move'], caption: 'Primary references are listed below.' }, [section('reading', 'Different references, different questions.', 'ARKit informs scene context; NIST informs voice-identity evaluation; SQLite informs local data primitives; Pollen, Moflin, LimX, Figure, and Menlo illuminate embodiment and robotics product structure.', ['Mapping and scene context', 'Voice identity evaluation', 'Local data primitives', 'Robotic form and movement'], 'SOURCE-BACKED CONTEXT'), section('boundary', 'Reference behavior is not Lajvard evidence.', 'Public products demonstrate their own systems under their own conditions. Their pages help us ask better questions; they do not validate this concept.', ['No affiliation implied', 'No capability transfer implied', 'Source links remain inspectable'], 'EXPLICIT LIMIT')]),
      page('/life-with-lajvard/', 'Life with Lajvard', 'The daily rituals Lajvard is being designed to support.', 'LIFE WITH LAJVARD / SCENARIO', 'Start with the morning, not the dashboard.', 'A companion earns trust through small, legible moments: a greeting you can dismiss, a memory you can edit, a pause you understand.', { kind: 'daybook', title: 'A daybook in four gestures', items: ['wake', 'notice', 'remember', 'rest'], caption: 'Concept storyboard, not a claimed user experience.' }, [section('ritual', 'A day in four gestures.', 'Wake, notice, remember, rest. These are story beats for design exploration, not a claimed user experience.', ['Say hello without demanding attention', 'Notice a change without inventing a reason', 'Rest when the owner asks'], 'SCENARIO'), section('consent', 'Presence should remain dismissible.', 'The person in the room should be able to pause listening, clear a memory, or ask what the robot knows.', ['Dismiss the interaction', 'Inspect the memory', 'Choose when to continue'], 'DESIGN REQUIREMENT')]),
      page('/gallery/', 'Gallery', 'A quiet index of Lajvard concept studies.', 'ARCHIVE / MEDIA STATUS', 'The archive is intentionally small.', 'There are no finished product photographs to present. This gallery is reserved for clearly labelled sketches, diagrams, and future verified media.', { kind: 'gallery', title: 'Archive states', items: ['CONCEPT', 'PROTOTYPE', 'DEMONSTRATION', 'RELEASED'], caption: 'No product photography or prototype claim.' }, [section('archive', 'Label the artifact before showing it.', 'Concept art, renders, prototypes, and captured product behavior must remain separate categories. Nothing here should be mistaken for a shipping unit.', ['Concept', 'Prototype', 'Demonstration', 'Released'], 'AWAITING MATERIAL'), section('media', 'No borrowed product imagery.', 'Reference products are linked as research context, not reused as Lajvard media. Original project-owned visual material will be added only when available.', ['No fake render', 'No reference image presented as Lajvard', 'Provenance on every future asset'], 'MEDIA POLICY')]),
      page('/specs/', 'Specs', 'Current known and unknown Lajvard specifications.', 'REFERENCE / HONEST SPECIFICATION', 'The honest specification sheet.', 'A blank field is more useful than a made-up number. The following are not announced.', { kind: 'spec-ledger', title: 'Known / unknown', items: ['direction', 'question', 'evidence'], caption: 'Unknown values are intentionally not filled.' }, [section('table', 'Not yet specified.', 'Dimensions, mass, battery, compute, sensors, connectivity, materials, ingress rating, and certifications are all unknown.', ['Dimensions — UNKNOWN', 'Battery — UNKNOWN', 'Sensors — INTENDED DIRECTION', 'Certifications — NOT CLAIMED'], 'UNKNOWN'), section('method', 'Publish only what can be checked.', 'A future specification sheet should name the revision, measurement method, and evidence source for every number.', ['Revision attached', 'Method stated', 'Evidence linked'], 'FUTURE STANDARD')]),
      page('/availability/', 'Availability', 'Availability status for the Lajvard concept.', 'ACCESS / STATUS', 'No preorder. No delivery date.', 'Lajvard is not available to buy, reserve, or test. This page will change only when a verifiable status changes.', { kind: 'stamp', title: 'UPDATES ONLY', items: ['no preorder', 'no pilot', 'no shipping'], caption: 'Concept-stage status.' }, [section('status', 'Updates only.', 'There is no announced launch, waitlist, region, pilot, or distribution plan. You can follow the research without mistaking interest for an order.', ['No release announced', 'No pilot announced', 'No shipping claim'], 'NOT AVAILABLE'), section('future', 'A future access page must earn its button.', 'Availability will be published only with a real product decision, scope, terms, and evidence that matches the wording.', ['No deposit', 'No implied queue', 'No delivery promise'], 'POLICY')], contact),
      page('/support/', 'Support', 'Support boundary for a concept-stage project.', 'ACCESS / SUPPORT BOUNDARY', 'No support desk yet.', 'Because Lajvard is not released, there is no technical support channel, repair program, warranty, or service-level promise.', { kind: 'mail', title: 'A human inbox', items: ['research question', 'source correction', 'future note'], caption: 'For questions, not troubleshooting a released robot.' }, [section('help', 'Questions are welcome.', 'For research questions or corrections to a source-backed claim, contact the team. We will not imply support for hardware that does not exist.', ['No warranty announced', 'No repair policy announced', 'Research questions welcome'], 'CONCEPT STAGE'), section('care', 'Support follows a real object.', 'A repair, safety, or service program can only be documented once there is a product and an accountable operating model.', ['No service-level promise', 'No support entitlement', 'Future policy requires review'], 'NOT AVAILABLE')]),
      page('/about/', 'About Lajvard', 'Why this robot research exists.', 'ABOUT / NAVIN RESEARCH', 'A companion project, kept accountable.', 'Lajvard is a Navin Research product direction exploring how robotics can enter daily life with warmth, restraint, and explicit boundaries.', { kind: 'wordmark', title: 'Lajvard / field notebook', items: ['warmth', 'restraint', 'accountability'], caption: 'Project identity, not a product claim.' }, [section('ethos', 'Useful wonder, without theater.', 'We will separate sketches from prototypes, demos from dependable behavior, and intentions from shipped capabilities.', ['Source-backed writing', 'Visible uncertainty', 'Human judgment at the center'], 'DESIGN PRINCIPLE'), section('relationship', 'A product direction within Navin Research.', 'Lajvard has its own visual and narrative world while remaining explicit about its research status and relationship to the parent studio.', ['Independent product identity', 'Shared evidence discipline', 'No manufactured maturity'], 'CONTEXT')]),
      page('/contact/', 'Contact Lajvard', 'Contact for Lajvard research and corrections.', 'CONTACT / FIELD NOTEBOOK', 'Write to the notebook.', 'Contact is for research conversations, source corrections, and future updates. It is not a sales or preorder channel.', { kind: 'mail', title: 'Contact', items: ['question', 'source', 'context'], caption: 'Use the site contact channel when available.' }, [section('contact', 'Keep the signal clear.', 'Please include the question, source, or context you want to discuss. A request is not an availability commitment.', ['Research conversations', 'Source corrections', 'Update interest'], 'OPEN CHANNEL'), section('reply', 'A human response, when possible.', 'No outcome, response time, or availability is promised by this contact path.', ['No sales queue', 'No preorder queue', 'No support entitlement'], 'BOUNDARY')]),
      page('/privacy/', 'Privacy', 'Privacy principles for a concept-stage Lajvard site.', 'LEGAL / PRIVACY', 'Privacy is a design requirement.', 'Lajvard is not collecting robot telemetry because no Lajvard robot service is released here.', { kind: 'document', title: 'Privacy / plain language', items: ['no robot account', 'no voice profile', 'no telemetry'], caption: 'Website policy remains canonical.' }, [section('legal', 'No hidden product promise.', 'This concept page does not establish a robot account, journal, voice profile, or telemetry service. See the site privacy policy for website-level handling.', ['No robot data claim', 'Future collection requires notice', 'Deletion should be straightforward'], 'POLICY INTENT'), section('notice', 'Policy follows collection.', 'Future product data practices must be documented before collection and matched to the actual implementation.', ['Purpose stated', 'Retention stated', 'Controls stated'], 'FUTURE STANDARD')]),
      page('/terms/', 'Terms', 'Terms for reading the Lajvard concept site.', 'LEGAL / TERMS', 'A field notebook is not a purchase contract.', 'These pages describe an evolving concept. They do not create an order, license, warranty, support agreement, or promise of delivery.', { kind: 'document', title: 'Terms / plain language', items: ['concept content', 'no order', 'no warranty'], caption: 'Canonical site terms govern the web property.' }, [section('legal', 'Read the boundary.', 'Use the linked site terms for governing website conditions. Product terms do not exist because Lajvard is not released.', ['Concept content only', 'No purchase relationship', 'No availability commitment'], 'CONCEPT STAGE'), section('scope', 'The page cannot create a robot contract.', 'Descriptions, scenarios, and diagrams are informational until a real product and reviewed terms exist.', ['No service agreement', 'No license grant', 'No implied promise'], 'BOUNDARY')]),
      page('/404.html', 'Page not found', 'The Lajvard page could not be found.', 'WAYFINDING / ROUTE UNKNOWN', 'This path has gone quiet.', 'Try the field notebook home or return to life with Lajvard.', { kind: 'wayfinding', title: 'Lost / found', items: ['return home', 'read the notebook'], caption: 'Unknown route.' }, [section('help', 'Find the thread again.', 'The page may have moved while the concept changed.', ['Return home', 'Read life with Lajvard'], '404')])
    ]
  }
};

export default lajvard;
