const sources = {
  arkit: 'https://developer.apple.com/documentation/arkit/scene_understanding',
  nist: 'https://www.nist.gov/itl/iad/mig/voice-biometric-evaluations',
  sqlite: 'https://www.sqlite.org/docs.html',
  microduck: 'https://pollen-robotics.com/microduck',
  moflin: 'https://www.casio.com/us/moflin/',
  limx: 'https://limxdynamics.com/en'
};

const page = (path, title, description, headline, lede, sections, visual, cta) => ({
  path, title, description, headline, lede, visual, sections, ...(cta ? { cta } : {})
});

const lajvard = {
  slug: 'lajvard',
  name: 'Lajvard',
  eyebrow: 'WARM COMPANION FIELD NOTES / BLUEPRINT 01',
  status: 'CONCEPT STAGE · UPDATES, NOT PREORDER',
  catalogStatus: 'research',
  thesis: 'A cute, compact humanoid companion imagined for the small rituals of a room: noticing where it is, remembering what matters, and answering with a personality that feels present without pretending to be human.',
  intro: 'Lajvard is a product direction, not a shipping promise. This notebook describes the questions we are testing around a portable robot with spatial awareness, a private journal, and a gentle social presence.',
  proofNote: 'The capabilities below are intentions and design hypotheses. No Lajvard hardware, firmware, availability, performance, or offline/online behavior is being claimed here.',
  sections: [
    { id: 'room-notes', kicker: '01 / ROOM NOTES', title: 'A map that stays close to the moment', body: 'The imagined robot would build a modest spatial memory of its surroundings, then use that context to make movement and conversation feel less random. The map is a design question: what should be remembered, for how long, and with whose permission?', points: ['LiDAR mapping is an intended sensing direction, not a demonstrated Lajvard feature.', 'Spatial memory should be inspectable, editable, and easy to clear.', 'The companion should say when it does not know where something is.'] },
    { id: 'private-thread', kicker: '02 / PRIVATE THREAD', title: 'A journal, not a hidden dossier', body: 'Lajvard explores a local-first journal of moments an owner chooses to keep. Voice recognition and an offline-online split are proposed interaction patterns; they still need careful consent, identity, and failure-mode work before they can become product behavior.', points: ['Owner voice recognition remains a concept-stage intention.', 'Journal entries should carry clear provenance and deletion controls.', 'Network access should be visible rather than assumed.'] },
    { id: 'portable-character', kicker: '03 / PORTABLE CHARACTER', title: 'Personality with an honest boundary', body: 'The character is meant to be warm, compact, and a little humanoid without making emotional guarantees. Portable firmware is an aspiration for continuity across places, while the physical form, power system, and update path remain open research questions.', points: ['Personality is a creative direction, not evidence of sentience.', 'Portable firmware is an unbuilt intention.', 'Updates will document what changed; this is not a preorder announcement.'] }
  ],
  capabilities: ['Compact humanoid form', 'LiDAR mapping direction', 'Spatial memory direction', 'Owner voice recognition direction', 'Local-first journal direction'],
  evidence: [
    { label: 'Hardware', value: 'Not built or demonstrated', state: 'CONCEPT' },
    { label: 'Firmware', value: 'Portable architecture under exploration', state: 'UNVERIFIED' },
    { label: 'Privacy', value: 'Consent and deletion are design requirements', state: 'INTENDED' },
    { label: 'Availability', value: 'No release or preorder announced', state: 'UPDATES ONLY' }
  ],
  availability: { label: 'FIELD NOTEBOOK', title: 'Follow the questions, not a checkout button.', body: 'We will share design notes as the direction becomes more concrete. There is no preorder, delivery date, or availability claim attached to this page.', cta: 'Read future updates' },
  sourceLinks: [
    { label: 'Apple ARKit scene understanding', url: sources.arkit },
    { label: 'NIST voice biometric evaluations', url: sources.nist },
    { label: 'SQLite documentation', url: sources.sqlite },
    { label: 'Pollen Robotics MicroDuck', url: sources.microduck },
    { label: 'Casio Moflin', url: sources.moflin },
    { label: 'LimX Dynamics', url: sources.limx }
  ],
  site: {
    primaryCta: { label: 'Follow the field notes', href: '/availability/' },
    navigation: [
      { label: 'Life with Lajvard', href: '/life-with-lajvard/' },
      { label: 'The robot', href: '/robot/', children: [{ label: 'Movement', href: '/movement/' }, { label: 'Spatial memory', href: '/spatial-memory/' }, { label: 'Hardware', href: '/hardware/' }] },
      { label: 'Intelligence', href: '/intelligence/' },
      { label: 'Research', href: '/research/' },
      { label: 'Access', href: '/availability/' }
    ],
    footerGroups: [
      { title: 'Explore', links: [{ label: 'Gallery', href: '/gallery/' }, { label: 'Specs', href: '/specs/' }, { label: 'Developer', href: '/developer/' }] },
      { title: 'Read', links: [{ label: 'Research', href: '/research/' }, { label: 'Support', href: '/support/' }, { label: 'About', href: '/about/' }] },
      { title: 'Legal', links: [{ label: 'Privacy', href: '/privacy/' }, { label: 'Terms', href: '/terms/' }, { label: 'Contact', href: '/contact/' }] }
    ],
    pages: [
      page('/', 'Lajvard — a daily robot companion', 'A concept-stage field notebook for a warm, compact robot companion.', 'Life with a little presence.', 'Lajvard begins with the room: a quiet hello, a small ritual, a companion that knows the limits of what it knows. This is a concept, not a shipping announcement.', [
        { kind: 'promise', title: 'Designed around ordinary moments', body: 'The first question is not how much a robot can do. It is whether its presence makes a familiar day feel more attentive without becoming intrusive.', points: ['A companion for small rituals', 'Visible boundaries around memory and listening', 'No claim of sentience or emotional understanding'], status: 'CONCEPT STAGE' },
        { kind: 'evidence', title: 'What is real today', body: 'Lajvard has no demonstrated hardware or released software. These pages are a transparent design and research direction, informed by public work in robot form, mapping, voice biometrics, and local data systems.', points: ['Concept only', 'No price or availability announced', 'Research links are listed in the field notes'], status: 'UNVERIFIED' }
      ], { kind: 'system', title: 'Lajvard companion system sketch', caption: 'An original concept blueprint, not a product demo.' }, { title: 'Keep the notebook open', body: 'Get future notes when the direction changes.', label: 'Follow updates', href: '/availability/' }),
      page('/robot/', 'The robot', 'The proposed form, behavior, and boundaries of Lajvard.', 'A small body for a real room.', 'The form is intentionally open: compact, approachable, and capable of being present without taking over the room.', [{ kind: 'form', title: 'Character before specification', body: 'Lajvard explores a humanoid silhouette because faces, posture, and gesture can make a machine legible. That is a design hypothesis, not a claim about capability.', points: ['Compact humanoid direction', 'Warm character, not childish branding', 'Physical dimensions and materials are not final'], status: 'DESIGN DIRECTION' }], { kind: 'silhouette', title: 'Form study 01', caption: 'No production design or industrial-design claim.' }),
      page('/intelligence/', 'Intelligence', 'A truthful outline of proposed intelligence boundaries.', 'Helpful does not mean all-knowing.', 'Lajvard may combine perception, memory, and language someday. The system must show uncertainty instead of performing confidence.', [{ kind: 'architecture', title: 'Three modest layers', body: 'We are exploring a perception layer, a local journal, and an interaction layer. Their interfaces and models remain research questions.', points: ['Perception can be wrong', 'Memory is owner-controlled', 'Responses are not evidence of understanding'], status: 'RESEARCH DIRECTION' }], { kind: 'layers', title: 'Perception / memory / response', items: ['observe', 'retain with consent', 'respond'] }),
      page('/movement/', 'Movement', 'Movement research for a small companion robot.', 'Movement should earn its place.', 'A robot that moves through a home needs more than a list of actuators: it needs safe pauses, clear intent, and an honest answer when the route is unknown.', [{ kind: 'research', title: 'A question, not a benchmark', body: 'Public robotics work demonstrates many approaches to mobility, but none of it is evidence that Lajvard moves. We are studying how movement can feel calm and predictable.', points: ['Navigation is not demonstrated', 'No speed, range, or autonomy claim', 'Pause and ask when uncertain'], status: 'NOT DEMONSTRATED' }], { kind: 'motion-line', title: 'Pause is a behavior', caption: 'A storyboard, not a movement test.' }),
      page('/spatial-memory/', 'Spatial memory', 'How Lajvard might remember a room with consent.', 'Remember less. Remember clearly.', 'Spatial memory should be a readable relationship with a place, not an invisible dossier.', [{ kind: 'privacy', title: 'A map with an eraser', body: 'Scene understanding is an established research and platform area; Lajvard has no mapping implementation. Any future map would need inspection, correction, expiry, and deletion.', points: ['Show what was remembered', 'Let the owner correct it', 'Clear it without a support ticket'], status: 'INTENDED' }], { kind: 'map', title: 'Room memory study', items: ['seen', 'placed', 'forgotten'], caption: 'Inspired by public scene-understanding documentation; not a Lajvard feature.' }),
      page('/hardware/', 'Hardware', 'The open hardware questions behind Lajvard.', 'A body is a set of compromises.', 'Sensors, compute, power, sound, repair, and materials all shape how a companion belongs in a room.', [{ kind: 'inventory', title: 'No specification sheet yet', body: 'We are not publishing invented dimensions, battery life, sensors, materials, or certifications. The hardware program is not announced.', points: ['No prototype shown', 'No certification claimed', 'Repair and ownership remain open questions'], status: 'UNKNOWN' }], { kind: 'parts', title: 'Open hardware notebook', items: ['sensing', 'compute', 'power', 'shell'] }),
      page('/software/', 'Software', 'A proposed software surface for Lajvard.', 'Software should explain itself.', 'The software direction favors visible state: listening, thinking, remembering, offline, unavailable, and waiting for permission.', [{ kind: 'system', title: 'State before spectacle', body: 'A future companion needs understandable controls for journals, network access, updates, and recovery. No Lajvard software is currently released.', points: ['Clear listening indicator', 'Export and delete journal data', 'Fail closed when identity is uncertain'], status: 'UNBUILT' }], { kind: 'status', title: 'Listening / local / waiting', items: ['LISTENING', 'LOCAL', 'WAITING'] }),
      page('/developer/', 'Developer', 'A possible developer surface, without a fabricated SDK.', 'Nothing to install yet.', 'There is no Lajvard SDK, API, package, or developer preview to download. This page records the boundary clearly.', [{ kind: 'boundary', title: 'Future interfaces should be narrow', body: 'If a developer surface exists, it should document permissions, data ownership, versioning, and failure states before convenience APIs.', points: ['No SDK announced', 'No API key or sandbox available', 'Contact us with focused research questions'], status: 'NOT AVAILABLE' }], { kind: 'terminal', title: 'Developer access', caption: 'No commands or credentials are being offered.' }),
      page('/research/', 'Research', 'Public references and open questions guiding Lajvard research.', 'Borrow methods, not certainty.', 'Lajvard is informed by public documentation and products; those references are context, not proof of Lajvard capability.', [{ kind: 'reading', title: 'A small reading shelf', body: 'ARKit scene understanding, NIST voice biometric evaluation, SQLite, Pollen Robotics MicroDuck, Casio Moflin, and LimX Dynamics each illuminate different questions. Their work is not affiliated with Lajvard.', points: ['Mapping and scene context', 'Voice identity evaluation', 'Local data primitives', 'Robotic form and movement'], status: 'SOURCE-BACKED CONTEXT' }], { kind: 'references', title: 'Methods under review', items: ['map', 'voice', 'store', 'move'], caption: 'See source links for primary references.' }),
      page('/life-with-lajvard/', 'Life with Lajvard', 'The daily rituals Lajvard is being designed to support.', 'Start with the morning, not the dashboard.', 'A companion earns trust through small, legible moments: a greeting you can dismiss, a memory you can edit, a pause you understand.', [{ kind: 'ritual', title: 'A day in four gestures', body: 'Wake, notice, remember, rest. These are story beats for design exploration, not a claimed user experience.', points: ['Say hello without demanding attention', 'Notice a change without inventing a reason', 'Rest when the owner asks'], status: 'SCENARIO' }], { kind: 'daybook', title: 'A daybook, not a feature list', items: ['morning', 'afternoon', 'evening'], caption: 'Concept storyboard.' }),
      page('/gallery/', 'Gallery', 'A quiet index of Lajvard concept studies.', 'The archive is intentionally small.', 'There are no finished product photographs to present. This gallery is reserved for clearly labelled sketches, diagrams, and future verified media.', [{ kind: 'archive', title: 'No finished gallery yet', body: 'We will label concept art, renders, prototypes, and captured product behavior separately. Nothing here should be mistaken for a shipping unit.', points: ['Concept', 'Prototype', 'Demonstration', 'Released'], status: 'AWAITING MATERIAL' }], { kind: 'gallery', title: 'Archive placeholder', caption: 'No product photography or prototype claim.' }),
      page('/specs/', 'Specs', 'Current known and unknown Lajvard specifications.', 'The honest specification sheet.', 'A blank field is more useful than a made-up number. The following are not announced.', [{ kind: 'table', title: 'Not yet specified', body: 'Dimensions, mass, battery, compute, sensors, connectivity, materials, ingress rating, and certifications are all unknown.', points: ['Dimensions — UNKNOWN', 'Battery — UNKNOWN', 'Sensors — INTENDED DIRECTION', 'Certifications — NOT CLAIMED'], status: 'UNKNOWN' }], { kind: 'spec-ledger', title: 'Known / unknown', items: ['direction', 'question', 'evidence'] }),
      page('/availability/', 'Availability', 'Availability status for the Lajvard concept.', 'No preorder. No delivery date.', 'Lajvard is not available to buy, reserve, or test. This page will change only when a verifiable status changes.', [{ kind: 'status', title: 'Updates only', body: 'There is no announced launch, waitlist, region, pilot, or distribution plan. You can follow the research without mistaking interest for an order.', points: ['No release announced', 'No pilot announced', 'No shipping claim'], status: 'NOT AVAILABLE' }], { kind: 'stamp', title: 'UPDATES ONLY', caption: 'Status checked: concept stage.' }, { title: 'Receive field notes', body: 'A quiet channel for verified updates.', label: 'Contact the team', href: '/contact/' }),
      page('/pricing/', 'Pricing', 'Pricing status for Lajvard.', 'There is no price to quote.', 'No price, deposit, subscription, or ownership model has been announced. Please do not treat comparisons or estimates as Lajvard pricing.', [{ kind: 'status', title: 'Pricing is unknown', body: 'We will publish a price only with a real product decision and the terms needed to understand it.', points: ['No preorder deposit', 'No subscription announced', 'No estimate presented as fact'], status: 'NOT ANNOUNCED' }], { kind: 'blank', title: 'Price: not announced', caption: 'Truthful absence is part of the product page.' }),
      page('/support/', 'Support', 'Support boundary for a concept-stage project.', 'No support desk yet.', 'Because Lajvard is not released, there is no technical support channel, repair program, warranty, or service-level promise.', [{ kind: 'help', title: 'Questions are welcome', body: 'For research questions or corrections to a source-backed claim, contact the team. We will not imply support for hardware that does not exist.', points: ['No warranty announced', 'No repair policy announced', 'Research questions welcome'], status: 'CONCEPT STAGE' }], { kind: 'mail', title: 'A human inbox', caption: 'For questions, not troubleshooting a released robot.' }),
      page('/about/', 'About Lajvard', 'Why this robot research exists.', 'A companion project, kept accountable.', 'Lajvard is a Navin Research product direction exploring how robotics can enter daily life with warmth, restraint, and explicit boundaries.', [{ kind: 'ethos', title: 'Useful wonder, without theater', body: 'We will separate sketches from prototypes, demos from dependable behavior, and intentions from shipped capabilities.', points: ['Source-backed writing', 'Visible uncertainty', 'Human judgment at the center'], status: 'DESIGN PRINCIPLE' }], { kind: 'wordmark', title: 'Lajvard / field notebook' }),
      page('/contact/', 'Contact Lajvard', 'Contact for Lajvard research and corrections.', 'Write to the notebook.', 'Contact is for research conversations, source corrections, and future updates. It is not a sales or preorder channel.', [{ kind: 'contact', title: 'Keep the signal clear', body: 'Please include the question, source, or context you want to discuss. We will preserve the distinction between a request and an availability commitment.', points: ['Research conversations', 'Source corrections', 'Update interest'], status: 'OPEN CHANNEL' }], { kind: 'mail', title: 'Contact', caption: 'Use the site contact channel when available.' }),
      page('/privacy/', 'Privacy', 'Privacy principles for a concept-stage Lajvard site.', 'Privacy is a design requirement.', 'Lajvard is not collecting robot telemetry because no Lajvard robot service is released here. Any future data practice must be documented before collection.', [{ kind: 'legal', title: 'No hidden product promise', body: 'This concept page does not establish a robot account, journal, voice profile, or telemetry service. See the site privacy policy for website-level handling.', points: ['No robot data claim', 'Future collection requires notice', 'Deletion should be straightforward'], status: 'POLICY INTENT' }], { kind: 'document', title: 'Privacy / plain language' }),
      page('/terms/', 'Terms', 'Terms for reading the Lajvard concept site.', 'A field notebook is not a purchase contract.', 'These pages describe an evolving concept. They do not create an order, license, warranty, support agreement, or promise of delivery.', [{ kind: 'legal', title: 'Read the boundary', body: 'Use the linked site terms for governing website conditions. Product terms do not exist because Lajvard is not released.', points: ['Concept content only', 'No purchase relationship', 'No availability commitment'], status: 'CONCEPT STAGE' }], { kind: 'document', title: 'Terms / plain language' }),
      page('/404.html', 'Page not found', 'The Lajvard page could not be found.', 'This path has gone quiet.', 'Try the field notebook home or return to life with Lajvard.', [{ kind: 'help', title: 'Find the thread again', body: 'The page may have moved while the concept changed.', points: ['Return home', 'Read life with Lajvard'], status: '404' }], { kind: 'wayfinding', title: 'Lost / found' })
    ]
  }
};

export default lajvard;
