const sori = {
  slug: "sori",
  name: "Sori",
  eyebrow: "PROGRAMMABLE VOICE RUNTIME",
  status: "BETA INTEREST ONLY",
  thesis: "A quiet, local-first voice runtime for desktop work.",
  intro: "Sori is a Windows-first desktop MVP foundation: a small instrument for speaking into the active app, with the runtime, permissions, and boundaries kept visible when they matter.",
  proofNote: "The repository documents a Rust daemon, loopback IPC, SQLite persistence, and explicit capability diagnostics. Microphone speech, physical hotkey delivery, focused-app insertion, and transcript persistence from a real session remain UNVERIFIED and machine-dependent.",
  sections: [
    { id: "hot-path", kicker: "01 / THE HOT PATH", title: "A voice gesture, not another destination.", body: "The intended daily path is compact: grant permissions, hold a hotkey, speak, release, and let text meet the focused app. The overlay stays small and appears for listening, preview, or attention.", points: ["Hold-to-speak interaction", "Tiny overlay and tray presence", "Focused-app insertion is an explicit boundary"] },
    { id: "runtime", kicker: "02 / THE INSTRUMENT", title: "Programmable beneath the surface.", body: "A desktop shell can talk to a local Sori daemon over bounded loopback IPC. Context, audio, routing, history, profiles, skills, and permissions are arranged as runtime concerns rather than a dashboard of promises.", points: ["Rust daemon with loopback IPC", "Local SQLite metadata and history", "Progressive disclosure from basic to expert"] },
    { id: "boundary", kicker: "03 / THE BOUNDARY", title: "Useful, with the unknowns marked.", body: "Sori keeps audio local-first by default in its product direction and gates side effects behind dry-run and approval. The current foundation is not presented as a verified physical voice vertical slice.", points: ["Cloud and local providers can be routed deliberately", "Side effects require explicit approval by default", "Physical microphone and insertion evidence remain UNVERIFIED"] }
  ],
  capabilities: ["Local-first desktop runtime", "Hotkey-led voice interaction", "Model and provider routing", "Local history and metadata", "Skills, tools, and permissions"],
  evidence: [
    { label: "Runtime shape", value: "Rust daemon + loopback IPC", state: "DOCUMENTED" },
    { label: "Persistence", value: "SQLite metadata", state: "DOCUMENTED" },
    { label: "Physical voice path", value: "Microphone → text → focused app", state: "UNVERIFIED" },
    { label: "Availability", value: "Beta interest only", state: "CONCEPT STAGE" }
  ],
  availability: { label: "EARLY SIGNAL", title: "Quietly taking interest.", body: "Sori is not open for general product access. Registering interest helps shape the next review without implying a release, pricing, or physical-runtime guarantee.", cta: "Register beta interest" },
  sourceLinks: [
    { label: "Sori README / product thesis", url: "https://github.com/kyoo-147/Sori/blob/main/README.md" },
    { label: "Sori repository", url: "https://github.com/kyoo-147/Sori" }
  ],
  site: {
    primaryCta: { label: "Register beta interest", href: "/contact/" },
    navigation: [
      { label: "Product", href: "/product/" },
      { label: "Features", href: "/features/", children: [{ label: "Voice dictation", href: "/voice-dictation/" }, { label: "Voice actions", href: "/voice-actions/" }, { label: "Apps", href: "/apps/" }] },
      { label: "Use cases", href: "/use-cases/", children: [{ label: "Writing", href: "/use-cases/writing/" }, { label: "Developers", href: "/use-cases/developers/" }, { label: "Communication", href: "/use-cases/communication/" }] },
      { label: "Docs", href: "/docs/" },
      { label: "Access", href: "/download/" }
    ],
    footerGroups: [
      { title: "Explore", links: [{ label: "Product", href: "/product/" }, { label: "Features", href: "/features/" }, { label: "Use cases", href: "/use-cases/" }, { label: "Changelog", href: "/changelog/" }] },
      { title: "Trust", links: [{ label: "Security", href: "/security/" }, { label: "Privacy", href: "/privacy/" }, { label: "Terms", href: "/terms/" }] },
      { title: "Contact", links: [{ label: "Docs", href: "/docs/" }, { label: "Contact", href: "/contact/" }, { label: "Download", href: "/download/" }] }
    ],
    pages: [
      { path: "/", title: "Sori — voice, with the boundary visible", description: "A local-first voice runtime for desktop work.", eyebrow: "VOICE COMPUTING / BETA INTEREST ONLY", headline: "Speak to the work already in front of you.", lede: "Sori is a Windows-first desktop foundation for a compact path: speech → text → intent → action. The physical voice path is UNVERIFIED.", visual: { kind: "signal-line", title: "speech → text → intent → action", items: ["capture", "transcribe", "interpret", "approve"], caption: "A product primitive, not a performance claim." }, sections: [{ kind: "proof", title: "A small path, honestly described.", body: "The repository documents a Rust daemon, bounded loopback IPC, SQLite metadata, and capability diagnostics. It does not yet prove a real microphone-to-focused-app session." }, { kind: "boundary", title: "Local-first by direction.", body: "Provider routing and side effects are treated as explicit runtime decisions. Availability, pricing, and physical delivery are not announced." }], cta: { title: "Keep the signal open.", body: "Register interest for future access updates.", label: "Register beta interest", href: "/contact/" } },
      { path: "/product/", title: "The Sori product", description: "Understand the Sori runtime and its boundaries.", eyebrow: "THE INSTRUMENT", headline: "One gesture. Four deliberate steps.", lede: "Sori keeps the voice path legible instead of hiding it behind a destination app.", visual: { kind: "pipeline", title: "The hot path", items: ["Speech", "Text", "Intent", "Action"], caption: "Action remains a permissioned boundary." }, sections: [{ kind: "workflow", title: "Designed around the focused app.", body: "The intended interaction is hold, speak, release, review or route, then insert or act. Overlay and tray presence stay secondary to the work." }, { kind: "evidence", title: "What exists on paper.", body: "Rust daemon, loopback IPC, SQLite persistence, model/provider routing, skills, tools, and permissions are documented in the source repository." }], cta: { title: "Read the implementation boundary.", body: "The docs keep product direction separate from verified behavior.", label: "Open docs", href: "/docs/" } },
      { path: "/features/", title: "Sori features", description: "Explore the voice runtime primitives.", eyebrow: "FEATURES", headline: "Primitives before promises.", lede: "Each feature names its boundary; none implies benchmarked quality or general availability.", visual: { kind: "index", title: "Five runtime concerns", items: ["Dictation", "Actions", "Routing", "History", "Permissions"] }, sections: [{ kind: "feature-list", title: "A focused set of tools.", body: "Voice dictation is the text path. Voice actions are the intent path. Apps are destinations. Routing and history make the runtime inspectable." , points: ["Voice dictation", "Voice actions", "App-aware intent", "Provider routing", "Local history"] }], cta: { title: "See the path in context.", body: "Start with a practical use case.", label: "Browse use cases", href: "/use-cases/" } },
      { path: "/voice-dictation/", title: "Voice dictation | Sori", description: "Speak, review, and place text in the active app.", eyebrow: "01 / TEXT", headline: "Voice becomes editable text.", lede: "The intended dictation path moves from speech to text, with insertion treated as an explicit capability.", visual: { kind: "transcript", title: "TEXT PREVIEW", items: ["listening", "preview", "insert"], caption: "Physical microphone and insertion are UNVERIFIED." }, sections: [{ kind: "workflow", title: "For the sentence already in motion.", body: "Use a hold-to-speak gesture, keep a small preview, and decide whether text should meet the focused app. This is a direction, not a verified session claim." }, { kind: "boundary", title: "Insertion is not assumed.", body: "Permissions, target ownership, and physical delivery must be checked by the runtime before an action is trusted." }] },
      { path: "/voice-actions/", title: "Voice actions | Sori", description: "Turn spoken intent into permissioned desktop actions.", eyebrow: "02 / INTENT", headline: "Intent, before action.", lede: "Sori's action direction separates what was said from what a tool may do next.", visual: { kind: "approval", title: "PROPOSE → REVIEW → ACT", items: ["intent", "dry run", "approval"] }, sections: [{ kind: "boundary", title: "Side effects stay visible.", body: "Tools and skills are runtime concerns. Approval and dry-run boundaries are preferred over silent automation." }, { kind: "evidence", title: "No automation claim.", body: "The current public source documents the design boundary; it does not establish a production action catalog or physical proof." }] },
      { path: "/apps/", title: "Apps | Sori", description: "A voice layer for the focused desktop app.", eyebrow: "DESTINATIONS", headline: "Meet the app already open.", lede: "Sori is conceived as a layer across desktop work, not as another place to paste your day.", visual: { kind: "window", title: "FOCUSED APP", items: ["context", "target", "permission"], caption: "App coverage is not announced." }, sections: [{ kind: "workflow", title: "Context is a boundary.", body: "The active window, target, and permission state matter before text or an action crosses into another app." }, { kind: "boundary", title: "No compatibility list yet.", body: "Sori does not claim support for named apps or operating systems beyond its Windows-first direction." }] },
      { path: "/use-cases/", title: "Use cases | Sori", description: "Practical voice-computing directions for desktop work.", eyebrow: "USE CASES", headline: "Less reaching. More thinking.", lede: "These are product directions, not customer results or workflow guarantees.", visual: { kind: "index", title: "Three desks", items: ["Writing", "Development", "Communication"] }, sections: [{ kind: "use-case", title: "Choose the work, then inspect the boundary.", body: "Writing needs clean text. Development needs precise intent. Communication needs review before sending. Each path keeps a human decision visible.", points: ["Writing", "Developers", "Communication"] }] },
      { path: "/use-cases/writing/", title: "Voice for writing | Sori", description: "Draft text without leaving the page.", eyebrow: "WRITING", headline: "Keep the sentence close.", lede: "Dictate a draft, review the text, and decide when it belongs in the editor.", visual: { kind: "margin-note", title: "DRAFT / REVIEW / PLACE", items: ["capture a thought", "edit the text", "insert deliberately"] }, sections: [{ kind: "workflow", title: "A quieter drafting loop.", body: "Sori's intended value is reducing the distance between a thought and the document already open. No writing speed or quality result is claimed." }, { kind: "boundary", title: "You keep the final say.", body: "Preview and insertion are separate steps; physical insertion remains UNVERIFIED." }] },
      { path: "/use-cases/developers/", title: "Voice for developers | Sori", description: "Explore voice input for technical work.", eyebrow: "DEVELOPERS", headline: "Say the next precise thing.", lede: "A voice runtime can help move intent into technical work while keeping tools and side effects inspectable.", visual: { kind: "terminal", title: "INTENT / TOOL / RESULT", items: ["describe", "dry run", "review"] }, sections: [{ kind: "workflow", title: "Words are not permissions.", body: "A spoken request may become an intent proposal; a tool should still expose its scope and wait at the appropriate approval boundary." }, { kind: "boundary", title: "No coding benchmark.", body: "Sori publishes no accuracy, latency, productivity, or developer outcome claim." }] },
      { path: "/use-cases/communication/", title: "Voice for communication | Sori", description: "Prepare messages with a visible review step.", eyebrow: "COMMUNICATION", headline: "Draft first. Send never by accident.", lede: "Voice can prepare a message; sending is a consequential action and should remain explicit.", visual: { kind: "approval", title: "DRAFT → REVIEW → SEND", items: ["compose", "inspect", "confirm"] }, sections: [{ kind: "boundary", title: "A message is not a side effect-free output.", body: "Sori's product direction treats communication actions as permissioned and reviewable." }, { kind: "evidence", title: "Direction, not delivery.", body: "No mail, chat, or calendar integration is announced or verified." }] },
      { path: "/download/", title: "Download Sori", description: "Current Sori access and installation status.", eyebrow: "ACCESS", headline: "Not a public download.", lede: "Sori is currently beta interest only. There is no released installer or general-access package represented here.", visual: { kind: "status", title: "CURRENT ACCESS", items: ["BETA INTEREST ONLY", "NO PUBLIC INSTALLER", "UNVERIFIED PHYSICAL PATH"] }, sections: [{ kind: "status", title: "Access status.", body: "Register interest to hear about a future review. This page makes no availability, pricing, or installation promise." }], cta: { title: "Stay informed.", body: "Send a beta-interest request.", label: "Contact Sori", href: "/contact/" } },
      { path: "/pricing/", title: "Sori pricing", description: "Pricing status for Sori.", eyebrow: "ACCESS", headline: "Pricing is not announced.", lede: "Sori has no public pricing because it is not open for general product access.", visual: { kind: "status", title: "PRICING", items: ["NOT ANNOUNCED", "NO PLAN COMPARISON", "NO BILLING CLAIM"] }, sections: [{ kind: "boundary", title: "No invented plans.", body: "There are no prices, tiers, trials, or customer commitments to present at this stage." }] },
      { path: "/security/", title: "Sori security", description: "Security direction and known evidence boundaries.", eyebrow: "TRUST", headline: "Make the boundary inspectable.", lede: "Sori's source documents local runtime boundaries and capability diagnostics; this page does not claim a certification or completed audit.", visual: { kind: "ledger", title: "DOCUMENTED / UNVERIFIED", items: ["loopback IPC", "permissions", "SQLite metadata", "physical path"] }, sections: [{ kind: "evidence", title: "Documented in source.", body: "The repository describes a Rust daemon, loopback IPC, SQLite persistence, and explicit capability diagnostics." }, { kind: "boundary", title: "What is not claimed.", body: "No certification, audit, threat-model result, or production security guarantee is asserted." }] },
      { path: "/privacy/", title: "Sori privacy", description: "Privacy direction for a local-first voice runtime.", eyebrow: "TRUST", headline: "Keep data decisions visible.", lede: "Local-first is the product direction. Actual collection, retention, and provider behavior depend on an eventual release and are not represented as settled policy here.", visual: { kind: "ledger", title: "DATA PATH", items: ["capture", "route", "persist", "remove"] }, sections: [{ kind: "boundary", title: "Direction is not policy.", body: "Sori does not claim that a shipped service, retention schedule, or processor list exists today." }, { kind: "evidence", title: "Ask before access.", body: "The source repository is the current reference for runtime shape; product privacy terms remain to be published." }] },
      { path: "/changelog/", title: "Sori changelog", description: "Sori release and research notes.", eyebrow: "RECORD", headline: "A short record, without theater.", lede: "No public release history is claimed on this page yet.", visual: { kind: "timeline", title: "CURRENT RECORD", items: ["MVP foundation", "capability diagnostics", "beta interest only"] }, sections: [{ kind: "status", title: "Nothing shipped to announce.", body: "This page will record dated, source-backed changes when a public release exists." }] },
      { path: "/docs/", title: "Sori docs", description: "Technical orientation for the Sori runtime.", eyebrow: "REFERENCE", headline: "Start with the boundary map.", lede: "The public repository is the authoritative technical reference for the current foundation.", visual: { kind: "index", title: "READ IN ORDER", items: ["README", "runtime shape", "capabilities", "open questions"] }, sections: [{ kind: "documentation", title: "Current source map.", body: "Read the README for the product thesis and repository structure. Look for runtime, permissions, IPC, and persistence boundaries before assuming a user-visible behavior." }], cta: { title: "Go to the source.", body: "Inspect the public Sori repository.", label: "Read Sori on GitHub", href: "https://github.com/kyoo-147/Sori" } },
      { path: "/contact/", title: "Contact Sori", description: "Register interest in future Sori access.", eyebrow: "CONTACT", headline: "Bring a careful question.", lede: "Sori is collecting beta interest, not promising access, timelines, pricing, or a working physical voice path.", visual: { kind: "signal-line", title: "BETA INTEREST", items: ["your context", "your question", "no commitment"] }, sections: [{ kind: "status", title: "A human review comes first.", body: "Share why the voice runtime matters to your work. Requests are signals for future product decisions, not a release queue." }], cta: { title: "Register interest.", body: "Use the available Navin Research contact channel.", label: "Contact Navin Research", href: "https://navinresearch.com/" } },
      { path: "/terms/", title: "Sori terms", description: "Terms status for Sori.", eyebrow: "LEGAL", headline: "Terms will follow access.", lede: "Sori has no public product access or service terms to present today.", visual: { kind: "status", title: "TERMS", items: ["NOT PUBLISHED", "NO SERVICE CLAIM", "ACCESS NOT OPEN"] }, sections: [{ kind: "boundary", title: "No implied agreement.", body: "Interest registration does not constitute product access, a license, or a service commitment. Published terms will govern any future release." }] },
      { path: "/404.html", title: "Sori — page not found", description: "The requested Sori page was not found.", eyebrow: "404 / OUT OF RANGE", headline: "That signal is not here.", lede: "Return to the Sori index and choose a documented path.", visual: { kind: "status", title: "NOT FOUND", items: ["check the address", "return to home"] }, sections: [{ kind: "navigation", title: "Find the instrument.", body: "Use the home page to review Sori's current product direction and access status." }], cta: { title: "Back to Sori.", body: "Start at the beginning.", label: "Go home", href: "/" } }
    ]
  }
};

export default sori;
