import { escapeHtml, headMarkup } from "../product-renderer-helpers.mjs";
const e=escapeHtml;const normalizePath=(v="/")=>v==="/404.html"?v:(`/${String(v).replace(/^\/+|\/+$/g,"")}/`).replace("//","/");const ext=(h="")=>/^https?:|^mailto:/.test(h)?' target="_blank" rel="noopener noreferrer"':"";
const layoutFor=(p)=>/docs|developers/.test(p.path)?"docs":/review|validation|reconciliation|security|privacy|terms/.test(p.path)?"ledger":/document-processing|extraction|workflows|use-cases/.test(p.path)?"workflow":/pricing|contact/.test(p.path)?"availability":"editorial";
function nav(site,path){return site.navigation.map(item=>{const href=item.href||item.children?.[0]?.href||"/",active=normalizePath(href)===path||item.children?.some(c=>normalizePath(c.href)===path);if(item.children?.length)return `<details class="ds-nav-group"${active?" data-current":""}><summary>${e(item.label)}</summary><div>${item.children.map(c=>`<a href="${e(c.href)}"${normalizePath(c.href)===path?' aria-current="page"':""}${ext(c.href)}>${e(c.label)}</a>`).join("")}</div></details>`;return `<a href="${e(href)}"${active?' aria-current="page"':""}${ext(href)}>${e(item.label)}</a>`}).join("")}
function documentView(page){const items=(page.visual?.items||["Source page","Field","Rule","Reviewer"]).slice(0,5);return `<figure class="ds-document"><div class="ds-document__sheet"><header><span>DOSSIER / INPUT</span><span>PAGE 01</span></header><h2>${e(page.visual?.title||"Document under review")}</h2><p class="ds-document__redacted">████ ████████ ███ █████</p><div class="ds-document__region"><span>SOURCE REGION</span><p>${e(page.visual?.caption||"Illustrative document canvas. No real customer document is shown.")}</p></div><ol>${items.map((item,index)=>`<li style="--x:${8+(index*11)%42}%;--w:${32+(index*13)%38}%"><span>${String(index+1).padStart(2,"0")}</span>${e(item)}</li>`).join("")}</ol><b class="ds-document__stamp">REVIEW</b></div><figcaption>Original abstract diagram · project-owned · no OCR claim.</figcaption></figure>`}
function workstation(page){return `<section class="ds-workstation">${(page.sections||[]).map((s,i)=>`<article class="ds-case"><div class="ds-case__meta"><span>CASE ${String(i+1).padStart(3,"0")}</span><b>${e(s.status||"OPEN")}</b></div><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p></div>${s.points?.length?`<dl>${s.points.map((p,j)=>`<div><dt>F${String(j+1).padStart(2,"0")}</dt><dd>${e(p)}</dd></div>`).join("")}</dl>`:""}</article>`).join("")}</section>`}
function workflow(page){return `<section class="ds-pipeline"><header><span>DOCUMENT PIPELINE</span><p>Each transition keeps the source and exception visible.</p></header><ol>${(page.sections||[]).map((s,i)=>`<li><div class="ds-pipeline__step"><span>${String(i+1).padStart(2,"0")}</span><i aria-hidden="true"></i></div><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${s.status?`<mark>${e(s.status)}</mark>`:""}</div>${s.points?.length?`<ul>${s.points.map(p=>`<li>${e(p)}</li>`).join("")}</ul>`:""}</li>`).join("")}</ol></section>`}
function ledger(page){return `<section class="ds-review"><aside><span>REVIEW QUEUE</span><h2>Exceptions first.</h2><p>Automated suggestions remain separate from reviewer decisions.</p></aside><div>${(page.sections||[]).map((s,i)=>`<article><header><span>ITEM ${String(i+1).padStart(3,"0")}</span><strong>${e(s.status||"REVIEW REQUIRED")}</strong></header><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${s.points?.length?`<ul>${s.points.map(p=>`<li><i></i>${e(p)}</li>`).join("")}</ul>`:""}</article>`).join("")}</div></section>`}
function docs(page){return `<section class="ds-docs"><nav aria-label="Documentation contents"><span>CONTENTS</span>${(page.sections||[]).map((s,i)=>`<a href="#d${i+1}">${String(i+1).padStart(2,"0")} ${e(s.title)}</a>`).join("")}</nav><article>${(page.sections||[]).map((s,i)=>`<section id="d${i+1}"><span>${String(i+1).padStart(2,"0")}</span><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${s.status?`<mark>${e(s.status)}</mark>`:""}</div>${s.points?.length?`<pre><code>${s.points.map(p=>`field: ${e(p)}`).join("\n")}</code></pre>`:""}</section>`).join("")}</article></section>`}
function availability(page){const sections=page.sections||[];return `<section class="ds-register"><header><span>COMMERCIAL REGISTER</span><strong>${e(sections[0]?.status||"NOT PUBLISHED")}</strong></header><div class="ds-register__notice"><span>NOTICE</span><h2>${e(page.headline||page.title)}</h2><p>Dossier is not presented as generally available. No amount, tier, or purchasing route is inferred.</p></div><table><tbody>${sections.map((section,index)=>`<tr><th>${String(index+1).padStart(2,"0")} ${e(section.title)}</th><td>${e(section.body)}</td><td>${e(section.status||"UNPUBLISHED")}</td></tr>`).join("")}</tbody></table></section>`}

function content(page,mode){if(mode==="availability")return availability(page);if(mode==="workflow")return workflow(page);if(mode==="ledger")return ledger(page);if(mode==="docs")return docs(page);return workstation(page)}
function footer(product,site){return `<footer class="ds-footer"><div class="ds-footer__folio"><span>DOSSIER</span><strong>Document intelligence with the source still attached.</strong><p>${e(product.thesis)}</p></div><div class="ds-footer__index">${site.footerGroups.map((g,i)=>`<section><span>0${i+1}</span><h3>${e(g.title)}</h3>${g.links.map(l=>`<a href="${e(l.href)}"${ext(l.href)}>${e(l.label)}</a>`).join("")}</section>`).join("")}</div><div class="ds-footer__base"><span>© <span data-current-year></span> Dossier</span><a href="https://navinresearch.com/products/">Navin Research / Products ↗</a></div></footer>`}
function render(product,site,page){const path=normalizePath(page.path),mode=layoutFor(page),home=path==="/",cta=page.cta||site.primaryCta;return `<!doctype html><html lang="en" class="no-js"><head>${headMarkup({product,page,path,layout:mode,isHome:home})}</head><body class="ds-body ds-${mode}" data-product="dossier" data-route="${e(path)}"><a class="skip-link" href="#main-content">Skip to content</a><header class="ds-header"><a class="ds-logo" href="/" aria-label="Dossier home"><span>D</span>DOSSIER</a><div class="ds-file"><span>FILE</span><b>${e(path==="/"?"000 / INTAKE":path.replaceAll("/"," ").trim().toUpperCase())}</b></div><button class="product-menu-button ds-menu-button" type="button" aria-controls="product-menu" aria-expanded="false" data-product-menu>INDEX</button><div class="product-menu ds-menu" id="product-menu"><nav aria-label="Primary navigation">${nav(site,path)}</nav><a class="ds-contact" href="/contact/">Open a case ↗</a></div></header><main id="main-content"><section class="ds-hero"><div class="ds-hero__copy"><p>${e(page.eyebrow||"DOCUMENT INTELLIGENCE / ACCOUNTABLE HANDOFF")}</p><h1>${e(page.headline||page.title)}</h1><p>${e(page.lede||page.description)}</p>${home?`<div class="ds-actions"><a href="/product/">ENTER THE WORKSTATION</a><a href="/review/">SEE THE REVIEW QUEUE →</a></div>`:""}</div>${documentView(page)}</section>${content(page,mode)}${cta?`<section class="ds-handoff"><span>EXPORT / HANDOFF</span><div><h2>${e(cta.title||"Keep the source attached")}</h2><p>${e(cta.body||product.availability.body)}</p></div><a href="${e(cta.href)}"${ext(cta.href)}>${e(cta.label)} →</a></section>`:""}${home?`<section class="ds-proof"><div><span>AUDIT NOTES</span><h2>Proof belongs beside the proposition.</h2><p>${e(product.proofNote)}</p></div><table><tbody>${product.evidence.map((item,i)=>`<tr><th>${String(i+1).padStart(2,"0")} ${e(item.label)}</th><td>${e(item.value)}</td><td>${e(item.state)}</td></tr>`).join("")}</tbody></table></section>`:""}</main>${footer(product,site)}</body></html>`}
export default function renderDossier(product,site,page){return render(product,site,page).replace(/[ \t]+$/gm,"")};export{layoutFor,normalizePath};
