import { escapeHtml, headMarkup } from "../product-renderer-helpers.mjs";
const e=escapeHtml;const normalizePath=(v="/")=>v==="/404.html"?v:(`/${String(v).replace(/^\/+|\/+$/g,"")}/`).replace("//","/");const ext=(h="")=>/^https?:|^mailto:/.test(h)?' target="_blank" rel="noopener noreferrer"':"";
const layoutFor=(p)=>/docs|github/.test(p.path)?"docs":/research-workflow|how-it-works/.test(p.path)?"workflow":/sources|evidence|experiments|releases/.test(p.path)?"ledger":/access|contact/.test(p.path)?"availability":"editorial";
function nav(site,path){return site.navigation.map(item=>{const href=item.href||item.children?.[0]?.href||"/",active=normalizePath(href)===path||item.children?.some(c=>normalizePath(c.href)===path);if(item.children?.length)return `<details class="hh-nav-group"${active?" data-current":""}><summary>${e(item.label)} +</summary><div>${item.children.map(c=>`<a href="${e(c.href)}"${normalizePath(c.href)===path?' aria-current="page"':""}${ext(c.href)}>${e(c.label)}</a>`).join("")}</div></details>`;return `<a href="${e(href)}"${active?' aria-current="page"':""}${ext(href)}>${e(item.label)}</a>`}).join("")}
function packet(page){const items=(page.visual?.items||["Question","Sources","Checks","Review"]).slice(0,5);return `<div class="hh-packet"><div class="hh-packet__label"><span>HOWHOW RESEARCH PACKET</span><b>HANDLE WITH CURIOSITY</b></div><div class="hh-packet__question"><small>QUESTION</small><strong>${e(page.visual?.title||page.headline||page.title)}</strong></div><ol>${items.map((item,index)=>`<li><span>${String(index+1).padStart(2,"0")}</span><b>${e(item)}</b><i>${index===items.length-1?"HUMAN REVIEW":"ATTACHED"}</i></li>`).join("")}</ol><p>${e(page.visual?.caption||"Illustrative packet. Sources and states are shown as a design contract, not live evidence.")}</p><i class="hh-sticker" aria-hidden="true">WHY?</i></div>`}
function editorial(page){return `<section class="hh-shelf">${(page.sections||[]).map((s,i)=>`<article class="hh-box hh-box--${(i%4)+1}"><header><span>PACKET ${String(i+1).padStart(2,"0")}</span>${s.status?`<b>${e(s.status)}</b>`:""}</header><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p></div>${s.points?.length?`<ul>${s.points.map(p=>`<li>${e(p)}</li>`).join("")}</ul>`:""}${s.cta?`<a href="${e(s.cta.href)}"${ext(s.cta.href)}>${e(s.cta.label)} ↗</a>`:""}</article>`).join("")}</section>`}
function workflow(page){return `<section class="hh-recipe"><header><span>RESEARCH RECIPE</span><h2>Make the reasoning inspectable.</h2></header><ol>${(page.sections||[]).map((s,i)=>`<li><div class="hh-recipe__badge">${String(i+1).padStart(2,"0")}</div><div><p>METHOD</p><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${s.status?`<strong>${e(s.status)}</strong>`:""}</div>${s.points?.length?`<ul>${s.points.map(p=>`<li>${e(p)}</li>`).join("")}</ul>`:""}</li>`).join("")}</ol></section>`}
function ledger(page){return `<section class="hh-ledger"><header><div><span>EVIDENCE RECEIPT</span><h2>Nothing important without a source trail.</h2></div><p>States distinguish illustration, source, check, and human decision.</p></header>${(page.sections||[]).map((s,i)=>`<article><div class="hh-ledger__stamp">${e(s.status||"CHECK")}</div><div><span>LINE ${String(i+1).padStart(2,"0")}</span><h2>${e(s.title)}</h2><p>${e(s.body)}</p></div>${s.points?.length?`<dl>${s.points.map((p,j)=>`<div><dt>${String(j+1).padStart(2,"0")}</dt><dd>${e(p)}</dd></div>`).join("")}</dl>`:""}</article>`).join("")}</section>`}
function docs(page){return `<section class="hh-manual"><aside><div>HOWHOW<br>FIELD<br>MANUAL</div><p>Version: concept</p></aside><article>${(page.sections||[]).map((s,i)=>`<section><span>${String(i+1).padStart(2,"0")}</span><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${s.status?`<mark>${e(s.status)}</mark>`:""}</div>${s.points?.length?`<pre><code>${s.points.map(p=>`→ ${e(p)}`).join("\n")}</code></pre>`:""}</section>`).join("")}</article></section>`}
function availability(page){const sections=page.sections||[];return `<section class="hh-review-pass"><div class="hh-review-pass__ticket"><span>ACCESS TICKET / CONCEPT</span><h2>${e(page.headline||page.title)}</h2><b>${e(sections[0]?.status||"REVIEW REQUIRED")}</b><p>No magic button: access, terms, and availability must be stated before action.</p></div><div>${sections.map((section,index)=>`<article><span>CHECK ${String(index+1).padStart(2,"0")}</span><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.status?`<strong>${e(section.status)}</strong>`:""}</article>`).join("")}</div></section>`}

function content(page,mode){if(mode==="availability")return availability(page);if(mode==="workflow")return workflow(page);if(mode==="ledger")return ledger(page);if(mode==="docs")return docs(page);return editorial(page)}
function footer(product,site){return `<footer class="hh-footer"><div class="hh-footer__marquee" aria-hidden="true">ASK • SOURCE • CHECK • REVIEW • ASK • SOURCE • CHECK • REVIEW •</div><div class="hh-footer__body"><div><span>HOWHOW™</span><h2>Questions in. Inspectable packets out.</h2><p>${e(product.thesis)}</p></div><nav aria-label="Footer">${site.footerGroups.flatMap(g=>g.links).slice(0,14).map(l=>`<a href="${e(l.href)}"${ext(l.href)}>${e(l.label)} ↗</a>`).join("")}</nav></div><div class="hh-footer__base"><span>© <span data-current-year></span> HOWHOW</span><span>A Navin Research project</span></div></footer>`}
function render(product,site,page){const path=normalizePath(page.path),mode=layoutFor(page),home=path==="/",cta=page.cta||site.primaryCta;return `<!doctype html><html lang="en" class="no-js"><head>${headMarkup({product,page,path,layout:mode,isHome:home})}</head><body class="hh-body hh-${mode}" data-product="howhow" data-route="${e(path)}"><a class="skip-link" href="#main-content">Skip to content</a><header class="hh-header"><a class="hh-logo" href="/" aria-label="HowHow home">HOW<br>HOW<span>?</span></a><button class="product-menu-button hh-menu-button" type="button" aria-expanded="false" aria-controls="product-menu" data-product-menu>MENU</button><div class="product-menu hh-menu" id="product-menu"><nav aria-label="Primary navigation">${nav(site,path)}</nav><a class="hh-access" href="${e(site.primaryCta.href)}"${ext(site.primaryCta.href)}>${e(site.primaryCta.label)}</a></div></header><main id="main-content"><section class="hh-hero"><div class="hh-hero__copy"><p>${e(page.eyebrow||"RESEARCH REASONING / PACKET BY PACKET")}</p><h1>${e(page.headline||page.title)}</h1><p>${e(page.lede||page.description)}</p>${home?`<div class="hh-actions"><a href="/how-it-works/">OPEN A PACKET</a><a href="/sources/">FOLLOW THE SOURCES →</a></div>`:""}</div>${packet(page)}</section>${content(page,mode)}${cta?`<section class="hh-cta"><div class="hh-cta__burst">NEXT!</div><div><span>THE PACKET IS NOT THE VERDICT</span><h2>${e(cta.title||"Keep a human at the review stamp")}</h2><p>${e(cta.body||product.availability.body)}</p></div><a href="${e(cta.href)}"${ext(cta.href)}>${e(cta.label)} ↗</a></section>`:""}${home?`<section class="hh-proof"><header><span>INGREDIENTS / EVIDENCE</span><h2>What is actually in the box?</h2></header><div><p>${e(product.proofNote)}</p><ul>${product.evidence.map(item=>`<li><span>${e(item.label)}</span><b>${e(item.value)}</b><small>${e(item.state)}</small></li>`).join("")}</ul></div></section>`:""}</main>${footer(product,site)}</body></html>`}
export default function renderHowHow(product,site,page){return render(product,site,page).replace(/[ \t]+$/gm,"")};export{layoutFor,normalizePath};
