import { escapeHtml, headMarkup } from "../product-renderer-helpers.mjs";
const e = escapeHtml;
const normalizePath = (value = "/") => value === "/404.html" ? value : (`/${String(value).replace(/^\/+|\/+$/g, "")}/`).replace("//", "/");
const external = (href = "") => /^https?:|^mailto:/.test(href) ? ' target="_blank" rel="noopener noreferrer"' : "";
const layoutFor = (page) => page.path === "/404.html" ? "error" : /docs|api|developers/.test(page.path) ? "docs" : /product/.test(page.path) ? "product" : /models|benchmarks|evaluation|edge|devices/.test(page.path) ? "specs" : /research/.test(page.path) ? "timeline" : /privacy|terms/.test(page.path) ? "ledger" : /pricing|contact/.test(page.path) ? "availability" : /solutions|speech|translation|streaming/.test(page.path) ? "workflow" : "editorial";

function navigation(site, path) {
  return site.navigation.map((item) => {
    const href = item.href || item.children?.[0]?.href || "/";
    const active = normalizePath(href) === path || item.children?.some((child) => normalizePath(child.href) === path);
    if (item.children?.length) return `<details class="my-nav-group"${active ? " data-current" : ""}><summary>${e(item.label)}<span>+</span></summary><div>${item.children.map((child) => `<a href="${e(child.href)}"${normalizePath(child.href) === path ? ' aria-current="page"' : ""}${external(child.href)}>${e(child.label)}</a>`).join("")}</div></details>`;
    return `<a href="${e(href)}"${active ? ' aria-current="page"' : ""}${external(href)}>${e(item.label)}</a>`;
  }).join("");
}

function waveform(page) {
  const items = (page.visual?.items || ["Speaker", "Meaning", "Context", "Output"]).slice(0, 6);
  const bars = Array.from({ length: 48 }, (_, index) => `<i class="my-wave__bar my-wave__bar--${index % 8}" aria-hidden="true"></i>`).join("");
  return `<figure class="my-wave"><div class="my-wave__top"><span>LIVE SIGNAL / ILLUSTRATIVE</span><span>00:${String(items.length * 7).padStart(2, "0")}</span></div><div class="my-wave__bars" aria-hidden="true">${bars}</div><ol>${items.map((item, index) => `<li><span>${String(index + 1).padStart(2, "0")}</span>${e(item)}</li>`).join("")}</ol><figcaption>${e(page.visual?.caption || "A conceptual signal path. No benchmark or live latency is implied.")}</figcaption></figure>`;
}

function cards(page) {
  return `<section class="my-cards">${(page.sections || []).map((section, index) => `<article class="my-card my-card--${(index % 4) + 1}"><span>${String(index + 1).padStart(2, "0")}</span><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.status ? `<strong>${e(section.status)}</strong>` : ""}${section.points?.length ? `<ul>${section.points.map((point) => `<li>${e(point)}</li>`).join("")}</ul>` : ""}${section.cta ? `<a href="${e(section.cta.href)}"${external(section.cta.href)}>${e(section.cta.label)} ↗</a>` : ""}</article>`).join("")}</section>`;
}

function apiDocs(page){const sections=page.sections||[];return `<section class="my-docs my-api-contract"><header><span>REQUEST / RECEIPT CONTRACT</span><code>audio + context → stateful result</code></header><div class="my-api-contract__rail"><span>INPUT</span><span>TRANSFORM</span><span>STATE</span><span>REVIEW</span></div>${sections.map((section,index)=>`<article><span>${String(index+1).padStart(2,"0")}</span><div><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.status?`<mark>${e(section.status)}</mark>`:""}</div>${section.points?.length?`<pre><code>${section.points.map(point=>`receipt: ${e(point)}`).join(" | ")}</code></pre>`:""}</article>`).join("")}</section>`}
function developerDocs(page){const sections=page.sections||[];return `<section class="my-docs my-developer-loop"><header><span>INTEGRATE / INSPECT / APPROVE</span><h2>A developer loop with the state exposed.</h2></header><ol>${sections.map((section,index)=>`<li><span>STEP ${String(index+1).padStart(2,"0")}</span><h2>${e(section.title)}</h2><p>${e(section.body)}</p><strong>${e(section.status||"SDK NOT ANNOUNCED")}</strong></li>`).join("")}</ol></section>`}
function documentDocs(page){const sections=page.sections||[];return `<section class="my-docs my-document-stack"><nav aria-label="Documentation contents"><span>READING STACK</span>${sections.map((section,index)=>`<a href="#topic-${index+1}">${String(index+1).padStart(2,"0")} ${e(section.title)}</a>`).join("")}</nav><article>${sections.map((section,index)=>`<section id="topic-${index+1}"><span>${String(index+1).padStart(2,"0")}</span><div><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.status?`<mark>${e(section.status)}</mark>`:""}</div>${section.points?.length?`<ul>${section.points.map(point=>`<li>${e(point)}</li>`).join("")}</ul>`:""}</section>`).join("")}</article></section>`}
function docs(page){const kind=page.visual?.kind;return kind==="api-contract"?apiDocs(page):kind==="developer-loop"?developerDocs(page):documentDocs(page)}

function specs(page) {
  return `<section class="my-lab"><header><span>LANGUAGE LAB</span><p>Claims remain bounded by published project evidence.</p></header>${(page.sections || []).map((section, index) => `<article><div class="my-lab__number">${String(index + 1).padStart(2, "0")}</div><div><h2>${e(section.title)}</h2><p>${e(section.body)}</p></div><div class="my-lab__reading"><span>${e(section.status || "OBSERVATION")}</span>${section.points?.length ? `<ul>${section.points.map((point) => `<li>${e(point)}</li>`).join("")}</ul>` : ""}</div></article>`).join("")}</section>`;
}

function flow(page) {
  return `<section class="my-flow"><div class="my-flow__line" aria-hidden="true"></div>${(page.sections || []).map((section, index) => `<article class="my-flow__step my-flow__step--${index % 6}"><span>STEP ${String(index + 1).padStart(2, "0")}</span><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.points?.length ? `<ol>${section.points.map((point) => `<li>${e(point)}</li>`).join("")}</ol>` : ""}</article>`).join("")}</section>`;
}

function availability(page) {
  const sections = page.sections || [];
  return `<section class="my-offer"><header><span>PUBLIC AVAILABILITY</span><strong>${e(sections[0]?.status || "NOT ANNOUNCED")}</strong></header><div class="my-offer__statement"><p>01 / STATE</p><h2>${e(page.headline || page.title)}</h2><p>No number, tier, or date is inferred where the project has not published one.</p></div><dl>${sections.map((section, index) => `<div><dt>${String(index + 2).padStart(2, "0")} / ${e(section.title)}</dt><dd>${e(section.body)}${section.status ? `<b>${e(section.status)}</b>` : ""}</dd></div>`).join("")}</dl></section>`;
}

function errorPage(page){return `<section class="my-error"><span>404 / SIGNAL NOT FOUND</span><h2>${e(page.headline||page.title||"This signal is not in the catalog.")}</h2><p>${e(page.lede||page.description||"Return to the Moyi index.")}</p><a href="/">Return to Moyi ↗</a></section>`;}
function productFamily(page){return `<section class="my-product-family"><header><span>MODEL FAMILY / PRODUCT</span><p>Speech, context, and deployment boundaries across the Moyi layer.</p></header><div>`+(page.sections||[]).map((x,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><h2>${e(x.title)}</h2><p>${e(x.body)}</p></article>`).join("")+`</div></section>`;}
function legalLedger(page){return `<section class="my-legal-ledger"><header><span>POLICY REGISTER</span><p>Product-specific terms remain pending a released service.</p></header>`+(page.sections||[]).map((x,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><h2>${e(x.title)}</h2><p>${e(x.body)}</p></article>`).join("")+`</section>`;}

function modelMap(page){return `<section class="my-lab my-family-map"><header><span>MODEL FAMILY MAP</span><h2>One family, distinct jobs.</h2></header><ol>${(page.visual?.items||[]).map((item,index)=>`<li><span>${String(index+1).padStart(2,"0")}</span><b>${e(item)}</b><small>SEPARATE EVIDENCE</small></li>`).join("")}</ol><div>${(page.sections||[]).map(s=>`<article><h2>${e(s.title)}</h2><p>${e(s.body)}</p><strong>${e(s.status||"OPEN")}</strong></article>`).join("")}</div></section>`}
function evaluationMatrix(page){return `<section class="my-lab my-evaluation-matrix"><header><span>EVALUATION MATRIX</span><h2>Conditions travel with every observation.</h2></header><div role="table" aria-label="Evaluation protocol fields">${(page.sections||[]).map((s,i)=>`<article role="row"><span>${String(i+1).padStart(2,"0")}</span><div role="cell"><h2>${e(s.title)}</h2><p>${e(s.body)}</p></div><strong role="cell">${e(s.status||"UNKNOWN")}</strong><ul role="cell">${(s.points||[]).map(p=>`<li>${e(p)}</li>`).join("")}</ul></article>`).join("")}</div></section>`}
function evidenceGrid(page){return `<section class="my-lab my-evidence-grid"><header><span>BENCHMARK PROTOCOL / VALUES WITHHELD</span><h2>No score without a named test.</h2></header><div>${(page.sections||[]).map((s,i)=>`<article><span>FIELD ${String(i+1).padStart(2,"0")}</span><h2>${e(s.title)}</h2><p>${e(s.body)}</p><strong>${e(s.status||"RESULT: UNKNOWN")}</strong><div aria-label="No published value">—</div></article>`).join("")}</div></section>`}
function researchNotebook(page){return `<section class="my-lab my-research-notebook"><aside><span>RESEARCH NOTEBOOK</span><h2>Question before finding.</h2><p>No result is inferred from an open research direction.</p></aside><div>${(page.sections||[]).map((s,i)=>`<article><span>NOTE ${String(i+1).padStart(2,"0")}</span><h2>${e(s.title)}</h2><p>${e(s.body)}</p><strong>${e(s.status||"OPEN QUESTION")}</strong></article>`).join("")}</div></section>`}
function signalStudy(page,kind){return `<section class="my-signal-study my-signal-study--${e(kind)}"><header><span>${e(kind.replaceAll("-"," ").toUpperCase())}</span><h2>Keep state, context, and review separate.</h2></header><div class="my-signal-study__instrument" aria-hidden="true"><i></i><i></i><i></i><i></i></div><ol>${(page.sections||[]).map((s,i)=>`<li><span>${String(i+1).padStart(2,"0")}</span><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p></div><strong>${e(s.status||"UNVERIFIED")}</strong></li>`).join("")}</ol></section>`}
function routeLead(page,mode){return `<section class="my-route-lead my-route-lead--${e(mode)}"><div><p>${e(page.eyebrow||"MOYI / LISTENING ROOM")}</p><h1>${e(page.headline||page.title)}</h1></div><p>${e(page.lede||page.description)}</p><span>SIGNAL / ${e(mode.toUpperCase())} / REVIEW</span></section>`}
function pageBody(page, mode) { if (mode === "error") return errorPage(page); if (mode === "product") return productFamily(page); if (mode === "ledger") return legalLedger(page); if (mode === "availability") return availability(page); if (mode === "docs") return docs(page); const kind=page.visual?.kind; if (kind==="model-family"||kind==="family-map") return modelMap(page); if(kind==="evaluation-matrix")return evaluationMatrix(page); if(kind==="evidence-grid")return evidenceGrid(page); if(kind==="research-notebook")return researchNotebook(page); if (/speech/.test(page.path)) return signalStudy(page,"acoustic-field"); if (/translation/.test(page.path)) return signalStudy(page,"translation-loop"); if (/streaming/.test(page.path)) return signalStudy(page,"stream-timeline"); if (/edge/.test(page.path)) return signalStudy(page,"edge-boundary"); if (/devices/.test(page.path)) return signalStudy(page,"device-record"); if (mode === "specs" || mode === "timeline") return specs(page); if (mode === "workflow") return flow(page); return cards(page); }

function footer(product, site) {
  const groups = site.footerGroups;
  return `<footer class="my-footer"><div class="my-footer__voice"><span>MOYI</span><h2>Speech carries more than words.</h2><p>${e(product.thesis)}</p></div><div class="my-footer__links">${groups.map((group) => `<section><h3>${e(group.title)}</h3>${group.links.map((link) => `<a href="${e(link.href)}"${external(link.href)}>${e(link.label)}</a>`).join("")}</section>`).join("")}</div><div class="my-footer__ticker"><span>LANGUAGE</span><span>CONTEXT</span><span>VOICE</span><span>MEANING</span><span>© <span data-current-year></span></span></div></footer>`;
}

function render(product, site, page) {
  const path = normalizePath(page.path); const mode = layoutFor(page); const home = path === "/"; const cta = page.cta || site.primaryCta;
  const lead=home?`<section class="my-hero"><div class="my-hero__copy"><p>${e(page.eyebrow || "VOICE AI / CONTEXT FIRST")}</p><h1>${e(page.headline || page.title)}</h1><div class="my-hero__lede"><span aria-hidden="true">↳</span><p>${e(page.lede || page.description)}</p></div><div class="my-actions"><a href="${e(site.primaryCta.href)}"${external(site.primaryCta.href)}>${e(site.primaryCta.label)}</a><a href="/models/">Explore the model family</a></div></div>${waveform(page)}</section>`:routeLead(page,mode);
  return `<!doctype html><html lang="en" class="no-js"><head>${headMarkup({ product, page, path, layout: mode, isHome: home })}</head><body class="my-body my-${mode}" data-product="moyi" data-route="${e(path)}"><a class="skip-link" href="#main-content">Skip to content</a><header class="my-header"><a class="my-logo" href="/" aria-label="Moyi home">MOYI<i aria-hidden="true"></i></a><button class="product-menu-button my-menu-button" type="button" aria-controls="product-menu" aria-expanded="false" data-product-menu>Menu</button><div class="product-menu my-menu" id="product-menu"><nav aria-label="Primary navigation">${navigation(site, path)}</nav><a class="my-header__cta" href="${e(site.primaryCta.href)}"${external(site.primaryCta.href)}>${e(site.primaryCta.label)}</a></div></header><main id="main-content">${lead}${pageBody(page, mode)}${cta ? `<section class="my-next"><p>WHERE THE SIGNAL GOES NEXT</p><div><h2>${e(cta.title || "Keep the boundary audible")}</h2><p>${e(cta.body || product.availability.body)}</p></div><a href="${e(cta.href)}"${external(cta.href)}>${e(cta.label)} <span>↗</span></a></section>` : ""}${home ? `<section class="my-evidence"><div><p>EVIDENCE / LIMITS</p><h2>Evaluation before exaggeration.</h2><p>${e(product.proofNote)}</p></div><ol>${product.evidence.map((item, index) => `<li><span>${String(index + 1).padStart(2, "0")}</span><b>${e(item.label)}</b><strong>${e(item.value)}</strong><small>${e(item.state)}</small></li>`).join("")}</ol></section>` : ""}</main>${footer(product, site)}</body></html>`;
}
export default function renderMoyi(product, site, page) { return render(product, site, page).replace(/[ \t]+$/gm, ""); }
export { layoutFor, normalizePath };
