import { escapeHtml, headMarkup } from "../product-renderer-helpers.mjs";
const e = escapeHtml;
const normalizePath = (value = "/") => value === "/404.html" ? value : (`/${String(value).replace(/^\/+|\/+$/g, "")}/`).replace("//", "/");
const external = (href = "") => /^https?:|^mailto:/.test(href) ? ' target="_blank" rel="noopener noreferrer"' : "";
const layoutFor = (page) => page.path === "/404.html" ? "error" : /docs/.test(page.path) ? "docs" : /product/.test(page.path) ? "product" : /download|pricing|contact/.test(page.path) ? "availability" : /privacy|security|terms|permissions/.test(page.path) ? "ledger" : /use-cases|voice-|apps|features/.test(page.path) ? "workflow" : /changelog|history/.test(page.path) ? "timeline" : "editorial";

function navigation(site, path) {
  const preferred = ["Product", "Use cases", "Download", "Pricing"];
  const entries = preferred.map((label) => site.navigation.find((item) => item.label === label)).filter(Boolean);
  return entries.map((item) => {
    const href = item.href || item.children?.[0]?.href || "/";
    const active = normalizePath(href) === path || item.children?.some((child) => normalizePath(child.href) === path);
    if (item.children?.length) return `<details class="so-nav-group"${active ? " data-current" : ""}><summary>${e(item.label)} <span>⌄</span></summary><div>${item.children.map((child) => `<a href="${e(child.href)}"${normalizePath(child.href) === path ? ' aria-current="page"' : ""}>${e(child.label)}</a>`).join("")}</div></details>`;
    return `<a href="${e(href)}"${active ? ' aria-current="page"' : ""}>${e(item.label)}</a>`;
  }).join("");
}

function voiceCanvas(page) {
  const snippets = (page.visual?.items || ["Speak", "Review", "Approve", "Send"]).slice(0, 5);
  return `<div class="so-canvas" aria-label="Illustrative Sori editing canvas"><div class="so-canvas__window"><div class="so-canvas__chrome"><i></i><i></i><i></i><span>Desktop insertion canvas / illustrative</span></div><div class="so-canvas__note"><span>TRANSCRIPT UNDER REVIEW</span><p>${e(page.visual?.title || "Your voice stays attached to the action.")}</p><div class="so-editline" aria-hidden="true"><span>Insertion target</span><b></b><kbd>Ctrl ↵ approve</kbd></div></div><ol>${snippets.map((item,index)=>`<li><b>${String(index+1).padStart(2,"0")}</b><span>${e(item)}</span><i>${index===snippets.length-1?"Review":"Ready"}</i></li>`).join("")}</ol></div><p>${e(page.visual?.caption || "Concept UI only. No live model or device behavior is represented.")}</p></div>`;
}

function editorial(page) {
  return `<section class="so-stories">${(page.sections || []).map((section,index)=>`<article class="so-story so-story--${(index%3)+1}"><div class="so-story__number">${String(index+1).padStart(2,"0")}</div><div><p>${e(section.kind || "VOICE PRACTICE")}</p><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.status?`<strong>${e(section.status)}</strong>`:""}</div>${section.points?.length?`<ul>${section.points.map(point=>`<li>${e(point)}</li>`).join("")}</ul>`:""}</article>`).join("")}</section>`;
}
function useCases(page) {
  return `<section class="so-use"><header><span>YOUR VOICE, IN CONTEXT</span><p>Each action remains reviewable before it leaves the canvas.</p></header><div>${(page.sections || []).map((section,index)=>`<article><span>${String(index+1).padStart(2,"0")}</span><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.points?.length?`<ul>${section.points.map(point=>`<li>${e(point)}</li>`).join("")}</ul>`:""}</article>`).join("")}</div></section>`;
}
function boundaries(page) {
  return `<section class="so-boundaries"><div class="so-boundaries__intro"><span>BOUNDARY CENTER</span><h2>Know what leaves the canvas.</h2></div>${(page.sections || []).map((section,index)=>`<details${index===0?" open":""}><summary><span>${String(index+1).padStart(2,"0")}</span>${e(section.title)}<b>+</b></summary><div><p>${e(section.body)}</p>${section.status?`<strong>${e(section.status)}</strong>`:""}${section.points?.length?`<ul>${section.points.map(point=>`<li>${e(point)}</li>`).join("")}</ul>`:""}</div></details>`).join("")}</section>`;
}
function docs(page) {
  return `<section class="so-guide"><header><span>SORI GUIDE</span><h2>Start with the boundary.</h2></header>${(page.sections || []).map((section,index)=>`<article><span>${String(index+1).padStart(2,"0")}</span><div><h2>${e(section.title)}</h2><p>${e(section.body)}</p></div>${section.points?.length?`<ol>${section.points.map(point=>`<li>${e(point)}</li>`).join("")}</ol>`:""}</article>`).join("")}</section>`;
}
function availability(page){const sections=page.sections||[];return `<section class="so-offer"><div class="so-offer__state"><span>PUBLIC STATUS</span><b>${e(sections[0]?.status||"NOT ANNOUNCED")}</b><p>Sori has not published a price, purchase path, or release date on this site.</p></div><div class="so-offer__details">${sections.map((section,index)=>`<article><span>${String(index+1).padStart(2,"0")}</span><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.status?`<strong>${e(section.status)}</strong>`:""}</article>`).join("")}</div></section>`}

function errorPage(page){return `<section class="so-error"><span>404 / ROUTE NOT FOUND</span><h2>${e(page.headline||page.title||"This voice route is unavailable.")}</h2><p>${e(page.lede||page.description||"Return to the Sori studio.")}</p><a href="/">Return to Sori ↗</a></section>`;}
function productStudio(page){return `<section class="so-product-studio"><header><span>STUDIO / PRODUCT MAP</span><p>Profiles, permissions, and voice workflows in one deliberate surface.</p></header>`+(page.sections||[]).map((x,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><h2>${e(x.title)}</h2><p>${e(x.body)}</p></article>`).join("")+`</section>`;}
function content(page, mode){ if(mode==="error")return errorPage(page); if(mode==="product")return productStudio(page); if(mode==="availability") return availability(page); if(mode==="workflow") return useCases(page); if(mode==="ledger") return boundaries(page); if(mode==="docs") return docs(page); return editorial(page); }
function footer(product,site){return `<footer class="so-footer"><div class="so-footer__close"><p>FROM THE FIRST WORD</p><h2>Keep your voice close.</h2><span>${e(product.thesis)}</span></div><div class="so-footer__links">${site.footerGroups.map(group=>`<section><h3>${e(group.title)}</h3>${group.links.map(link=>`<a href="${e(link.href)}"${external(link.href)}>${e(link.label)}</a>`).join("")}</section>`).join("")}</div><div class="so-footer__base"><a href="/">SORI ●</a><span>© <span data-current-year></span> · A Navin Research project</span></div></footer>`}
function render(product,site,page){const path=normalizePath(page.path),mode=layoutFor(page),home=path==="/",cta=page.cta||site.primaryCta;return `<!doctype html><html lang="en" class="no-js"><head>${headMarkup({product,page,path,layout:mode,isHome:home})}</head><body class="so-body so-${mode}" data-product="sori" data-route="${e(path)}"><a class="skip-link" href="#main-content">Skip to content</a><header class="so-header"><a class="so-logo" href="/" aria-label="Sori home"><span>SORI</span><i aria-hidden="true"></i></a><button class="product-menu-button so-menu-button" type="button" aria-expanded="false" aria-controls="product-menu" data-product-menu>Menu</button><div class="product-menu so-menu" id="product-menu"><nav aria-label="Primary navigation">${navigation(site,path)}</nav><a class="so-download" href="/download/">Download <span>↘</span></a></div></header><main id="main-content"><section class="so-hero"><div class="so-hero__copy"><p>${e(page.eyebrow||"VOICE WITH A VISIBLE BOUNDARY")}</p><h1>${e(page.headline||page.title)}</h1><p>${e(page.lede||page.description)}</p>${home?`<div class="so-actions"><a href="/download/">Try the concept</a><a href="/product/">See how Sori works →</a></div>`:""}</div>${(mode === "docs" || mode === "ledger" || path === "/404.html") ? `<figure class="so-signal-note"><span>NO LIVE VOICE SURFACE</span><figcaption>Reference and policy surface. No microphone, model, or insertion behavior is represented.</figcaption></figure>` : voiceCanvas(page)}</section>${content(page,mode)}${cta?`<section class="so-next"><div><span>ONE MORE THING</span><h2>${e(cta.title||"Your voice stays yours")}</h2><p>${e(cta.body||product.availability.body)}</p></div><a href="${e(cta.href)}"${external(cta.href)}>${e(cta.label)} →</a></section>`:""}${home?`<section class="so-proof"><p>TRUST, WITHOUT SMALL PRINT</p><h2>Visible states. Reversible actions.</h2><div><p>${e(product.proofNote)}</p><ul>${product.evidence.map(item=>`<li><span>${e(item.label)}</span><b>${e(item.value)}</b><small>${e(item.state)}</small></li>`).join("")}</ul></div></section>`:""}</main>${footer(product,site)}</body></html>`}
export default function renderSori(product,site,page){return render(product,site,page).replace(/[ \t]+$/gm,"")}
export{layoutFor,normalizePath};
