import { escapeHtml, headMarkup } from "../product-renderer-helpers.mjs";
const e = escapeHtml;
const normalizePath = (value = "/") => value === "/404.html" ? value : (`/${String(value).replace(/^\/+|\/+$/g, "")}/`).replace("//", "/");
const external = (href = "") => /^https?:|^mailto:/.test(href) ? ' target="_blank" rel="noopener noreferrer"' : "";
const layoutFor = (page) => page.path === "/404.html" ? "error" : /docs/.test(page.path) ? "docs" : /product/.test(page.path) ? "product" : /download|pricing|contact/.test(page.path) ? "availability" : /privacy|security|terms|permissions/.test(page.path) ? "ledger" : /use-cases|voice-|apps|features/.test(page.path) ? "workflow" : /changelog|history/.test(page.path) ? "timeline" : "editorial";

function navigation(site, path) {
  return site.navigation.map((item) => {
    const href=item.href||item.children?.[0]?.href||"/";
    const active=normalizePath(href)===path||item.children?.some(child=>normalizePath(child.href)===path);
    if(item.children?.length)return `<details class="so-nav-group"${active?" data-current":""}><summary>${e(item.label)} <span>⌄</span></summary><div><a href="${e(href)}"${normalizePath(href)===path?' aria-current="page"':""}>Overview</a>${item.children.map(child=>`<a href="${e(child.href)}"${normalizePath(child.href)===path?' aria-current="page"':""}>${e(child.label)}</a>`).join("")}</div></details>`;
    return `<a href="${e(href)}"${active?' aria-current="page"':""}>${e(item.label)}</a>`;
  }).join("");
}

function voiceCanvas(page) {
  const snippets = (page.visual?.items || ["Speak", "Review", "Approve", "Send"]).slice(0, 5);
  return `<div class="so-canvas" aria-label="Illustrative Sori editing canvas"><div class="so-canvas__window"><div class="so-canvas__chrome"><i></i><i></i><i></i><span>Desktop insertion canvas / illustrative</span></div><div class="so-canvas__note"><span>TRANSCRIPT UNDER REVIEW</span><p>${e(page.visual?.title || "Your voice stays attached to the action.")}</p><div class="so-editline" aria-hidden="true"><span>Insertion target</span><b></b><kbd>Ctrl ↵ approve</kbd></div></div><ol>${snippets.map((item,index)=>`<li><b>${String(index+1).padStart(2,"0")}</b><span>${e(item)}</span><i>${index===snippets.length-1?"Review":"Ready"}</i></li>`).join("")}</ol></div><p>${e(page.visual?.caption || "Concept UI only. No live model or device behavior is represented.")}</p></div>`;
}

function editorial(page) {
  return `<section class="so-stories">${(page.sections || []).map((section,index)=>`<article class="so-story so-story--${(index%3)+1}"><div class="so-story__number">${String(index+1).padStart(2,"0")}</div><div><p>${e(section.kind || "VOICE PRACTICE")}</p><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.status?`<strong>${e(section.status)}</strong>`:""}</div>${section.points?.length?`<ul>${section.points.map(point=>`<li>${e(point)}</li>`).join("")}</ul>`:""}</article>`).join("")}</section>`;
}
function errorPage(page){return `<section class="so-error"><span>404 / ROUTE NOT FOUND</span><h2>${e(page.headline||page.title||"This voice route is unavailable.")}</h2><p>${e(page.lede||page.description||"Return to the Sori studio.")}</p><a href="/">Return to Sori ↗</a></section>`;}
function visualPanel(page,label="CONCEPT INSTRUMENT"){const items=(page.visual?.items||[]).slice(0,6);return `<figure class="so-route-visual so-route-visual--${e(page.visual?.kind||"index")}"><header><span>${e(label)}</span><strong>${e(page.visual?.title||page.title)}</strong></header>${page.visual?.src?`<img src="${e(page.visual.src)}" alt="${e(page.visual.alt||"")}" width="1200" height="760">`:""}<ol>${items.map((item,i)=>`<li><span>${String(i+1).padStart(2,"0")}</span><b>${e(item)}</b><small>${i===items.length-1?"HUMAN CHECK":"VISIBLE STATE"}</small></li>`).join("")}</ol><figcaption>${e(page.visual?.caption||"Concept interface only. No physical behavior or availability is implied.")}</figcaption></figure>`}
function productStudio(page){return `<section class="so-product-studio"><header><span>STUDIO / PRODUCT MAP</span><p>Profiles, permissions, and voice workflows in one deliberate surface.</p></header><div class="so-product-studio__grid"><div>${(page.sections||[]).map((x,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><h2>${e(x.title)}</h2><p>${e(x.body)}</p></article>`).join("")}</div>${visualPanel(page,"HOT PATH / UNVERIFIED")}</div></section>`;}
function studio(page){return `<section class="so-stories so-studio"><header><span>STUDIO CONTROL ROOM</span><h2>Advanced surfaces stay behind the daily gesture.</h2></header><div class="so-studio__desk">${visualPanel(page,"CONTROL SURFACE / CONCEPT")}${(page.sections||[]).map((s,i)=>`<article><span>PANEL ${String(i+1).padStart(2,"0")}</span><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${s.points?.length?`<ul>${s.points.map(p=>`<li>${e(p)}</li>`).join("")}</ul>`:""}</article>`).join("")}</div></section>`}
function workflowSurface(page){const kind=page.visual?.kind||"workflow";return `<section class="so-use so-work-surface so-work-surface--${e(kind)}"><header><span>${/use-cases/.test(page.path)?"DESK STUDY":"VOICE PRIMITIVE"}</span><p>${e(page.visual?.caption||"Direction only; physical delivery remains unverified.")}</p></header><div class="so-work-surface__layout">${visualPanel(page,/use-cases/.test(page.path)?"WORK CONTEXT":"REVIEWABLE PATH")}<ol>${(page.sections||[]).map((s,i)=>`<li><span>${String(i+1).padStart(2,"0")}</span><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p></div>${s.points?.length?`<ul>${s.points.map(p=>`<li>${e(p)}</li>`).join("")}</ul>`:""}</li>`).join("")}</ol></div></section>`}
function trustRegister(page){const permissions=/permissions/.test(page.path);return `<section class="so-boundaries so-trust-register${permissions?" so-trust-register--approval":""}"><header><span>${permissions?"PERMISSION GATE":"TRUST REGISTER"}</span><h2>${permissions?"Request, review, allow.":"Policy belongs to the actual data path."}</h2></header><div>${(page.sections||[]).map((s,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p></div><strong>${e(s.status||"NOT CLAIMED")}</strong>${s.points?.length?`<ul>${s.points.map(p=>`<li>${e(p)}</li>`).join("")}</ul>`:""}</article>`).join("")}</div></section>`}
function docs(page){return `<section class="so-guide"><header><span>SORI FIELD GUIDE</span><p>Source description, local test, browser behavior, and physical proof remain separate receipts.</p></header>${(page.sections||[]).map((section,index)=>`<article><span>${String(index+1).padStart(2,"0")}</span><div><h2>${e(section.title)}</h2><p>${e(section.body)}</p></div>${section.points?.length?`<ol>${section.points.map(point=>`<li>${e(point)}</li>`).join("")}</ol>`:""}</article>`).join("")}</section>`}
function availability(page){const sections=page.sections||[],kind=/pricing/.test(page.path)?"pricing":/contact/.test(page.path)?"contact":"download";return `<section class="so-offer so-offer--${kind}"><div class="so-offer__state"><span>${kind==="contact"?"HUMAN INTAKE":"PUBLIC STATUS"}</span><b>${e(sections[0]?.status||(/pricing/.test(page.path)?"NOT ANNOUNCED":"BETA INTEREST ONLY"))}</b><p>${kind==="contact"?"Contact is a question path, not an access queue.":"No price, purchase path, installer, or release date is published here."}</p></div><div class="so-offer__details">${sections.map((section,index)=>`<article><span>${String(index+1).padStart(2,"0")}</span><h2>${e(section.title)}</h2><p>${e(section.body)}</p>${section.status?`<strong>${e(section.status)}</strong>`:""}${section.points?.length?`<ul>${section.points.map(p=>`<li>${e(p)}</li>`).join("")}</ul>`:""}</article>`).join("")}</div></section>`}
function history(page){return `<section class="so-history"><header><span>CHANGE RECORD</span><h2>States, not release theatre.</h2></header><ol>${(page.sections||[]).map((s,i)=>`<li><time>${String(i+1).padStart(2,"0")}</time><div><h2>${e(s.title)}</h2><p>${e(s.body)}</p></div><strong>${e(s.status||"RECORDED")}</strong></li>`).join("")}</ol></section>`}
function routeLead(page,mode){const rails=mode==="docs"?["SOURCE","RUNTIME","CAPABILITY","OPEN QUESTION"]:mode==="ledger"?["SCOPE","DATA PATH","CONTROL","UNKNOWN"]:mode==="availability"?["ACCESS","PACKAGE","PRICE","SUPPORT"]:mode==="timeline"?["CHANGE","SOURCE","STATE","DATE"]:(page.visual?.items||["CONTEXT","PROPOSAL","REVIEW","ACTION"]).slice(0,4);return `<section class="so-route-lead so-route-lead--${e(mode)}"><div><p>${e(page.eyebrow||"SORI / DESKTOP INSTRUMENT")}</p><h1>${e(page.headline||page.title)}</h1></div><p>${e(page.lede||page.description)}</p>${mode==="error"?"":`<ol>${rails.map(item=>`<li>${e(item)}</li>`).join("")}</ol>`}</section>`}
function content(page,mode){if(mode==="error")return errorPage(page);if(mode==="product")return productStudio(page);if(mode==="availability")return availability(page);if(mode==="workflow")return workflowSurface(page);if(mode==="ledger")return trustRegister(page);if(mode==="docs")return docs(page);if(mode==="timeline")return history(page);if(/studio|models|profiles/.test(page.path))return studio(page);return editorial(page)}
function footer(product,site){return `<footer class="so-footer"><div class="so-footer__close"><p>FROM THE FIRST WORD</p><h2>Keep your voice close.</h2><span>${e(product.thesis)}</span></div><div class="so-footer__links">${site.footerGroups.map(group=>`<section><h3>${e(group.title)}</h3>${group.links.map(link=>`<a href="${e(link.href)}"${external(link.href)}>${e(link.label)}</a>`).join("")}</section>`).join("")}</div><div class="so-footer__base"><a href="/">SORI ●</a><span>© <span data-current-year></span> · A Navin Research project</span></div></footer>`}
function render(product,site,page){const path=normalizePath(page.path),mode=layoutFor(page),home=path==="/",cta=mode==="error"?null:(page.cta||site.primaryCta);const lead=home?`<section class="so-hero"><div class="so-hero__copy"><p>${e(page.eyebrow||"VOICE WITH A VISIBLE BOUNDARY")}</p><h1>${e(page.headline||page.title)}</h1><p>${e(page.lede||page.description)}</p><div class="so-actions"><a href="/download/">Try the concept</a><a href="/product/">See how Sori works →</a></div></div>${voiceCanvas(page)}</section>`:routeLead(page,mode);return `<!doctype html><html lang="en" class="no-js"><head>${headMarkup({product,page,path,layout:mode,isHome:home})}</head><body class="so-body so-${mode}" data-product="sori" data-route="${e(path)}"><a class="skip-link" href="#main-content">Skip to content</a><header class="so-header"><a class="so-logo" href="/" aria-label="Sori home"><span>SORI</span><i aria-hidden="true"></i></a><button class="product-menu-button so-menu-button" type="button" aria-expanded="false" aria-controls="product-menu" data-product-menu>Menu</button><div class="product-menu so-menu" id="product-menu"><nav aria-label="Primary navigation">${navigation(site,path)}</nav><a class="so-download" href="/download/">Access status <span>↘</span></a></div></header><main id="main-content">${lead}${content(page,mode)}${cta?`<section class="so-next"><div><span>ONE MORE THING</span><h2>${e(cta.title||"Your voice stays yours")}</h2><p>${e(cta.body||product.availability.body)}</p></div><a href="${e(cta.href)}"${external(cta.href)}>${e(cta.label)} →</a></section>`:""}${home?`<section class="so-proof"><p>TRUST, WITHOUT SMALL PRINT</p><h2>Visible states. Reversible actions.</h2><div><p>${e(product.proofNote)}</p><ul>${product.evidence.map(item=>`<li><span>${e(item.label)}</span><b>${e(item.value)}</b><small>${e(item.state)}</small></li>`).join("")}</ul></div></section>`:""}</main>${footer(product,site)}</body></html>`}
export default function renderSori(product,site,page){return render(product,site,page).replace(/[ \t]+$/gm,"")}
export{layoutFor,normalizePath};
