export const blogSources = {
  openaiAgents: ["OpenAI, New tools for building agents", "https://openai.com/index/new-tools-for-building-agents/"],
  openaiResponses: ["OpenAI, Responses API reference", "https://platform.openai.com/docs/api-reference/responses"],
  openaiTools: ["OpenAI, Tools guide", "https://platform.openai.com/docs/guides/tools"],
  openaiFunctions: ["OpenAI, Function calling guide", "https://platform.openai.com/docs/guides/function-calling"],
  openaiStructured: ["OpenAI, Structured outputs guide", "https://platform.openai.com/docs/guides/structured-outputs"],
  openaiEvals: ["OpenAI, Evaluations guide", "https://platform.openai.com/docs/guides/evals"],
  openaiSafety: ["OpenAI, Safety best practices", "https://platform.openai.com/docs/guides/safety-best-practices"],
  openaiLatency: ["OpenAI, Latency optimization guide", "https://platform.openai.com/docs/guides/latency-optimization"],
  anthropicAgents: ["Anthropic, Building effective agents", "https://www.anthropic.com/engineering/building-effective-agents"],
  anthropicMulti: ["Anthropic, How we built our multi-agent research system", "https://www.anthropic.com/engineering/multi-agent-research-system"],
  anthropicContext: ["Anthropic, Effective context engineering for AI agents", "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents"],
  anthropicTools: ["Anthropic, Writing effective tools for agents", "https://www.anthropic.com/engineering/writing-tools-for-agents"],
  anthropicEvals: ["Anthropic, Demystifying evals for AI agents", "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents"],
  anthropicThinking: ["Anthropic, Extended thinking guide", "https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking"],
  mcp: ["Model Context Protocol, Introduction", "https://modelcontextprotocol.io/docs/getting-started/intro"],
  mcpSecurity: ["Model Context Protocol, Security best practices", "https://modelcontextprotocol.io/specification/draft/basic/security_best_practices"],
  a2a: ["Agent2Agent Protocol documentation", "https://a2a-protocol.org/latest/"],
  geminiFunctions: ["Google, Gemini API function calling", "https://ai.google.dev/gemini-api/docs/function-calling"],
  geminiStructured: ["Google, Gemini API structured output", "https://ai.google.dev/gemini-api/docs/structured-output"],
  geminiCaching: ["Google, Gemini API context caching", "https://ai.google.dev/gemini-api/docs/caching"],
  geminiLong: ["Google, Gemini API long context", "https://ai.google.dev/gemini-api/docs/long-context"],
  geminiImage: ["Google, Gemini image understanding", "https://ai.google.dev/gemini-api/docs/image-understanding"],
  geminiAudio: ["Google, Gemini audio understanding", "https://ai.google.dev/gemini-api/docs/audio"],
  geminiVideo: ["Google, Gemini video understanding", "https://ai.google.dev/gemini-api/docs/video-understanding"],
  geminiLive: ["Google, Gemini Live API", "https://ai.google.dev/gemini-api/docs/live"],
  deepseekFunctions: ["DeepSeek, Function calling guide", "https://api-docs.deepseek.com/guides/function_calling"],
  deepseekModels: ["DeepSeek, Models and pricing", "https://api-docs.deepseek.com/quick_start/pricing"],
  deepseekTransparency: ["DeepSeek, Transparency Center", "https://www.deepseek.com/en/transparency/"],
  kimi: ["Moonshot AI, Kimi K2 repository and model documentation", "https://github.com/MoonshotAI/Kimi-K2"],
  qwen: ["Qwen Team, Qwen documentation", "https://qwen.readthedocs.io/en/latest/"],
  llama: ["Meta, Llama documentation", "https://www.llama.com/docs/"],
  mistralFunctions: ["Mistral AI, Function calling", "https://docs.mistral.ai/capabilities/function_calling/"],
  mistralModels: ["Mistral AI, Models overview", "https://docs.mistral.ai/getting-started/models/models_overview/"],
  nvidiaServing: ["NVIDIA, TensorRT-LLM documentation", "https://nvidia.github.io/TensorRT-LLM/"],
  nvidiaDynamo: ["NVIDIA, Dynamo documentation", "https://docs.nvidia.com/dynamo/latest/"],
};

const p = (category, slug, title, description, answer, steps, checks, pitfalls, sources, keywords) => ({ category, slug, title, description, answer, steps, checks, pitfalls, sources, keywords });

export const blogPosts = [
  p("agents", "single-agent-before-multi-agent", "Start With One AI Agent Before Building a Multi-Agent System", "A practical decision rule for choosing one agent, a workflow, or several collaborating agents.", "Use one agent until evaluation data shows that context size, tool ownership, or parallel work is the actual bottleneck. Multiple agents add coordination, latency, cost, and new failure modes; they are an architecture choice, not an automatic quality upgrade.", ["Write one measurable task contract with inputs, allowed actions, and a stop condition.", "Build a deterministic workflow around one model and the smallest useful tool set.", "Collect failures by type: missing knowledge, bad tool choice, context overload, or independent subtasks.", "Split roles only when a recorded failure maps clearly to separation or parallelism."], ["Compare task success, p95 latency, and token cost against the single-agent baseline.", "Verify that every handoff has a schema and an owner.", "Keep a fallback path that can finish or safely stop when one specialist fails."], ["Creating personas without distinct tools or information.", "Letting agents converse without a turn or budget limit.", "Judging an architecture from a polished demo instead of repeated tasks."], ["anthropicAgents", "openaiAgents"], ["single agent", "multi-agent system", "AI agent architecture"]),
  p("agents", "multi-agent-orchestration-patterns", "Multi-Agent Orchestration Patterns That Work in Production", "Choose among manager-worker, parallel fan-out, handoff, and evaluator loops without building an uncontrolled agent swarm.", "Prefer explicit orchestration. A manager-worker pattern suits decomposable tasks, parallel fan-out suits independent research, handoffs suit distinct permissions, and evaluator loops suit outputs that can be checked. Each pattern needs bounded turns and a typed result.", ["Classify the task as sequential, parallel, specialist-routed, or iteratively verifiable.", "Define the state passed between agents; pass artifacts and decisions, not entire transcripts by default.", "Set per-agent time, tool, and token budgets.", "Merge results with deterministic code before asking a model to resolve only genuine conflicts."], ["Replay the same task and inspect variance in routing and final quality.", "Inject a failed worker and confirm graceful degradation.", "Trace who produced each claim and which tool evidence supports it."], ["All-to-all chat topologies.", "A reviewer that merely restates the draft.", "No global cancellation or deadline propagation."], ["anthropicMulti", "openaiAgents"], ["multi-agent orchestration", "manager worker agents", "agent handoffs"]),
  p("agents", "agent-handoffs", "How to Design Reliable Handoffs Between AI Agents", "Use typed handoff packets, acceptance checks, and clear responsibility boundaries between specialist agents.", "A reliable handoff is a contract, not a conversational suggestion. Include the objective, relevant state, evidence, constraints, unresolved questions, and an explicit acceptance condition. The receiving agent should be able to reject malformed work.", ["Create a versioned handoff schema with required and optional fields.", "Summarize decisions separately from observations and raw evidence.", "Validate the packet before routing it to the next agent.", "Record acceptance, rejection, or escalation as a trace event."], ["Test missing fields and incompatible schema versions.", "Confirm secrets and unnecessary personal data are excluded.", "Require source links or tool-result identifiers for factual claims."], ["Passing a huge transcript as state.", "Allowing two agents to believe they own the same side effect.", "Treating a handoff as successful before the receiver validates it."], ["openaiAgents", "anthropicContext"], ["AI agent handoff", "agent routing", "typed agent state"]),
  p("agents", "agent-tool-design", "Design Better Tools for AI Agents", "Make agent tools easier to select, call, validate, and recover from with narrow schemas and actionable errors.", "Design tools around user intentions rather than low-level API endpoints. A good tool has a distinct name, a concise description, a strict input schema, a small response, and errors that tell the agent what can be corrected.", ["Start from real tasks and list the minimum operations needed to complete them.", "Use enums, required fields, examples, and server-side validation.", "Return stable identifiers and compact summaries; store large payloads outside model context.", "Separate read operations from writes and mark consequential actions clearly."], ["Measure tool-selection accuracy with confusing neighboring tools.", "Fuzz invalid arguments and ensure no side effect occurs.", "Confirm retries are idempotent or carry an idempotency key."], ["Exposing every backend endpoint as a tool.", "Descriptions that differ only by one vague verb.", "Returning unbounded logs or documents into context."], ["anthropicTools", "openaiFunctions"], ["AI agent tool design", "function calling schema", "tool use reliability"]),
  p("agents", "agent-memory", "AI Agent Memory: What to Store and What to Recompute", "Separate working context, durable user facts, episodic history, and external knowledge to reduce cost and privacy risk.", "Treat memory as several stores with different lifetimes. Keep task-local state in working context, verified preferences in a durable profile, reusable facts in a governed knowledge store, and execution traces in observability storage. Do not call an unfiltered transcript memory.", ["Define a purpose, retention period, and deletion path for each memory class.", "Write only facts supported by user confirmation or trusted system events.", "Retrieve by task relevance and recency, then cap the amount inserted into context.", "Allow users and operators to inspect and correct durable memory."], ["Test whether stale facts are superseded correctly.", "Measure retrieval precision, not only recall.", "Verify tenant isolation and deletion across backups and indexes."], ["Saving every message forever.", "Letting model-generated guesses become durable facts.", "Mixing audit logs with prompt-ready memory."], ["anthropicContext", "openaiResponses"], ["AI agent memory", "long-term memory LLM", "context engineering"]),
  p("agents", "mcp-server-security", "Secure an MCP Server Before Connecting AI Agents", "A deployment checklist for authentication, authorization, consent, validation, and least-privilege Model Context Protocol tools.", "Treat an MCP server as a security boundary. Authenticate clients, authorize every operation, validate all arguments, minimize tool scope, protect tokens, and require user confirmation for consequential actions. A trusted model does not make an untrusted tool safe.", ["Threat-model the server, upstream APIs, client, and transport separately.", "Issue short-lived credentials with the narrowest scopes and bind them to the intended audience.", "Validate redirect URIs and prevent token passthrough to downstream systems.", "Log security events without storing prompts, secrets, or sensitive tool results unnecessarily."], ["Attempt cross-tenant access and confused-deputy flows.", "Test prompt-injected arguments against server-side authorization.", "Confirm revoked credentials fail immediately or within the documented window."], ["Using one administrator token for all users.", "Relying on natural-language instructions as access control.", "Automatically approving writes because they originated from an agent."], ["mcp", "mcpSecurity"], ["MCP server security", "Model Context Protocol", "AI agent authorization"]),
  p("agents", "a2a-and-mcp", "A2A vs MCP: Different Layers for Agent Systems", "Understand when Agent2Agent and Model Context Protocol complement each other instead of competing.", "Use MCP to expose tools, resources, and prompts to an AI application. Use A2A when independently operated agents need to advertise capabilities, exchange task state, and collaborate. A system may use A2A between agents while each agent uses MCP for its local tools.", ["Draw the trust boundaries and ownership of every agent and tool server.", "Use the protocol that matches the boundary instead of wrapping everything in one abstraction.", "Translate only the minimum task state between A2A and local execution.", "Apply authentication and authorization independently at both layers."], ["Trace one task from remote delegation through local tool calls.", "Test capability discovery with unsupported versions.", "Verify that cancellation and errors propagate across both layers."], ["Calling MCP an agent-to-agent messaging protocol.", "Exposing internal tools directly to remote peers.", "Assuming protocol compatibility creates shared authorization."], ["a2a", "mcp"], ["A2A vs MCP", "Agent2Agent protocol", "Model Context Protocol"]),
  p("agents", "human-approval-gates", "Human Approval Gates for High-Risk AI Agent Actions", "Place approval at the last responsible moment and show people exactly what the agent intends to do.", "Require approval for irreversible, externally visible, expensive, or privilege-changing actions. Generate a preview from validated structured arguments, freeze those arguments while approval is pending, and execute exactly the approved operation.", ["Classify tools by risk and define policy outside the prompt.", "Show target, scope, cost, data exposure, and rollback options in the approval view.", "Bind approval to a hash of the normalized request.", "Expire approvals and require re-approval after any material change."], ["Change an argument after preview and ensure execution is blocked.", "Test cancellation, timeout, and duplicate-submit behavior.", "Audit who approved what without recording excess sensitive content."], ["A generic 'Are you sure?' dialog.", "Approval before the agent has concrete arguments.", "Letting the model decide whether its own action requires review."], ["openaiSafety", "mcpSecurity"], ["human in the loop AI", "agent approval gate", "safe AI actions"]),
  p("agents", "long-running-agent-jobs", "Build Long-Running AI Agent Jobs That Can Resume Safely", "Use checkpoints, idempotent tools, bounded retries, and cancellation for tasks that outlive one request.", "Persist explicit workflow state after meaningful steps instead of relying on a live model session. Each resumable step should have an idempotency key, recorded inputs, result status, and a clear rule for retry or human escalation.", ["Represent the job as a state machine with terminal and recoverable states.", "Checkpoint tool outputs and decisions, excluding hidden reasoning.", "Propagate deadlines and cancellation to workers and external calls.", "Resume from the last verified state using current credentials and policy."], ["Kill the worker between every pair of steps and resume.", "Replay callbacks and confirm side effects are not duplicated.", "Verify expired permissions stop the resumed job safely."], ["Keeping progress only in conversation history.", "Unlimited automatic retries.", "Marking a timeout as success because partial prose exists."], ["openaiResponses", "anthropicAgents"], ["long-running AI agents", "resumable agent workflow", "idempotent tool calls"]),
  p("agents", "agent-observability", "AI Agent Observability: Traces That Help Debug Failures", "Capture decisions, tool calls, latency, cost, and evidence without turning traces into a privacy liability.", "Trace the observable workflow: model request identifiers, selected tools, validated arguments, redacted results, state transitions, policy decisions, cost, and timing. Do not depend on hidden chain-of-thought; inspect outcomes and available summaries instead.", ["Assign one trace ID across orchestration, model calls, and tools.", "Record structured events with schema versions and redaction at ingestion.", "Link final claims to retrieved evidence or tool outputs.", "Sample routine success while retaining policy violations and failures under controlled access."], ["Reconstruct a failed task using only retained trace data.", "Check that secrets and personal data are removed before storage.", "Alert on loops, repeated tool errors, and unusual cost or latency."], ["Logging complete prompts by default.", "Metrics without task-level success labels.", "A dashboard that cannot connect a final error to its upstream call."], ["openaiAgents", "anthropicEvals"], ["AI agent observability", "agent tracing", "LLM monitoring"]),

  p("reasoning", "reasoning-models-vs-chat-models", "Reasoning Models vs Chat Models: A Practical Selection Guide", "Choose the least expensive model behavior that reliably solves the task instead of enabling heavy reasoning everywhere.", "Use deeper reasoning for tasks with verifiable multi-step dependencies, difficult planning, or complex tool use. Use fast general models for extraction, rewriting, routing, and straightforward questions. Route with evaluation data rather than intuition.", ["Create representative task buckets and define a correctness check for each.", "Benchmark a fast baseline and a reasoning configuration at multiple effort levels.", "Compare success, latency, and total cost including retries.", "Route only the buckets with a proven quality gain."], ["Repeat tests to measure variance.", "Include malformed and ambiguous inputs.", "Re-run after model or prompt changes because routing assumptions can age."], ["Using reasoning effort as a synonym for quality.", "Evaluating only hard showcase problems.", "Asking for hidden reasoning instead of checking the answer and evidence."], ["openaiEvals", "anthropicThinking"], ["reasoning models", "reasoning effort", "AI model selection"]),
  p("reasoning", "reasoning-effort-routing", "Route Reasoning Effort by Task Difficulty", "Build a simple difficulty router with escalation based on confidence and verification rather than one expensive default.", "Start low and escalate when a deterministic verifier fails, required evidence is absent, or the task belongs to a benchmarked hard class. The router should use observable features and never treat self-reported confidence as proof.", ["Extract routing features such as tool count, constraint count, input length, and verifier availability.", "Choose effort tiers from measured task performance.", "Run the cheapest tier first when verification is inexpensive.", "Escalate with the original evidence and failure reason, not an ever-growing transcript."], ["Measure false escalations and missed hard tasks.", "Cap attempts and total spend.", "Log router version so regressions can be attributed."], ["Routing from prompt length alone.", "Trusting a confidence sentence generated by the same model.", "Retrying identical inputs without new information or changed settings."], ["openaiEvals", "anthropicThinking"], ["reasoning effort routing", "adaptive inference", "LLM cost optimization"]),
  p("reasoning", "verify-reasoning-results", "Verify AI Reasoning Without Requesting Chain-of-Thought", "Check final answers with tests, constraints, citations, and independent computation instead of collecting private reasoning traces.", "Verification should target observable claims. Use unit tests for code, calculators for arithmetic, schema and invariant checks for data, source inspection for factual answers, and independent judges only where deterministic checks are unavailable.", ["Convert the task requirements into executable or inspectable checks.", "Ask the model for a concise answer, assumptions, and evidence - not hidden reasoning.", "Run deterministic checks before any model-based evaluator.", "Return precise failure feedback for one bounded correction pass."], ["Seed known wrong answers and confirm the verifier catches them.", "Check both false acceptance and false rejection.", "Keep evaluator inputs independent from irrelevant authoring context."], ["Treating fluent explanations as correctness.", "Using the same prompt and model as both author and sole judge.", "Publishing citations without checking that they support the claim."], ["openaiEvals", "anthropicEvals"], ["verify AI reasoning", "LLM answer verification", "chain of thought privacy"]),
  p("reasoning", "structured-outputs", "Structured Outputs for Reliable AI Pipelines", "Use JSON Schema for machine-consumed responses while preserving server-side validation and business rules.", "Structured output constrains syntax, not truth. Define the smallest schema your application needs, reject unknown fields where supported, validate again on your server, and apply domain rules before side effects.", ["Version the schema and keep field descriptions unambiguous.", "Use enums and discriminated variants instead of free-form status strings.", "Parse and validate before data reaches queues, databases, or tools.", "Handle refusal, truncation, and unsupported-schema cases explicitly."], ["Generate boundary values, missing fields, and extra fields.", "Test semantically invalid but schema-valid data.", "Measure parse success separately from task correctness."], ["A giant schema that mirrors the entire database.", "Assuming valid JSON is valid business data.", "Silently coercing types or inventing missing values."], ["openaiStructured", "geminiStructured"], ["structured outputs", "JSON schema LLM", "reliable AI pipeline"]),
  p("reasoning", "reasoning-with-tools", "Reasoning With Tools: Separate Planning From Execution", "Let models choose actions while deterministic code validates, executes, and records each operation.", "The model may propose a plan and tool calls, but the application owns permissions, validation, execution, retry policy, and stopping. This separation keeps failures inspectable and prevents natural language from bypassing control logic.", ["Expose a narrow set of task-relevant tools.", "Validate each call against schema, user scope, and current state.", "Return concise results with stable identifiers and explicit error types.", "Stop on success, budget exhaustion, policy denial, or repeated non-progress."], ["Simulate stale state between planning and execution.", "Test partial tool failure and duplicate requests.", "Confirm the agent cannot manufacture a tool result in plain text."], ["Executing a prose plan as code.", "Returning stack traces or secrets to the model.", "Allowing endless plan-revise loops."], ["openaiFunctions", "geminiFunctions", "anthropicTools"], ["reasoning with tools", "AI tool calling", "agent execution loop"]),
  p("reasoning", "long-context-is-not-memory", "Long Context Is Not the Same as Memory", "Use large context windows deliberately; retrieval, summaries, and durable state still matter.", "A larger context window can hold more tokens, but it does not guarantee that every detail is used correctly or remain affordable. Keep authoritative state structured, retrieve relevant evidence, place instructions clearly, and evaluate performance at realistic context lengths.", ["Separate instructions, current task state, retrieved evidence, and history.", "Remove duplicate and obsolete content before each call.", "Use retrieval metadata so evidence can be traced to its source.", "Benchmark with distractors and facts placed at different positions."], ["Measure answer support and retrieval precision.", "Track input-token cost and cache hits.", "Test whether a compact curated context beats the full transcript."], ["Appending every prior turn forever.", "Using summaries as if they were authoritative records.", "Assuming advertised capacity equals reliable recall."], ["geminiLong", "anthropicContext"], ["long context LLM", "AI memory", "context engineering"]),
  p("reasoning", "context-engineering-checklist", "A Context Engineering Checklist for AI Agents", "Curate instructions, tools, evidence, state, and history as a limited resource on every model turn.", "Build context from explicit layers: stable policy, task contract, current state, relevant tools, retrieved evidence, and a compact recent history. Give each layer an owner and a removal rule. More context is useful only when it changes the correct next action.", ["Reserve the beginning for stable high-priority instructions.", "Select tools on demand and avoid loading large catalogs blindly.", "Retrieve evidence with provenance and a relevance threshold.", "Compact completed work into decisions, artifacts, and open questions."], ["Ablate each context layer and measure task impact.", "Detect conflicting instructions before sending the request.", "Track tokens by layer to identify growth."], ["Mixing untrusted documents with system instructions.", "Keeping stale tool definitions.", "Summarizing away constraints or unresolved risks."], ["anthropicContext", "geminiCaching"], ["context engineering checklist", "AI agent context", "prompt context management"]),
  p("reasoning", "reasoning-evaluation-dataset", "Build a Small Reasoning Evaluation Dataset That Matters", "Create a compact, versioned eval set from real failures before chasing broad benchmark scores.", "Begin with 30-100 representative cases tied to actual user value. Include normal, boundary, ambiguous, and adversarial inputs. Store expected properties and graders, not only one brittle reference sentence.", ["Sample production-like tasks after removing sensitive data.", "Label task type, difficulty, required evidence, and failure severity.", "Use deterministic graders wherever possible and rubric graders for subjective qualities.", "Freeze a regression set while rotating a private holdout set."], ["Review grader disagreement manually.", "Track pass rate by task slice, not only one average.", "Run the baseline and candidate under identical settings."], ["Writing evals from model capabilities instead of user tasks.", "Leaking all test cases into prompts or examples.", "Changing prompts, models, and graders simultaneously."], ["openaiEvals", "anthropicEvals"], ["reasoning evaluation dataset", "LLM evals", "AI regression testing"]),

  p("models", "choose-ai-model", "How to Choose an AI Model for a Production Application", "Evaluate quality, latency, cost, context, tool use, deployment, and governance with your own workload.", "Choose from a task-specific scorecard, not a universal leaderboard. First eliminate models that fail mandatory privacy, deployment, modality, or tool requirements. Then compare end-to-end task success, p95 latency, and total cost on representative traffic.", ["Write hard constraints and quality thresholds before testing.", "Use the same prompts, tools, retrieval data, and retry budget for candidates.", "Measure the full pipeline rather than isolated model calls.", "Plan a fallback and a repeatable model-upgrade process."], ["Include peak load and rate-limit behavior.", "Test refusals, malformed inputs, and long contexts.", "Record exact model identifiers and evaluation dates."], ["Picking the highest benchmark average.", "Ignoring operational limits and output-token cost.", "Coupling business logic to one provider's response shape."], ["openaiEvals", "mistralModels", "deepseekModels"], ["choose AI model", "LLM comparison", "production model selection"]),
  p("models", "open-vs-closed-models", "Open-Weight vs Hosted AI Models: A Deployment Decision", "Compare control, operations, licensing, data handling, and performance before self-hosting or buying an API.", "Open weights can offer deployment control and customization, but the operator owns serving, patching, abuse prevention, and capacity. Hosted APIs reduce infrastructure work but introduce vendor, policy, and data-processing dependencies. Decide from total risk and cost.", ["Document data residency, retention, and isolation requirements.", "Estimate hardware and engineering cost at realistic utilization.", "Review the exact model license and acceptable-use terms.", "Benchmark quality and operations with the same workload."], ["Test failover and upgrades.", "Include monitoring and security labor in cost.", "Verify quantized or hosted variants match the evaluated artifact."], ["Calling every downloadable model open source.", "Comparing API list price with only raw GPU rental.", "Assuming self-hosting automatically provides privacy."], ["llama", "qwen", "mistralModels"], ["open-weight vs hosted models", "self-hosted LLM", "AI deployment decision"]),
  p("models", "deepseek-api-integration", "Integrate the DeepSeek API Without Locking Your Application", "Use an adapter, capability checks, strict validation, and live documentation for a resilient DeepSeek integration.", "Treat API-format compatibility as a migration aid, not proof of identical behavior. Put provider-specific model names, thinking controls, tool semantics, errors, and rate limits behind an adapter and test every capability you depend on.", ["Read the current model and API pages before selecting identifiers.", "Create a provider-neutral request and response contract.", "Map tool calls, usage, finish reasons, and errors explicitly.", "Run contract tests against streaming and non-streaming paths."], ["Validate tool arguments server-side.", "Test unsupported parameter behavior rather than assuming it is ignored.", "Pin configuration and monitor deprecation notices."], ["Hard-coding a model alias throughout the product.", "Assuming OpenAI-compatible means feature-identical.", "Copying old pricing or context limits into permanent application logic."], ["deepseekFunctions", "deepseekModels", "deepseekTransparency"], ["DeepSeek API integration", "OpenAI compatible API", "DeepSeek function calling"]),
  p("models", "kimi-k2-deployment-checklist", "A Deployment Checklist for Kimi Open-Weight Models", "Verify the model card, hardware fit, serving stack, tool format, and license before deploying Kimi models.", "Start with the official Moonshot repository and the exact checkpoint documentation. Confirm memory requirements, tokenizer and chat template, precision, supported serving engines, tool-call format, and license. Then benchmark your chosen quantization on your own tasks.", ["Record the exact repository revision and checkpoint checksum.", "Choose a supported inference engine and validate its recommended flags.", "Test the official chat template and tool-call parser.", "Load-test context lengths and concurrency that match production."], ["Compare quality before and after quantization.", "Inspect out-of-memory and overload behavior.", "Review license and third-party notice obligations."], ["Using community defaults without checking the official model card.", "Assuming one benchmark predicts agent reliability.", "Serving an enormous model at low utilization without cost analysis."], ["kimi", "nvidiaServing"], ["Kimi K2 deployment", "Moonshot AI models", "open-weight model serving"]),
  p("models", "qwen-deployment-checklist", "A Practical Qwen Model Deployment Checklist", "Select the right Qwen variant, template, precision, and serving engine while preserving reproducibility.", "Qwen is a family, not one interchangeable model. Match the exact variant to language, modality, context, and compute needs. Follow official documentation for templates and deployment, then record every artifact and runtime setting used in evaluation.", ["Define workload languages, modalities, latency, and memory limits.", "Select a specific model and verify its license and model card.", "Use the documented tokenizer and conversation template.", "Benchmark supported quantization and serving options under load."], ["Run multilingual and domain-specific eval slices.", "Check tool-call and structured-output behavior if required.", "Verify output quality after runtime or kernel upgrades."], ["Using the wrong chat template.", "Comparing differently quantized variants as if identical.", "Selecting parameter count without measuring activated compute and memory."], ["qwen", "nvidiaServing"], ["Qwen deployment", "Qwen model selection", "open model inference"]),
  p("models", "llama-self-hosting", "Self-Hosting Llama: What to Validate Before Production", "Cover licensing, weights, serving, safety, evaluation, and operations for a responsible Llama deployment.", "Self-hosting gives control over infrastructure, not freedom from product responsibilities. Verify the specific Llama license, obtain artifacts from an authorized source, select a maintained serving stack, and add your own access controls, moderation, monitoring, and incident process.", ["Document the model version, checksum, tokenizer, and template.", "Size GPU memory for weights, KV cache, concurrency, and headroom.", "Apply application-level safety controls appropriate to the use case.", "Benchmark quality, throughput, and tail latency after every optimization."], ["Run abuse and data-leakage tests.", "Exercise overload, restart, and rollback procedures.", "Confirm notices and attribution in distribution artifacts."], ["Treating a model's built-in safeguards as the whole safety system.", "Ignoring KV-cache memory in capacity plans.", "Downloading repackaged weights without provenance."], ["llama", "nvidiaServing"], ["self-host Llama", "Llama deployment", "LLM serving checklist"]),
  p("models", "mistral-function-calling", "Reliable Function Calling With Mistral Models", "Build a provider adapter, validate arguments, and test tool selection with official Mistral capabilities.", "Function calling lets a model request application functions; it does not execute or authorize them. Define narrow tools, parse the returned call, validate against schema and permissions, execute in trusted code, and return a compact result for the next model turn.", ["Choose a current model documented to support the required capability.", "Give every function a distinct purpose and strict parameter schema.", "Validate and authorize before execution.", "Handle multiple calls, tool errors, and no-call responses explicitly."], ["Test neighboring tools with similar names.", "Inject invalid and extra parameters.", "Confirm retries do not duplicate writes."], ["Executing model-generated JSON directly.", "Mixing secrets into tool descriptions.", "Assuming every model family supports identical tool behavior."], ["mistralFunctions", "mistralModels"], ["Mistral function calling", "Mistral AI tools", "LLM function calls"]),
  p("models", "model-upgrade-playbook", "An AI Model Upgrade Playbook With Safe Rollback", "Change models through pinned versions, regression evals, shadow traffic, canaries, and reversible configuration.", "Treat a model upgrade like a dependency and behavior change. Pin the candidate where possible, run offline regressions, shadow representative traffic, canary a small share, and preserve a one-step rollback. Prompts and tool schemas may need migration even when the API shape stays stable.", ["Capture the current model, prompt, tool, and retrieval baseline.", "Run fixed regression and fresh holdout evaluations.", "Compare cost, latency, refusals, formatting, and tool behavior.", "Canary with automatic rollback thresholds."], ["Inspect regressions by task slice.", "Test fallback compatibility before rollout.", "Store configuration revisions with each trace."], ["Switching a floating alias globally.", "Changing model and prompt in one untraceable release.", "Evaluating only average quality."], ["openaiEvals", "anthropicEvals"], ["AI model upgrade", "LLM migration", "model rollback"]),

  p("multimodal", "image-understanding-pipeline", "Build a Reliable Image Understanding Pipeline", "Prepare images, preserve provenance, structure outputs, and verify visual claims before using multimodal results.", "Use the original or an appropriate-resolution image, provide the task and expected output schema, and preserve image identifiers. Verify high-impact visual claims with deterministic processing, a second pass, or human review because confident descriptions can still be wrong.", ["Normalize orientation, format, and resolution without discarding needed detail.", "Send only task-relevant images and label each one clearly.", "Request structured fields with an explicit unknown option.", "Store source coordinates or image IDs with extracted claims."], ["Test small text, occlusion, unusual aspect ratios, and blank images.", "Measure field-level accuracy rather than prose similarity.", "Check accessibility and consent for uploaded images."], ["Asking one vague question about a contact sheet.", "Treating OCR-like output as exact.", "Removing provenance after extraction."], ["geminiImage", "openaiResponses"], ["image understanding AI", "multimodal pipeline", "vision language model"]),
  p("multimodal", "document-ai-extraction", "Extract Structured Data From Documents With Multimodal Models", "Combine file parsing, page images, schemas, citations, and validation for dependable document extraction.", "Use native text extraction when available, page images when layout matters, and a strict output schema for target fields. Preserve page references and mark uncertainty. Validate totals, dates, identifiers, and cross-field rules before downstream use.", ["Classify document type and detect unreadable or missing pages.", "Extract text and layout with stable page identifiers.", "Ask for only required fields plus page evidence.", "Run domain validations and send exceptions to review."], ["Create a labeled set spanning templates and scan quality.", "Measure exact field accuracy and missing-field behavior.", "Test prompt injection embedded inside documents."], ["Sending hundreds of pages without retrieval.", "Guessing absent values.", "Discarding page-level evidence."], ["geminiImage", "openaiStructured"], ["document AI extraction", "multimodal document processing", "structured data extraction"]),
  p("multimodal", "video-understanding", "Practical Video Understanding With Multimodal AI", "Sample video deliberately, keep timestamps, separate audio and visual evidence, and evaluate event recall.", "Video analysis is an evidence-selection problem. Choose sampling and clipping based on event duration, preserve timestamps, transcribe audio separately when needed, and require outputs to identify whether a claim came from frames, audio, or both.", ["Define the events, entities, and time precision required.", "Segment long video and select frames without losing short events.", "Attach timestamps to transcripts and visual observations.", "Merge segments with overlap and deduplicate events."], ["Test fast cuts, silence, off-screen speech, and repeated events.", "Measure temporal localization as well as label accuracy.", "Review consent, biometric, and retention requirements."], ["Uniform sparse sampling for every task.", "Presenting inferred intent as observed fact.", "Losing timestamps during summarization."], ["geminiVideo", "geminiLong"], ["video understanding AI", "multimodal video analysis", "video summarization"]),
  p("multimodal", "audio-understanding", "Audio Understanding Beyond Transcription", "Design an audio pipeline for transcription, speaker turns, acoustic events, and grounded summaries.", "Separate tasks that need different evidence: speech transcription, speaker attribution, language identification, non-speech events, and semantic summarization. Keep timestamps and uncertainty so the final application can distinguish heard content from model inference.", ["Normalize audio while retaining an untouched original.", "Segment by duration and silence with overlap at boundaries.", "Request timestamped outputs and an unknown-speaker label.", "Summarize only after merging and validating segment evidence."], ["Evaluate noisy, accented, overlapping, and silent audio.", "Measure word or segment errors separately from summary quality.", "Confirm retention and consent rules for voice data."], ["Inventing speaker names from voice alone.", "Dropping low-confidence sections.", "Using a polished summary as the transcription record."], ["geminiAudio", "geminiLive"], ["audio understanding AI", "speech transcription pipeline", "multimodal audio"]),
  p("multimodal", "realtime-voice-agents", "Build Safer Real-Time Voice Agents", "Handle latency, interruptions, turn detection, tool calls, consent, and fallback in live voice systems.", "A voice agent needs an explicit real-time state machine. Track listening, thinking, speaking, interrupted, tool-pending, and ended states. Make interruption immediate, keep tool actions separately authorized, and provide a visible or audible route to a human.", ["Set latency budgets for capture, inference, tools, and playback.", "Implement barge-in and cancel queued audio on interruption.", "Confirm identity and intent before sensitive actions.", "Summarize completed actions and expose correction paths."], ["Test background speech, packet loss, echo, and rapid interruptions.", "Verify a cancelled utterance cannot trigger a delayed tool call.", "Measure task success and user correction rate, not only response speed."], ["Treating silence as consent.", "Allowing spoken content to bypass tool policy.", "Hiding that the user is interacting with AI."], ["geminiLive", "openaiSafety"], ["real-time voice agents", "voice AI safety", "Live API"]),
  p("multimodal", "multimodal-rag", "Multimodal RAG for Text, Images, and Tables", "Index each modality with provenance, retrieve at the right granularity, and cite original evidence.", "Do not flatten every modality into one lossy text summary. Store extracted text, page or image regions, captions, table structure, and source metadata. Retrieve candidates across modalities, rerank for the question, and provide the original evidence to the model.", ["Choose chunks based on document structure and visual boundaries.", "Link derived text and embeddings to immutable source locations.", "Retrieve separately by modality, then rerank jointly.", "Return citations that a user can open at the relevant page or region."], ["Evaluate retrieval recall before generation quality.", "Test questions answerable only from charts or tables.", "Check that citations support the exact claim."], ["OCR-only indexing of layout-heavy documents.", "Embedding whole files as one chunk.", "Citing a document title without a page or region."], ["geminiImage", "geminiLong"], ["multimodal RAG", "image retrieval augmented generation", "document retrieval AI"]),
  p("multimodal", "visual-prompt-injection", "Defend Multimodal Agents Against Visual Prompt Injection", "Treat text inside images and documents as untrusted data, not system instructions.", "An image can contain instructions intended for the model rather than the user. Keep system policy separate, label visual content as untrusted, restrict tools, require authorization for side effects, and validate actions in code. No prompt can replace these controls.", ["Threat-model screenshots, PDFs, web pages, QR codes, and retrieved images.", "Tell the model to extract relevant content without following embedded commands.", "Use least-privilege tools and confirmation for consequential actions.", "Detect unexpected tool requests and retain redacted security traces."], ["Add benign and adversarial visual instructions to the test set.", "Verify the same policy holds across OCR and native vision paths.", "Test mixed trusted and untrusted images."], ["Relying on a warning sentence alone.", "Giving a browsing agent broad credentials.", "Displaying external content without origin labels."], ["openaiSafety", "mcpSecurity"], ["visual prompt injection", "multimodal AI security", "indirect prompt injection"]),
  p("multimodal", "multimodal-evaluation", "Evaluate Multimodal AI With Evidence-Level Metrics", "Measure perception, grounding, extraction, reasoning, and abstention separately.", "A single similarity score hides where a multimodal system fails. Evaluate whether it perceived the right region or time, extracted the right value, connected evidence correctly, and abstained when evidence was missing. Keep task slices for quality, language, and input corruption.", ["Label source regions, timestamps, or pages where feasible.", "Define field-level or event-level correctness.", "Add impossible and insufficient-evidence cases.", "Review disagreements with the original media visible."], ["Track performance by modality and corruption type.", "Measure unsupported-claim rate.", "Test after preprocessing or compression changes."], ["Using text-only graders without media access.", "Ignoring abstention quality.", "Evaluating clean benchmark images only."], ["openaiEvals", "geminiImage"], ["multimodal evaluation", "vision model evals", "AI grounding metrics"]),

  p("inference", "reduce-llm-latency", "Reduce LLM Latency Before Changing Models", "Cut sequential calls, shorten outputs, stream useful progress, cache stable prefixes, and parallelize independent work.", "Start with architecture. The largest wins often come from fewer serial model calls and shorter generated outputs. Then optimize prompt size, cache reusable prefixes, parallelize independent retrieval, and choose a faster model only after measuring the quality trade-off.", ["Break total latency into queue, input, first-token, generation, and tool time.", "Remove unnecessary model turns and combine deterministic processing.", "Set concise output contracts and realistic token limits.", "Stream user-visible progress without pretending unfinished work is complete."], ["Track p50 and p95 by task class.", "Measure task success after every optimization.", "Load-test with real concurrency and output lengths."], ["Optimizing average latency only.", "Streaming verbose text that users do not need.", "Shrinking context without checking retrieval failures."], ["openaiLatency", "geminiCaching"], ["reduce LLM latency", "AI inference optimization", "time to first token"]),
  p("inference", "prompt-caching", "Prompt Caching: Structure Requests for Reuse", "Place stable prefixes first, separate volatile data, monitor cache hits, and protect tenant boundaries.", "Caching works best when many requests share an identical or sufficiently similar prefix. Put stable instructions and reusable reference material before volatile user data, avoid meaningless prompt changes, and verify provider-specific caching, retention, and billing behavior.", ["Measure repeated input volume by prompt segment.", "Order content from stable to dynamic where the API recommends it.", "Version shared prompts intentionally instead of injecting timestamps.", "Monitor cached-token usage, latency, cost, and correctness."], ["Test cache isolation across tenants.", "Confirm policy updates invalidate old prefixes.", "Compare total cost at production request rates."], ["Caching user-specific secrets in shared layers.", "Assuming every request receives a cache hit.", "Changing stable prompts on every deployment without need."], ["geminiCaching", "openaiLatency"], ["prompt caching", "LLM context cache", "AI inference cost"]),
  p("inference", "batch-inference", "When to Use Batch Inference for AI Workloads", "Move delay-tolerant, independent jobs to batches while preserving identifiers, retries, and quality checks.", "Batching is appropriate when tasks do not depend on immediate responses and can be processed independently: offline classification, embeddings, backfills, and evaluation runs. Keep interactive and dependent agent loops on synchronous paths.", ["Set a service-level deadline for the workload.", "Create stable item IDs and idempotent output writes.", "Group compatible model and configuration requests.", "Reconcile partial failures rather than rerunning an entire batch blindly."], ["Verify one output per input ID.", "Measure queue time and completion distribution.", "Compare price and operational overhead with synchronous traffic."], ["Batching multi-step tasks whose next input depends on the prior output.", "Losing item identity in concatenated prompts.", "Ignoring cancellation and data-retention requirements."], ["openaiResponses", "geminiCaching"], ["batch inference", "LLM batch processing", "offline AI workloads"]),
  p("inference", "quantization-quality", "Quantization for LLM Serving: Measure the Quality Trade-Off", "Reduce memory and increase throughput only after evaluating the exact quantized artifact on your tasks.", "Quantization changes numerical precision and can affect quality unevenly. Select a method supported by the model and runtime, verify hardware kernels, and compare the exact artifact against the higher-precision baseline on difficult and safety-critical slices.", ["Record model, quantization method, calibration data, runtime, and hardware.", "Measure memory, throughput, first-token time, and tokens per second.", "Run fixed quality and tool-use evaluations.", "Check long-context and high-concurrency behavior."], ["Inspect regressions by language and task type.", "Verify tokenizer and templates are unchanged.", "Repeat tests after runtime upgrades."], ["Assuming a bit-width guarantees a quality level.", "Comparing community artifacts without provenance.", "Reporting throughput without concurrency and output length."], ["nvidiaServing", "qwen"], ["LLM quantization", "quantized model quality", "AI serving optimization"]),
  p("inference", "kv-cache", "KV Cache Planning for LLM Inference", "Estimate memory from context, concurrency, model architecture, precision, and reuse before promising capacity.", "Weights are only part of serving memory. The key-value cache grows with active sequence length and concurrent requests, so long contexts can sharply reduce capacity. Measure with the exact runtime and scheduling policy rather than relying on a simple model-size estimate.", ["Define input and output length distributions.", "Measure per-request cache use for the selected model and precision.", "Reserve memory for weights, runtime workspace, fragmentation, and safety margin.", "Test prefix reuse, paging, or eviction behavior if supported."], ["Load-test mixed short and long requests.", "Observe rejection, preemption, and tail latency.", "Verify isolation when cache reuse spans requests."], ["Sizing only for model weights.", "Advertising maximum context at maximum concurrency.", "Ignoring memory fragmentation and runtime overhead."], ["nvidiaServing", "nvidiaDynamo"], ["KV cache LLM", "LLM inference memory", "long context serving"]),
  p("inference", "prefill-decode-disaggregation", "Prefill and Decode Disaggregation: When It Helps", "Separate compute-heavy prompt processing from memory-bandwidth-heavy token generation only for the right workload and scale.", "Disaggregation can improve utilization when prefill and decode have different hardware or scaling needs, especially under large, variable prompts. It also adds networking, scheduling, state transfer, and operational complexity. Benchmark against a well-tuned combined deployment.", ["Profile time and resource use in prefill and decode separately.", "Characterize prompt length, output length, and concurrency distributions.", "Measure transfer overhead and scheduler behavior.", "Adopt only if end-to-end throughput or tail latency improves at target load."], ["Test bursty and mixed workloads.", "Include failures during state transfer.", "Compare total hardware and operational cost."], ["Applying a hyperscale topology to a small service.", "Reporting component speed instead of user latency.", "Ignoring network bandwidth and failure domains."], ["nvidiaDynamo", "nvidiaServing"], ["prefill decode disaggregation", "LLM serving architecture", "distributed inference"]),
  p("inference", "model-routing-cost", "Cost-Aware Model Routing Without Silent Quality Loss", "Route tasks among models using validated task classes, hard constraints, and escalation rather than price alone.", "A cost router should preserve a minimum quality threshold. Use observable task features, start with the cheapest qualified model, verify outputs where possible, and escalate on failure. Keep sensitive or regulated tasks out of routes that violate policy regardless of cost.", ["Define task classes and mandatory capabilities.", "Benchmark candidate models per class.", "Build deterministic pre-routing for obvious cases.", "Add bounded escalation based on verification failure."], ["Track quality, cost, latency, and escalation rate together.", "Test router drift as traffic changes.", "Log provider and model decisions for audit."], ["Letting a model route based only on its own confidence.", "Optimizing average price while expensive retries rise.", "Sending data to a provider outside the approved boundary."], ["openaiEvals", "mistralModels", "deepseekModels"], ["cost-aware model routing", "LLM router", "AI inference cost optimization"]),
  p("inference", "inference-benchmark", "Benchmark an LLM Inference Server Correctly", "Report workload, hardware, concurrency, prompt and output lengths, latency percentiles, throughput, and quality together.", "A useful benchmark reproduces the intended workload. Warm the server, control request distributions, report time to first token and inter-token latency, and include p95 or p99 under sustained concurrency. Throughput without quality and workload details is not comparable.", ["Pin model artifact, runtime version, flags, drivers, and hardware.", "Generate a request distribution matching production.", "Warm caches, then run long enough to reach steady state.", "Report errors, queueing, latency percentiles, and tokens per second."], ["Repeat runs and publish variance.", "Verify outputs are valid and quality has not collapsed.", "Test overload and admission-control behavior."], ["Comparing different prompt or output lengths.", "Using only one request at a time.", "Omitting failed and rejected requests."], ["nvidiaServing", "nvidiaDynamo"], ["LLM inference benchmark", "tokens per second", "time to first token"]),

  p("safety-evaluation", "prompt-injection-defense", "Prompt Injection Defense for Tool-Using AI Agents", "Combine trust separation, least privilege, validation, approvals, and monitoring because prompts alone cannot secure agents.", "Treat retrieved pages, emails, files, images, and tool results as untrusted data. Keep policy separate, restrict available tools, validate every call in code, require approval for consequential actions, and minimize credentials and data exposure.", ["Map every place untrusted content can enter context.", "Label source and trust level in structured context.", "Enforce authorization outside the model.", "Add adversarial cases to continuous evaluations."], ["Attempt data exfiltration and privilege escalation.", "Test indirect instructions inside each supported modality.", "Confirm blocked actions leave an auditable event."], ["Using 'ignore malicious instructions' as the only defense.", "Giving browsing and write tools the same broad token.", "Returning secrets in tool errors."], ["openaiSafety", "mcpSecurity"], ["prompt injection defense", "AI agent security", "indirect prompt injection"]),
  p("safety-evaluation", "agent-evaluation", "Evaluate AI Agents End to End", "Measure task success, policy compliance, tool behavior, efficiency, and recovery across complete trajectories.", "Agent evaluation must inspect more than the final answer. Score whether the task was completed, tools were chosen and called correctly, evidence supports claims, policies were respected, and the system stopped efficiently or recovered safely.", ["Define outcome and process criteria from real tasks.", "Capture structured trajectories with redacted tool events.", "Use deterministic graders for actions and state changes.", "Add rubric or human review only for subjective dimensions."], ["Test repeated runs for variance.", "Include tool failures, stale data, and permission denial.", "Report results by task and risk slice."], ["Grading only the final prose.", "Rewarding longer trajectories.", "Letting the same model author every test and grade every result."], ["anthropicEvals", "openaiEvals"], ["AI agent evaluation", "agent trajectory evals", "LLM task success"]),
  p("safety-evaluation", "tool-call-evals", "Build Tool-Call Evaluations for AI Agents", "Test tool selection, arguments, sequencing, authorization, recovery, and unnecessary calls with executable fixtures.", "A tool-call eval should assert the intended operation and state transition, not demand one exact natural-language trace. Use fake or sandbox tools, seed controlled state, and check required calls, forbidden calls, argument properties, and final state.", ["Create fixtures for common and boundary tasks.", "Record allowed, required, and forbidden tool effects.", "Inject typed errors and stale-state responses.", "Score both completion and efficiency."], ["Test write idempotency and duplicate calls.", "Verify denied operations stay denied after retries.", "Review near-miss arguments that pass schema but violate business rules."], ["Exact-match grading of call order when order is irrelevant.", "Testing against production systems.", "Ignoring unnecessary expensive calls."], ["openaiEvals", "anthropicTools"], ["tool call evaluation", "AI agent evals", "function calling tests"]),
  p("safety-evaluation", "rag-evaluation", "Evaluate RAG Before Tuning the Generator", "Separate retrieval recall, ranking, context quality, answer support, and citation correctness.", "Diagnose retrieval-augmented generation in stages. First confirm the needed evidence exists and is retrieved. Then test ranking and context assembly. Only after that should you evaluate whether the model answers faithfully and cites the supporting passage.", ["Create questions with labeled source passages and unanswerable cases.", "Measure retrieval recall at several cutoffs.", "Inspect reranking and duplicate chunks.", "Score answer correctness, support, and citation precision separately."], ["Run ablations with oracle evidence.", "Test stale and conflicting documents.", "Verify access control before retrieval results enter context."], ["Changing embeddings and prompts simultaneously.", "Using answer similarity as a retrieval metric.", "Forcing an answer when evidence is absent."], ["anthropicContext", "openaiEvals"], ["RAG evaluation", "retrieval augmented generation evals", "citation accuracy"]),
  p("safety-evaluation", "llm-as-judge", "Use LLM-as-a-Judge Carefully", "Design rubrics, randomize ordering, calibrate against humans, and keep deterministic checks first.", "Model judges are useful for nuanced qualities but can be biased by style, length, position, or self-preference. Give a concrete rubric and evidence, hide irrelevant identity, randomize pair order, and validate judge agreement against expert labels.", ["Define dimensions and anchored score examples.", "Use deterministic graders before subjective judging.", "Run pairwise order swaps and repeated judgments.", "Escalate low-agreement or high-risk cases to humans."], ["Measure agreement and bias by answer length and model source.", "Keep a private calibration set.", "Version judge model, prompt, and rubric."], ["One vague 'which is better?' prompt.", "Using the candidate model as its only judge.", "Reporting judge scores as objective truth."], ["openaiEvals", "anthropicEvals"], ["LLM as a judge", "model-based evaluation", "AI evaluation rubric"]),
  p("safety-evaluation", "red-team-agents", "Red-Team an AI Agent With Realistic Attack Paths", "Test untrusted content, tool abuse, data boundaries, identity, and recovery in a controlled environment.", "Red teaming should follow the agent's actual attack surface: prompts, retrieved content, files, browser pages, tools, credentials, memory, and remote agents. Use sandbox accounts and synthetic data, then turn each confirmed weakness into a regression test.", ["Map assets, actors, trust boundaries, and high-impact actions.", "Create attacks for injection, exfiltration, unauthorized writes, and denial of service.", "Run tests in an isolated environment with kill switches.", "Record root cause and add a durable control plus regression case."], ["Verify controls at model, application, and tool layers.", "Test chained attacks rather than isolated strings.", "Retest after model and tool changes."], ["Testing only jailbreak phrases.", "Using real customer data in attack fixtures.", "Fixing one prompt without addressing missing authorization."], ["openaiSafety", "mcpSecurity"], ["red team AI agents", "agent security testing", "AI attack paths"]),
  p("safety-evaluation", "privacy-ai-applications", "Privacy Engineering for AI Applications", "Minimize data, define retention, isolate tenants, control logs, and make deletion testable.", "Collect and send only data required for the task. Document where prompts, files, embeddings, caches, traces, and backups go; who can access them; how long they remain; and how deletion propagates. Provider settings do not replace application governance.", ["Create a data-flow inventory for every model and tool call.", "Classify fields and redact before logging or evaluation storage.", "Apply tenant-aware authorization to retrieval and memory.", "Test access, export, correction, and deletion procedures."], ["Inspect logs and traces for accidental secrets.", "Verify retention jobs and backup policies.", "Review subprocessors and regional processing requirements."], ["Sending full records when a few fields suffice.", "Using production prompts as an unlabeled eval corpus.", "Claiming zero retention without checking every connected service."], ["openaiSafety", "mcpSecurity"], ["AI privacy engineering", "LLM data retention", "tenant isolation AI"]),
  p("safety-evaluation", "continuous-ai-evals", "Continuous AI Evaluations in CI and Production", "Run fast regression gates on every change and monitor sampled real-world outcomes without leaking user data.", "Use a layered eval program: small deterministic checks in each pull request, broader offline suites before release, canary comparisons during rollout, and privacy-reviewed production monitoring. Every failure should map to an owner and a release decision.", ["Version datasets, graders, prompts, tools, and model configuration.", "Set blocking thresholds for critical task and safety slices.", "Keep a private holdout set to detect overfitting.", "Sample and redact production cases under a documented policy."], ["Track confidence intervals and repeated-run variance.", "Alert on slice regressions even when the average improves.", "Verify rollback is fast and tested."], ["One giant eval run nobody can interpret.", "Updating tests to make a failing release pass.", "Storing sensitive production traces indefinitely."], ["openaiEvals", "anthropicEvals"], ["continuous AI evaluation", "LLM evals CI", "production AI monitoring"]),
];

export function blogPostPath(post) {
  return `/blog/${post.category}/${post.slug}.md`;
}

function lineList(items) {
  return items.map((item, index) => `${index + 1}. ${item}`).join("\n");
}

function bulletList(items) {
  return items.map((item) => `- ${item}`).join("\n");
}

export function renderBlogPost(post) {
  const canonical = `https://navinresearch.com${blogPostPath(post)}`;
  const sourceLines = post.sources.map((key) => {
    const source = blogSources[key];
    if (!source) throw new Error(`Unknown blog source: ${key}`);
    return `- [${source[0]}](${source[1]})`;
  }).join("\n");
  return `---
title: "${post.title.replaceAll('"', '\\"')}"
description: "${post.description.replaceAll('"', '\\"')}"
language: en
canonical: ${canonical}
topics: [${post.keywords.map((keyword) => `"${keyword}"`).join(", ")}]
---

# ${post.title}

${post.description}

**Short answer:** ${post.answer}

## Implementation steps

${lineList(post.steps)}

## Validation checklist

${bulletList(post.checks)}

## Common mistakes

${bulletList(post.pitfalls)}

## Practical decision

Ship the smallest design that passes the checks above. Record the model, prompt, tool, dataset, and runtime versions used in testing so later changes can be compared rather than guessed. Recheck the linked documentation before relying on provider-specific limits, model names, prices, or preview features; those details change more quickly than the engineering principles in this note.

## Official sources

${sourceLines}

---

Reviewed: 2026-08-24. This concise engineering note is educational, not a claim that Navin Research created or independently verified the cited provider technology.
`;
}
